### ISSUE TITLE
Bug: mongo查询成功，没有任何值

### ISSUE THREAD

**Issue by VincentYuan-hub** [chat2db/Chat2DB#1]
### Chat2DB Version

1.0.11

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/41802365/7d3df891-a9f0-4909-a969-7db71a58e324)

另外默认mongo的查询语句也不对。希望对mongo的支持能更好些。我看readme确定是支持mongodb的

**Comment by cnwelee** [comment]
+1，redis默认的查询语句也不对，就感觉这项目上线是不是太赶了

**Comment by chenxian01** [comment]
The old version will not be supported, please try the latest version. If you still have this issue in new version, please submit a new issue.
