### ISSUE TITLE
Bug: 编辑数据源时，带特殊字符的数据库名称无法保存

### ISSUE THREAD

**Issue by dongjialiang** [chat2db/Chat2DB#10]
### Chat2DB Version

1.0.11

### Describe the bug

1、编辑数据源，黏贴数据库名称，点击修改，再打开数据源的弹窗，数据库名称为空。
2、改为在URL中输入数据库名称，数据库名称中的特殊字符以及后面的字符没有在数据库一栏显示，像是名称被截断了一样。这个名称我在Navicat和DBeaver中输入是可以完整显示的。
3、黏贴没有特殊字符的数据库名称，点击修改，再打开数据源弹窗，此时数据库名称不为空。
以上操作是可以在Win10 1809上复现。
特殊字符我试了"."，"("，")"三个字符都不行，"_"可以。
不知道这属于Bug，还是属于设计的合理限制输入。
您看下是否能解除限制？如果是输入特殊字符可能存在风险，希望能在输入栏的一侧增加解释说明。

**Comment by shanhexi** [comment]
可以试试2.0.0解决了没有，
如果没有解决可以提供一下截图，

**Comment by dongjialiang** [comment]
> 可以试试2.0.0解决了没有， 如果没有解决可以提供一下截图，

解决了，谢谢
