### ISSUE TITLE
Bug: 放置一段时间不用后，会出现明明空间无法关闭，双击后无限延长的情况

### ISSUE THREAD

**Issue by Jimecc** [chat2db/Chat2DB#1001]
### Chat2DB Version

 v3.1.14 （Windows）

### Describe the bug

今天刚更新，遇到这个情况两次了。
场景描述：软件开在那里做别的事情，一段时间没有用它，点回去之后之前打开的表无法关闭了，双击（我点的是红框框内的向下箭头）后，该表下的明明空间会无限延长显示，一直重复的向下添加，此时点击表名或者箭头都无法关闭该表，只有刷新后才可以关闭。

目前只判断了第一张表，其他几张表没有尝试。

![image](https://github.com/chat2db/Chat2DB/assets/41030702/0b7e07e1-56fb-492f-8564-6002fcf90166)

**Comment by Jimecc** [comment]
更新：我在使用第二个表的时候，第一张表自动打开了，并且无法关闭，刷新才能关闭。
![image](https://github.com/chat2db/Chat2DB/assets/41030702/36a6e5c6-5b80-485f-acd8-195b94b981ee)

**Comment by shanhexi** [comment]
已解决晚上发布

**Comment by Jimecc** [comment]
我测试了一下，发现之前描述的不太对：
## 当我使用其它表的时候，第一个表会突然打开，然后出现上面的第一张表无法关闭双击无限延长的情况
复现条件：长时间没有用软件，或同时打开两张表（点击表左侧向下的箭头或者表的图标更容易触发，点击名字不容易触发，但是也会）

<br>

3. 当我A表打开的时候，打开B表，A表不会自动关闭，且双击A表会出现1中的情况（这时候打开C表，AB表都会出现此现象，也就是说此时已经允许一次性打开多张表了）

<br>

4. 当我当前打开的表超过两个的时候，我双击最上方的表，其他表也会出现叠加的情况（也就是说不用点击B表B表也会叠加），这个现象的出现比较随机，且并不是每个非点击表都会增长

<br>

5. 由于列表会无限叠加，因此当表的长度超出我的屏幕长度（也就是侧边的滚动条长度不是100%的时候，我滑动鼠标，列表将会无限延长，直至下拉条变得很小很小），见下面的两张图
触发条件：已经触发了1，同时滚动条的长度小于等于90%左右
![image](https://github.com/chat2db/Chat2DB/assets/41030702/be29f805-b722-472d-b896-2f2895f57761)

轻轻滚动鼠标，达到这种效果：

![image](https://github.com/chat2db/Chat2DB/assets/41030702/bee5f84b-a110-4706-870e-99a2f906502c)

**Comment by Jimecc** [comment]
> 已解决晚上发布

好的，感谢

**Comment by shanhexi** [comment]
3.1.15已修复
