### ISSUE TITLE
Bug:左侧表的菜单栏无法显示新增的表,但是sql语句可以查询出来

### ISSUE THREAD

**Issue by manallen** [chat2db/Chat2DB#1020]
### Chat2DB Version

3.1.15

### Describe the bug

左侧表的菜单栏无法显示新增的表,但是sql语句可以查询出来,其他工具navicate,dbeaver可以显示

这个表是在navicate新增的

![dbeaver](https://github.com/chat2db/Chat2DB/assets/33803392/26eae848-e069-4461-8463-b947624c701a)
![navi](https://github.com/chat2db/Chat2DB/assets/33803392/2e5aa84a-b990-41df-b1c8-f1658db2633a)
![333](https://github.com/chat2db/Chat2DB/assets/33803392/c9896127-efc8-4ca9-b8bc-9b4bb393a296)

**Comment by manallen** [comment]
已更新的3.1.16  问题同样存在

**Comment by miahemu** [comment]
你好，这个问题可以点击鼠标右键进行表的刷新可以解决：
![image](https://github.com/chat2db/Chat2DB/assets/157001655/e84c8b0e-8ad1-4cab-b1c1-c212581ec6b1)
