### ISSUE TITLE
Bug: 点击修改表报错

### ISSUE THREAD

**Issue by CaptainTim0** [chat2db/Chat2DB#1024]

**Comment by CaptainTim0** [comment]
![1703582901998](https://github.com/chat2db/Chat2DB/assets/102003285/9eefe2c7-baa8-41c2-8c0a-b6e1cbbe3cb1)

**Comment by miahemu** [comment]
你好可以发一些具体的截图看看嘛？

**Comment by CaptainTim0** [comment]
新版本不报错了
