### ISSUE TITLE
优化: 能否在查询列表中增加筛选条件

### ISSUE THREAD

**Issue by tanhao-github** [chat2db/Chat2DB#1025]

**Comment by Awarahou** [comment]
+1

**Comment by HackerYH** [comment]
加一

**Comment by qingshanking** [comment]
建议查询表数据上侧增加类似Navicat 这种筛选条件功能，右下角条数也增加全部或者指定分页的功能。
![image](https://github.com/chat2db/Chat2DB/assets/22401257/d004a601-4750-4f45-b9a0-8526b7f3a99f)

**Comment by dongzhichaogeek** [comment]
+1
