### ISSUE TITLE
Bug: After switching data connections in different environments, the data source of the table opened from the left does not change.

### ISSUE THREAD

**Issue by 1097886344** [chat2db/Chat2DB#1034]
### Chat2DB Version

3.1.17

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/46391293/ad75fa4f-2002-4a78-a597-48ee1c42994b)
![image](https://github.com/chat2db/Chat2DB/assets/46391293/dba88735-cddc-4cce-b405-199a0666937c)

As shown in the figure, the two data sources are different, and the data is also different. However, after switching, the data from the previous data source is still displayed. Clicking the refresh button is useless. You can only clear the search results, reopen the database, and click the table to change the

**Comment by miahemu** [comment]
try new version
