### ISSUE TITLE
Bug: docker版启动后无法访问  页面解析失败

### ISSUE THREAD

**Issue by GuXiaozhou** [chat2db/Chat2DB#1037]
### Chat2DB Version

3.1.17

### Describe the bug

![3](https://github.com/chat2db/Chat2DB/assets/24451541/a28ca0e1-2d56-4fd8-b12b-d482b641aed5)
![1](https://github.com/chat2db/Chat2DB/assets/24451541/88769741-0661-4432-bc73-b046b158365f)
![2](https://github.com/chat2db/Chat2DB/assets/24451541/69055a54-8c99-41e7-81e3-ee94ef9a9704)

**Comment by Arronlong** [comment]
https://github.com/chat2db/Chat2DB/issues/1031#issuecomment-1870994217
