### ISSUE TITLE
Bug: 表中date或者datetimezi字段查询结果在秒数后面多了一个小数位

### ISSUE THREAD

**Issue by renxiang0628** [chat2db/Chat2DB#1042]
### Chat2DB Version

3.1.17

**Comment by renxiang0628** [comment]
![Snipaste_2023-12-28_19-33-53](https://github.com/chat2db/Chat2DB/assets/29589366/12842127-9553-4720-9de0-8b42385cb728)

**Comment by miahemu** [comment]
timestamp在 MySQL 5.6 及以上版本中，会生成一个带有微秒级精度的时间戳，格式为 YYYY-MM-DD HH:MM:SS.microseconds，表示微秒部分。这就是为什么你看到的时间戳值可能会比标准格式多出一位小数位的原因。
