### ISSUE TITLE
Suggestion：Can you provide a shortcut key to execute the current sql?

### ISSUE THREAD

**Issue by wang19742008** [chat2db/Chat2DB#1044]
Can you provide a shortcut key to execute the current sql? Similar to dbeaver, each independent sql is separated by a semicolon. Ctrl+Enter executes the complete sql of the row where the mouse is located. Each semicolon is a complete sql. The mouse can be stopped on any row. This can prevent operational errors, incorrect execution of multiple SQL statements, and possible update/delete.

**Comment by williamlee1982** [comment]
这个真的是刚需，+1

**Comment by shanhexi** [comment]
> 这个真的是刚需，+1

Three clicks in a row can select this line, cmd+r can run, really do not know whether this is enough to meet the needs
