### ISSUE TITLE
Bug: Display problem of functions and procedures in Oracle

### ISSUE THREAD

**Issue by lessiky** [chat2db/Chat2DB#1061]
### Chat2DB Version

3.1.19

### Describe the bug

1. Some non-existent functions or procedures will be displayed on the left side of Oracle
![image](https://github.com/chat2db/Chat2DB/assets/6878770/72b38ba2-c84c-46e6-88f6-1d80908b94b9)
2. Some functions or procedures cannot be opened, and the ones that can be opened are also displayed repeatedly.
![image](https://github.com/chat2db/Chat2DB/assets/6878770/d062f037-358e-49f1-9268-caa95cbac8c3)
3. Every time you open chat2db, the tab on the right will automatically open the tab of the oracle view function or process that has been closed before.
![image](https://github.com/chat2db/Chat2DB/assets/6878770/6fb2de48-c5b1-4df3-a751-cbc848d30330)

**Comment by miahemu** [comment]
try pro version
https://chat2db.ai/zh-CN/download
