### ISSUE TITLE
建议: 可以复制已存在的链接

### ISSUE THREAD

**Issue by Mignet** [chat2db/Chat2DB#1062]
![image](https://github.com/chat2db/Chat2DB/assets/1306154/5da6c7ef-1718-489b-8fbd-824614ba7258)

**Comment by shanhexi** [comment]
Are you using 3.1.17? <img width="919" alt="image" src="https://github.com/chat2db/Chat2DB/assets/86969353/587e5d9a-9935-4cc9-b073-868e8a053f99">
