### ISSUE TITLE
Bug: 新增的表展示不出来

### ISSUE THREAD

**Issue by Yanch1994** [chat2db/Chat2DB#1076]
### Chat2DB Version

v3.1.17

### Describe the bug

别的软件加的表，我使用Chat2DB怎么刷新都显示不出来，重启软件也不行

**Comment by Yanch1994** [comment]
<img width="287" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/b9cd3fd5-722e-41a3-8b1d-70ff6d5785b7">
这里的刷新没有用。必须找到对应数据库的tables右击刷新才行

**Comment by shanhexi** [comment]
需要在tables上右键点击刷新
