### ISSUE TITLE
建议: RequestError: read ETIMEDOUT

### ISSUE THREAD

**Issue by youngledo** [chat2db/Chat2DB#1088]
本地yarn长时间没有响应，最后超时，已经设置了yarn镜像为淘宝，但是依旧不行。就算代理翻墙都不行，该如何处理？
<img width="1209" alt="image" src="https://github.com/chat2db/Chat2DB/assets/68590897/2ecdd99d-d781-41ea-af33-6f35cb600b69">

**Comment by shanhexi** [comment]
Solution 1：https://github.com/chat2db/Chat2DB/wiki/Chat2DB#q-%E5%89%8D%E7%AB%AF%E8%BF%90%E8%A1%8Cyarn%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E5%8D%A1%E5%9C%A8electron%E6%97%A0%E5%93%8D%E5%BA%94
Solution 2： If you don't need to package the desktop application, you can remove "electron": "^22.3.0" from package.json,
