### ISSUE TITLE
建议:console在保存的时候无法直接重命名

### ISSUE THREAD

**Issue by Luckytiger666** [chat2db/Chat2DB#1100]
保存新建的console时候，点击保存就直接保存下来了，正常情况下，是需要有重命名需求的，考虑保存新建的console时，增加命名窗口？

**Comment by shanhexi** [comment]
1. Save in the list you can right-click to modify the name
2. Double-click the tab TAB to change the name

**Comment by Luckytiger666** [comment]
Oh, I didn't notice I can double-click tab.
thanks.
