### ISSUE TITLE
Bug: 能否设置通过代理访问AI

### ISSUE THREAD

**Issue by JerryGerrit** [chat2db/Chat2DB#1109]
### Chat2DB Version

docker运行的最新版本

### Describe the bug

能否设置通过代理访问AI 

我看到这个链接提到 chat2db 客户端可以设置HTTP Proxy Host 和 HTTP Proxy Port， 但没说具体设置方法， 麻烦告知下，谢谢！
https://github.com/chat2db/Chat2DB/wiki/Chat2DB

**Comment by QingXiao111** [comment]
You can set it here.
![1](https://github.com/chat2db/Chat2DB/assets/92871355/5bed5592-0c98-4680-acb9-5bda9c629325)
