### ISSUE TITLE
抄袭？

### ISSUE THREAD

**Issue by sinbane** [chat2db/Chat2DB#1112]
https://redian.news/wxnews/724454

**Comment by csgirl562857639** [comment]
请作者正面回复……

**Comment by h3clikejava** [comment]
好问题。百度是抄袭google吗？QQ是抄袭ICQ吗？淘宝是抄袭amazon吗？微博是抄袭Twitter吗？

**Comment by Shawn-Huang-Tron** [comment]
抄袭是一回事儿，如果是直接偷源代码就是另外一回事儿了

**Comment by autumn0207** [comment]
借鉴是一回事，像素级抄袭是另外一回事

**Comment by EX-XD** [comment]
> 好问题。百度是抄袭google吗？QQ是抄袭ICQ吗？淘宝是抄袭amazon吗？微博是抄袭Twitter吗？

QQ还真是抄ICQ，不然你以为为什么以前叫OICQ

**Comment by panyox** [comment]
以前是国外一开源，国内就自研；现在反过来了，国内先开源，国外才自研，这怎么算是抄袭呢？[狗头]

**Comment by SwallowGG** [comment]
Chat2DB 回应： https://mp.weixin.qq.com/s/AxaMG0Lw1ijt4jsLs8xbLw

**Comment by 906051999** [comment]
艺术
