### ISSUE TITLE
建议: 后续会考虑添加显示达梦执行计划吗

### ISSUE THREAD

**Issue by huanghaifei1992** [chat2db/Chat2DB#112]
SQL语句：
EXPLAIN select * from BASE_THT_INFO WHERE XM = 'B2'；

返回执行计划：
1   #NSET2: [7, 1191, 194] 
2     #PRJT2: [7, 1191, 194]; exp_num(7), is_atom(FALSE) 
3       #SLCT2: [7, 1191, 194]; BASE_THT_INFO.XM = 'B2'
4         #CSCN2: [7, 47658, 194]; INDEX33555476(BASE_THT_INFO)

**Comment by robinji0** [comment]
marked in #404
