### ISSUE TITLE
Bug: The new filtering function added in 3.1.19 will be invalid if the /**/ comment is added.

### ISSUE THREAD

**Issue by YYHKING** [chat2db/Chat2DB#1134]
### Chat2DB Version

3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/10542719/9061b169-28ec-4dc3-8997-a4662061d1f5)
![image](https://github.com/chat2db/Chat2DB/assets/10542719/bcb0fd35-780a-49de-bcf5-878714e479e8)
I wanted to change the filter condition, but I didn’t want to delete the previous one, so I commented it out with /**/. It could still recognize that the comment turned green, but it couldn’t find anything.

The test library is sqlserver2016, which can filter normally under Oracle11g and mysql.

**Comment by miahemu** [comment]
new version already solved
