### ISSUE TITLE
Bug: After modifying the stored procedure, it was not saved. If I closed it and reopened it, I found that the modified content was gone.

### ISSUE THREAD

**Issue by YYHKING** [chat2db/Chat2DB#1135]
### Chat2DB Version

3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/10542719/7be14a3b-719b-453b-9a6b-555ad2b291b8)
After completing the modification, I clicked the save button and it was prompted that the modification was successful. However, after execution, I found that the result had not changed. When I opened the stored procedure, I found that the changes I had just made were not saved.
The database is sqlserver2016

**Comment by miahemu** [comment]
你好，点击procedures鼠标右键刷新按钮试试：
![image](https://github.com/chat2db/Chat2DB/assets/157001655/70e0e1dc-715f-4dc6-86a7-ddfaeb01244c)

**Comment by miahemu** [comment]
<img width="1246" alt="image" src="https://github.com/chat2db/Chat2DB/assets/157001655/60db3ca0-ecd8-48f8-9bd7-f554603ee0d0">
try new version
