### ISSUE TITLE
Bug: If I want to copy part of the query results, hold down shift and click on the headers of the first and last rows. As a result, random rows are selected.

### ISSUE THREAD

**Issue by YYHKING** [chat2db/Chat2DB#1136]
### Chat2DB Version

3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/10542719/0cf7ad73-c6ea-48d7-b2b5-6d9a7426509f)
The test library is sqlserver2016

**Comment by miahemu** [comment]
I just tried it, the new version doesn’t have this problem
