### ISSUE TITLE
Bug: Syntax parsing error

### ISSUE THREAD

**Issue by QingXiao111** [chat2db/Chat2DB#1138]
### Chat2DB Version

3.1.19

### Describe the bug

While adding data, an error occurred. (Most likely because of wrong quotation marks)
UPDATE shenhetiaojian SET dm_term = 'gs_Company_Mark = '工业'
and nvl (business_Income, 0) >= 20000
and substring(org_code, 1, 2) in (
  'BJ',
  'TJ',
  'HB',
  'SX',
  'NM',
  'LN',
  'JL',
  'LJ',
  'SH',
  'JS',
  'EJ',
  'AH',
  'FJ',
  'JX',
  'SD',
  'HE',
  'HU',
  'HN',
  'GD',
  'GX',
  'HA',
  'SC',
  'GU',
  'YN',
  'SA',
  'GS',
  'QH',
  'NX',
  'XJ',
  'XH',
  'AB',
  'KZ',
  'UH',
  'BT',
  'LA',
  'VS',
  'CQ',
  'CH',
  'MF',
  'WG',
  'DS',
  'NJ',
  'XY',
  'EN',
  'OS',
  'YS',
  'FN',
  'PH',
  'ZG',
  'GL',
  'QB',
  'AQ',
  'HL',
  'RN',
  'BN',
  'IH',
  'SG',
  'CX',
  'JU',
  'TG',
  'DX'
)' WHERE uuid ='CD2339A532FB4A0FAB2CA7AE32C77614';

**Comment by openai0229** [comment]
你好，可以提供一下数据库类型，表结构吗？
