### ISSUE TITLE
关闭网络，或者使用局域网时连接不上mysql数据库报java.net.unknownhostexception:oss.sqlgpt.cn

### ISSUE THREAD

**Issue by xiaog929** [chat2db/Chat2DB#1141]
### Chat2DB Version

latest

### Describe the bug

当没网络时连接不上mysql数据库该怎么办呢？报[java.net](ava.net.unknownhostexception:oss.sqlgpt.cn)
![1bc38e1738517fafe97d5fc9d49482d](https://github.com/chat2db/Chat2DB/assets/75246377/6ebf199f-1787-43b7-a1b5-52ace3e94580)

**Comment by SwallowGG** [comment]
不能联网的情况需要自己手动上传驱动
