### ISSUE TITLE
Bug: mysql新增的表在左侧列表栏找不到

### ISSUE THREAD

**Issue by ITfisher** [chat2db/Chat2DB#1144]
### Chat2DB Version

v3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/18683222/0cea8587-1299-4286-b4e1-d568fd14d525)
左侧列表栏找不到新增的表，点击刷新也无法加载出。
但是console直接sql语句查询是能查询到该表的数据。
通过删除数据库连接，然后重新添加数据库连接之后，可以查询到该表

**Comment by QingXiao111** [comment]
tables右键刷新试试

**Comment by ITfisher** [comment]
> tables右键刷新试试

table右键的刷新试了一下可以的，不过这个交互有点怪，左上角的那个刷新为啥反而不生效。
以及那个过滤的搜索栏，必须是展开的数据才能筛选到
