### ISSUE TITLE
Bug: DM数据库部分schema下的表查看异常

### ISSUE THREAD

**Issue by MSK-USER** [chat2db/Chat2DB#1149]
### Chat2DB Version

3.1.17

### Describe the bug

链接dm数据的，查看schema下的表数据，提示失败，datagrip可以正常查看。

DataGrip正常截图：
<img width="736" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/83965deb-effd-4bfb-9c0f-e7843ee0ac4d">

Chat2DB错误截图：
<img width="953" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/7069ec95-1024-4c81-a36d-cd5b103e7327">

错误报告：
{"getApplicationMessage":{"env":"desktop","versions":"3.1.17","buildTime":1703689902917,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) chat2db/3.1.1 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"},"requestUrl":"http://127.0.0.1:10824/api/rdb/dml/execute_table","requestParams":"{\"sql\":\"select * from \\\"ny_aa_a_399833\\\"\",\"tableName\":\"ny_aa_a_399833\",\"pageNo\":1,\"pageSize\":200,\"total\":0,\"hasNextPage\":true,\"dataSourceId\":3,\"databaseType\":\"DM\",\"schemaName\":\"B\",\"type\":\"DM\"}","errorCode":null,"errorMessage":"第1 行附近出现错误:\n无效的表或视图名[NY_AA_A_399833]","errorDetail":null,"solutionLink":null}

**Comment by miahemu** [comment]
您好，更新到v3.1.19问题就解决了

**Comment by miahemu** [comment]
另外可以问下您那边datagrip下载的达梦数据库驱动是什么版本的吗？我这边数据编码有问题
![image](https://github.com/chat2db/Chat2DB/assets/157001655/55302597-0fea-47ca-ac39-dbac7bc22c7e)

**Comment by MSK-USER** [comment]
> 您好，更新到v3.1.19问题就解决了

你好，刚升级了一下，还是不可以。

**Comment by MSK-USER** [comment]
> 另外可以问下您那边datagrip下载的达梦数据库驱动是什么版本的吗？我这边数据编码有问题 ![image](https://private-user-images.githubusercontent.com/157001655/302073850-55302597-0fea-47ca-ac39-dbac7bc22c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTYyMzMsIm5iZiI6MTcwNzAxNTkzMywicGF0aCI6Ii8xNTcwMDE2NTUvMzAyMDczODUwLTU1MzAyNTk3LTBmZWEtNDdjYS1hYzM5LWRiYWM3YmMyMmM3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMzA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2U2OGE5MTYxNmRkZjZmY2VlYzAyNWFjYzkxOGQwMjdmNDE5ZmNkZGRlNWM2YjVlMWJiYmNkMDI0YjZmMGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2x9aTWUFAW2Z3Pd3VkQB4RiiuypnyTn2g7oHAG0XFPE)

我分享给你 

DmJdbcDriver18.jar
https://www.alipan.com/s/PrwKEKh26R5
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by SaddyFire** [comment]
> > 您好，更新到v3.1.19问题就解决了
> 
> 你好，刚升级了一下，还是不可以。

我也是 3.1.17 的 chat2db, 在驱动中点击 Upload driver, 然后找达梦管理工具自带的驱动上传一下就好了
![image](https://github.com/chat2db/Chat2DB/assets/77627220/0945df26-525b-4341-92f4-efab71dd4360)

**Comment by MSK-USER** [comment]
> 另外可以问下您那边datagrip下载的达梦数据库驱动是什么版本的吗？我这边数据编码有问题 ![image](https://private-user-images.githubusercontent.com/157001655/302073850-55302597-0fea-47ca-ac39-dbac7bc22c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDIyMDMsIm5iZiI6MTcwNzQwMTkwMywicGF0aCI6Ii8xNTcwMDE2NTUvMzAyMDczODUwLTU1MzAyNTk3LTBmZWEtNDdjYS1hYzM5LWRiYWM3YmMyMmM3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxNDE4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmY1YzEwNTg5Y2QwYzJiOTg0ZDdkOTQxODhmMmQwYjJjZWI5NWNhYjJlYjZiMjNjNTkyNTc1MjBiZWM3NTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iyd68zchlHwaJzK4Z4-pVJz6I9OCde5an6vROOYmssc)

你好，找到bug原因了，chat2db的查表没有添加schema，从SYSDBA去找表不存在，实际表在B这个schema里面，添加上schema就可以查到了。
<img width="536" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/7217f3e9-7f9a-46ea-b492-a9e4cebcc5df">
