### ISSUE TITLE
Bug: 下方表格更新bug，导致全表更新

### ISSUE THREAD

**Issue by aohun** [chat2db/Chat2DB#1151]
### Chat2DB Version

3.1.18

### Describe the bug

SELECT USER_ID FROM SYS_USER WHERE ID='111';
用这语句查询之后，在下方表格更新USER_ID ，点提交，后台执行的语句是UPDATE SYS_USER SET USER_ID='XX' WHERE USER_ID IS NULL;把全表更新了

**Comment by miahemu** [comment]
你好，我刚刚试了一下。当ID为‘111’的USER_ID全为空时会更新全表，这时候系统就会表明在执行更新操作时，更新了多行数据而不是预期的一行数据。这通常是由于缺少适当的唯一键（Unique Key）导致的，并且在更新操作中没有限制更新范围，所以执行完毕之后全表更新。
![1](https://github.com/chat2db/Chat2DB/assets/157001655/d8773110-5396-4e18-a7ca-6385d1389dbb)
![2](https://github.com/chat2db/Chat2DB/assets/157001655/ef9d5409-620a-4229-a4ea-dd0a15ac1d0b)
![3](https://github.com/chat2db/Chat2DB/assets/157001655/0f21b665-ff18-4202-9cc4-804883ff7f1f)
![4](https://github.com/chat2db/Chat2DB/assets/157001655/283b0fef-4df6-4e14-a1a7-a15aa29eea57)
