### ISSUE TITLE
Bug: 在windows上安装3.1.19后，没有找到redis

### ISSUE THREAD

**Issue by ybina** [chat2db/Chat2DB#1156]
### Chat2DB Version

3.1.19

### Describe the bug

没有找到redis
![image](https://github.com/chat2db/Chat2DB/assets/93298258/06f5705b-10dc-4503-b62c-769e853f3720)

**Comment by tmlx1990** [comment]
您好，目前暂时不支持redis。

**Comment by ybina** [comment]
@tmlx1990 那为啥readme中有展示redis,也说部分支持redis了

**Comment by miahemu** [comment]
您好，之前老版本支持过redis，上线之后因为有一些没有解决的bug，不能完美的展示给用户，用户体验不好，所以新版本又下线了，redis后续期待吧！
