### ISSUE TITLE
Bug: Comment disappears

### ISSUE THREAD

**Issue by QingXiao111** [chat2db/Chat2DB#1157]
### Chat2DB Version

3.1.17

### Describe the bug

Comments are automatically ignored when executing sql
![1f9b01c2b6063de7964fd65a32e80a7](https://github.com/chat2db/Chat2DB/assets/92871355/01fa40b4-abf2-47a5-a2a7-e2352eb990fc)

**Comment by tmlx1990** [comment]
您好，能提供下使用的数据库版本吗？还有能否提供下建表语句？
