### ISSUE TITLE
Bug: Table lookup failed in some databases, and schema information was not added to the query conditions (only DM has been tested so far)

### ISSUE THREAD

**Issue by MSK-USER** [chat2db/Chat2DB#1162]
### Chat2DB Version

3.1.17

### Describe the bug

I mentioned two issues before, and today I accidentally discovered the cause of the error. Taking DM as an example, the query statement did not add a specific schema, resulting in the table not being found. By default, it went to SYSDBA to find the table information, but the actual table was in the schema B. , the table can be found correctly by adding the schema information. The sql of the error log does not add the schema.
<img width="536" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/61ecc8e9-bc9c-4875-94c4-0351fcee1823">

**Comment by MSK-USER** [comment]
<img width="670" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/73daed9b-2761-4acc-bcdb-c1d29340632e">

这个bug是打开非默认schema的表的时候会报错。

{"getApplicationMessage":{"env":"desktop","versions":"3.1.19","buildTime":1704272050850,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) chat2db/3.1.19 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"},"requestUrl":"http://127.0.0.1:10824/api/rdb/dml/execute_table","requestParams":"{\"sql\":\"select * from \\\"ny_aa_a_399833\\\"\",\"tableName\":\"ny_aa_a_399833\",\"pageNo\":1,\"pageSize\":200,\"total\":0,\"hasNextPage\":true,\"dataSourceId\":3,\"databaseType\":\"DM\",\"schemaName\":\"B\",\"type\":\"DM\"}","errorCode":null,"errorMessage":"第1 行附近出现错误:\n无效的表或视图名[ny_aa_a_399833]","errorDetail":null,"solutionLink":null}

**Comment by MSK-USER** [comment]
<img width="330" alt="image" src="https://github.com/chat2db/Chat2DB/assets/106138487/3bcfd9e4-216a-4929-8bd5-df5f0b184c26">
datagrip打开表日志

**Comment by miahemu** [comment]
1.您好，您这边指定了哪个schema吗？达梦数据库默认的查询语句中是直接跟表名的。如果没有指定schema的话，则会在当前用户的默认 schema 中查找相应的表。
![image](https://github.com/chat2db/Chat2DB/assets/157001655/5667a33e-f3a1-45e6-b7f2-2b08cb34360d)
选择好schema后，我刚刚在3.1.17版本试了下没有问题。
![image](https://github.com/chat2db/Chat2DB/assets/157001655/880aeb7c-9da4-4304-b4d0-ca8adccfd61d)


2.还有您说的打开非默认schema的表报错打不开。经验证，是未添加schema造成的，后续我们会修复这一bug，感谢您的指出。

**Comment by MSK-USER** [comment]
> 1.您好，您这边指定了哪个schema吗？达梦数据库默认的查询语句中是直接跟表名的。如果没有指定schema的话，则会在当前用户的默认 schema 中查找相应的表。 ![image](https://private-user-images.githubusercontent.com/157001655/307998479-5667a33e-f3a1-45e6-b7f2-2b08cb34360d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTU2NDUsIm5iZiI6MTcwODk5NTM0NSwicGF0aCI6Ii8xNTcwMDE2NTUvMzA3OTk4NDc5LTU2NjdhMzNlLWYzYTEtNDVlNi1iN2YyLTJiMDhjYjM0MzYwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMDU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmYzNjg0ODFiY2EzZDVmMDkwZDI0MWI2NDY1MzRkYjliMjdhYmRjMzI1Mjk1OWU2ZWU2M2RlYjNhMWVmZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-P44w_lNU_-L_x9fewZiS6sLefVyKU3vQxOd7r9MEC8) 选择好schema后，我刚刚在3.1.17版本试了下没有问题。 ![image](https://private-user-images.githubusercontent.com/157001655/307999986-880aeb7c-9da4-4304-b4d0-ca8adccfd61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTU2NDUsIm5iZiI6MTcwODk5NTM0NSwicGF0aCI6Ii8xNTcwMDE2NTUvMzA3OTk5OTg2LTg4MGFlYjdjLTlkYTQtNDMwNC1iNGQwLWNhOGFkY2NmZDYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMDU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzNlMTg4MDBiZGU0ZmJiMDk2OTY2ODgyNWY4NzM4M2RkZjk3YzY1MzM5NjJhOTY1OTIxMWNmMGFkMzdkYjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JCVVIzkDGpVCgi6_m-tXiVKMUiAdsr2gNwUjiVjaEBQ)
> 
> 2.还有您说的打开非默认schema的表报错打不开。经验证，是未添加schema造成的，后续我们会修复这一bug，感谢您的指出。

感谢，sql那里是我重现bug用的，故意没加schema，只有打开非默认schema表出错的那个bug。

**Comment by miahemu** [comment]
好的，明白了。客气。

**Comment by tmlx1990** [comment]
> 一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。

报错的时候，右下角的schema有选择吗？
![image](https://github.com/chat2db/Chat2DB/assets/5753992/241aa0f4-05a9-4a7c-8526-5435e7b847ab)

**Comment by MSK-USER** [comment]
> > 一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。
> 
> 报错的时候，右下角的schema有选择吗？ ![image](https://private-user-images.githubusercontent.com/5753992/308012412-241aa0f4-05a9-4a7c-8526-5435e7b847ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDMxOTAsIm5iZiI6MTcwOTAwMjg5MCwicGF0aCI6Ii81NzUzOTkyLzMwODAxMjQxMi0yNDFhYTBmNC0wNWE5LTRhN2MtODUyNi01NDM1ZTdiODQ3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDMwMTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA1ZGE5ZjE0ZmFhODA0OWQxNmFkNTlhMTllM2YyNTE3MmE0NDhiNDIwOGE4ZThkMTQ2N2RiNmZmMmM3MDY4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NjkogHLYyOH3y7m_9w342Mt5w5ATPl3lZTBzPnvyPHM)

双击打开非默认schema的表的时候报错，不是在控制台输入sql查询的时候报错。

**Comment by MSK-USER** [comment]
双击打开非默认schema的表的时候报错，不是在控制台执行查询sql报的错。 ---- 回复的原邮件 ----发件人Xin ***@***.***>发送日期2024年02月27日 10:08 ***@***.***> ***@***.***>***@***.***>主题Re: [chat2db/Chat2DB] Bug: 部分数据库查表失败，查询条件未添加schema信息（目前只测试了DM） (Issue #1162)

一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。

报错的时候，右下角的schema有选择吗？
image.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965660667",
"url": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965660667",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MSK-USER** [comment]
> > 一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。
> 
> 报错的时候，右下角的schema有选择吗？ ![image](https://private-user-images.githubusercontent.com/5753992/308012412-241aa0f4-05a9-4a7c-8526-5435e7b847ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDM2MTYsIm5iZiI6MTcwOTAwMzMxNiwicGF0aCI6Ii81NzUzOTkyLzMwODAxMjQxMi0yNDFhYTBmNC0wNWE5LTRhN2MtODUyNi01NDM1ZTdiODQ3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDMwODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzZTQzOTU2NjIwYjgwN2EyNTFlMzY5OWI5YTY1ZWZiNWExODkxODczM2JhM2M5ZGJhMDIyZThkN2QxMzA5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7elcNcNY0fuaKXLpZwO5blvyId6tJvdVLY9VASe1SS0)

双击打开非默认schema的表的时候报错，不是在控制台执行查询sql报的错。

**Comment by tmlx1990** [comment]
> > > 一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。
> > 
> > 
> > 报错的时候，右下角的schema有选择吗？ ![image](https://private-user-images.githubusercontent.com/5753992/308012412-241aa0f4-05a9-4a7c-8526-5435e7b847ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDM2MTYsIm5iZiI6MTcwOTAwMzMxNiwicGF0aCI6Ii81NzUzOTkyLzMwODAxMjQxMi0yNDFhYTBmNC0wNWE5LTRhN2MtODUyNi01NDM1ZTdiODQ3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDMwODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzZTQzOTU2NjIwYjgwN2EyNTFlMzY5OWI5YTY1ZWZiNWExODkxODczM2JhM2M5ZGJhMDIyZThkN2QxMzA5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7elcNcNY0fuaKXLpZwO5blvyId6tJvdVLY9VASe1SS0)
> 
> 双击打开非默认schema的表的时候报错，不是在控制台执行查询sql报的错。

好的，我复现下试试。

**Comment by MSK-USER** [comment]
好的，感谢。 ---- 回复的原邮件 ----发件人Xin ***@***.***>发送日期2024年02月27日 11:12 ***@***.***> ***@***.***>***@***.***>主题Re: [chat2db/Chat2DB] Bug: 部分数据库查表失败，查询条件未添加schema信息（目前只测试了DM） (Issue #1162)



一直都是3.1.19版本，刚刚重装了一下，还是不可以，macos系统，arm版本。

报错的时候，右下角的schema有选择吗？ 

双击打开非默认schema的表的时候报错，不是在控制台执行查询sql报的错。

好的，我复现下试试。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965710509",
"url": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965710509",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MSK-USER** [comment]
> 好的，我复现下试试。

好的，感谢。

**Comment by tmlx1990** [comment]
> > 好的，我复现下试试。
> 
> 好的，感谢。

您好，您的schema也是这个当前用户创建的吗？我是本地用sysdba，创建了两个schema。都可以打开表。也不是默认的。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/ef432c2b-424e-48b6-94a8-e47e65b0e548)

**Comment by MSK-USER** [comment]
> 默认

我新建了一个schema也是可以打开的，但是其他的schema打不开，在datagrip上同样的链接方式都可以打开。
方便价格联系方式吗，查看一下问题原因

**Comment by MSK-USER** [comment]
> datagrip

我的datagrip同样的链接方式都可以打开，但是datagrip占用内存太大了，我更倾向于chat2db

**Comment by MSK-USER** [comment]
我新建了一个schema也是可以打开的，但是其他的schema打不开，在datagrip上同样的链接方式都可以打开。datagrip内存占用太大，我更倾向于chat2db。
方便价格联系方式吗，查看一下问题原因 ---- 回复的原邮件 ----发件人Xin ***@***.***>发送日期2024年02月27日 11:27 ***@***.***> ***@***.***>***@***.***>主题Re: [chat2db/Chat2DB] Bug: 部分数据库查表失败，查询条件未添加schema信息（目前只测试了DM） (Issue #1162)


好的，我复现下试试。

好的，感谢。

您好，您的schema也是这个当前用户创建的吗？我是本地用sysdba，创建了两个schema。都可以打开表。也不是默认的。
image.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965721720",
"url": "https://github.com/chat2db/Chat2DB/issues/1162#issuecomment-1965721720",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tmlx1990** [comment]
> > 默认
> 
> 我新建了一个schema也是可以打开的，但是其他的schema打不开，在datagrip上同样的链接方式都可以打开。 方便价格联系方式吗，查看一下问题原因

WX：yanxin613您加下我吧

**Comment by miahemu** [comment]
The new version 3.1.22 has solved the problem, try it
