### ISSUE TITLE
Bug: 官方跑路了吗，官网进不去，加群给的二维码也过期

### ISSUE THREAD

**Issue by hhdang** [chat2db/Chat2DB#1166]
### Chat2DB Version

3.1.19

### Describe the bug

官方跑路了吗，官网进不去，加群给的二维码也过期

**Comment by openai0229** [comment]
放心，官方没有跑路，稍后会处理

**Comment by SwallowGG** [comment]
Thanks for your reminder, the server problem has been resolved
