### ISSUE TITLE
Bug: When connecting to DM database to create a new table, the id primary key column cannot be set to auto-increment.

### ISSUE THREAD

**Issue by tujianjun523** [chat2db/Chat2DB#1174]
### Chat2DB Version

3.1.17

### Describe the bug

When connecting to Dameng database to create a new table, the id primary key column cannot be set to auto-increment.
![image](https://github.com/chat2db/Chat2DB/assets/55422303/4e4fdaea-abcd-448f-8123-f3b3de5c2d09)

**Comment by openai0229** [comment]
你好，选中这个列之后还是没有吗？
![image](https://github.com/chat2db/Chat2DB/assets/136558319/d1a2817c-5bdf-4f2d-8870-d30073ef55d0)
