### ISSUE TITLE
Bug: 展示所有表的注释列全是空的

### ISSUE THREAD

**Issue by lifei1245** [chat2db/Chat2DB#1186]
### Chat2DB Version

3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/22293539/a771d7b7-7773-406a-a8ab-a6529aaf818f)
以下是navicat展示的结果
![image](https://github.com/chat2db/Chat2DB/assets/22293539/b305c1cc-08b8-4d75-b8b8-d7f2c97a175b)

**Comment by tmlx1990** [comment]
您好，请问是什么数据库?

**Comment by lifei1245** [comment]
@tmlx1990  mysql的

**Comment by tmlx1990** [comment]
> @tmlx1990 mysql的

好的，我看下。解决了告诉您。

**Comment by lifei1245** [comment]
@tmlx1990  好的,辛苦了

**Comment by tmlx1990** [comment]
> @tmlx1990 好的,辛苦了

已经修复了，等合并后发版吧。
