### ISSUE TITLE
Bug: When MySQL edits the table and saves it, the SQL preview will automatically add a "," after the statement, causing the execution to fail.

### ISSUE THREAD

**Issue by yetao-git** [chat2db/Chat2DB#1198]
### Chat2DB Version

3.1.17

### Describe the bug

MySQL 编辑表保存时，SQL预览中会自动在语句后加一个“，”导致执行失败

![1709629261274](https://github.com/chat2db/Chat2DB/assets/52268477/4c6e7f62-3028-4fbf-b045-d053e70e6a2b)

**Comment by tmlx1990** [comment]
这个问题您升级到3.1.19试下。应该已经修复过了。
