### ISSUE TITLE
Bug: after refreshing the column list, the deleted fields still exist

### ISSUE THREAD

**Issue by e-mhui** [chat2db/Chat2DB#1204]
### Chat2DB Version

v3.1.11

### Describe the bug

After refreshing the column list, the deleted fields still exist. 
The `ext_config` field has been deleted, but still exists after refresh.
<img width="262" alt="image" src="https://github.com/chat2db/Chat2DB/assets/111486498/0b5bcb17-ff1c-4896-8f33-76293ff34e57">

**Comment by openai0229** [comment]
You can try upgrading to 3.1.19 version
