### ISSUE TITLE
Bug: 前端跑不起来

### ISSUE THREAD

**Issue by hugCode-Fight** [chat2db/Chat2DB#121]
### Chat2DB Version

2.0.0

### Describe the bug

前端执行yarn ;  npm run start后界面就一值在转圈,只有设置两个字,点击设置后,console就抛出一堆错误
<img width="1228" alt="微信截图_20230702222423" src="https://github.com/chat2db/Chat2DB/assets/59286006/1f1e4fcc-e6f1-44f2-819d-ad0dce3858d0">
填写完apikey点击应用没反应

**Comment by shanhexi** [comment]
后端服务有起吗
