### ISSUE TITLE
Bug: 表字段删除未及时更新表字段

### ISSUE THREAD

**Issue by ZQZQOvO** [chat2db/Chat2DB#1211]
### Chat2DB Version

3.1.17

### Describe the bug

sqlserver删除表dept中字段column1，所有东西都刷新了这个字段还是显示出来，其实已经被删除了
![246cfa20631bcb499f9eace6f5deda0b](https://github.com/chat2db/Chat2DB/assets/71554000/e46e46dd-f8f6-4749-99b3-0ef9575a3281)

**Comment by openai0229** [comment]
Are you saying that you also refreshed the columns?

**Comment by ZQZQOvO** [comment]
都刷新了

**Comment by openai0229** [comment]
There is no problem with version 3.1.19. You can try upgrading to a higher version

**Comment by ZQZQOvO** [comment]
好的 谢谢
