### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by killuaon** [chat2db/Chat2DB#122]
### Chat2DB Version

2.0.0

### Describe the bug

按照官网的介绍，启动了前端进程和后端jar包，启动了网页端。也能正常访问和连接数据库。

手动写了一条计数sql，select count(1) from xxxx。 看chrome开发者区域，后端接口里有返回数字，但是前端有报错。貌似是数据类型有问题？需要数组传入了object?辛苦帮忙看看

<img width="1425" alt="企业微信截图_16883204952446" src="https://github.com/chat2db/Chat2DB/assets/28692444/39feb70e-b281-400c-a9c7-df51e1acf53a">

**Comment by MrHeroJack** [comment]
查count加AS 试试

**Comment by killuaon** [comment]
> 查count加AS 试试

还是白屏哈

**Comment by chenxian01** [comment]
Cannot reproduce  in the latest version. Please try the latest version.
