### ISSUE TITLE
优化: connection 沒有redis的選項

### ISSUE THREAD

**Issue by bensonyang0217** [chat2db/Chat2DB#1225]
如題請教一下，我下載了3.17及3.19的版本，為什麼裡面沒有redis選項可以選擇？
<img width="935" alt="截圖 2024-03-14 下午4 52 51" src="https://github.com/chat2db/Chat2DB/assets/82284026/35fba86f-18d9-4598-991d-faeda7e57531">

**Comment by lizhongyue248** [comment]
同问

**Comment by miahemu** [comment]
reids将在后续版本推出，敬请期待
