### ISSUE TITLE
Bug: getJDBCDriver error: null

### ISSUE THREAD

**Issue by lx3xun** [chat2db/Chat2DB#123]
### Chat2DB Version

2.0.0

### Describe the bug

MacOS ARM64 (Apple芯片) 连接mysql8.0提示 getJDBCDriver error: null， 无法连接

**Comment by DJasonlin** [comment]
same error

**Comment by RainySecret** [comment]
same fault

**Comment by fundgao** [comment]
一样报错，也下载了mysql8.0的驱动

**Comment by chat2db-yx** [comment]
2.0.1已经修复
