### ISSUE TITLE
Bug: mysql已有表中添加字段，生成的sql最后，没有去掉，

### ISSUE THREAD

**Issue by MrYangZC** [chat2db/Chat2DB#1247]
### Chat2DB Version

3.3.17

### Describe the bug

mysql已有表中添加字段，生成的sql最后，没有去掉
![image](https://github.com/chat2db/Chat2DB/assets/29966789/21494ca4-5ba6-4ecc-8af2-2d17890da154)

**Comment by openai0229** [comment]
Thank you for your support. There were no issues with testing on my end. My version is 3.1.19, please try upgrading to version 3.1.19,

**Comment by MrYangZC** [comment]
是的，3.1.19是不存在这个问题的
