### ISSUE TITLE
Suggestion: The total number of rows in the query with distinct is not accurate

### ISSUE THREAD

**Issue by saajireign** [chat2db/Chat2DB#1254]
Version:Chat2DB v3.1.17
Phenomenon:
<img width="310" alt="image" src="https://github.com/chat2db/Chat2DB/assets/16491916/21b9fbd5-6fa9-400c-92ae-ef1a1369487b">
suggestion:
As shown in the figure, it seems that the total calculation method of chat2db is to wrap the statements between select and from in the original query with count() and then retrieve the result. However, if there is a distinct keyword in the original query statement, if The original query found empty records, but count(distinct...) cannot count empty records, resulting in inaccurate results. It is recommended to wrap the count outside without changing the counting method of the original SQL statement.

**Comment by openai0229** [comment]
Thank you for your support. My test version is 3.1.19, and I have not found any problems during testing. If you still encounter problems after upgrading to this version, please provide SQL query statements so that I can reproduce the problem
