### ISSUE TITLE
Bug: 数据库不存在，则点击刷新表，会报错

### ISSUE THREAD

**Issue by activepirate** [chat2db/Chat2DB#126]
### Chat2DB Version

v2.0.0

### Describe the bug

数据库不存在，则点击刷新表，会报错 "common.systemError: 系统发生异常，可在帮助中点击日志查看异常详情。如无法解决，可关注微信公众号Text2SQL咨询帮助"

**Comment by activepirate** [comment]
![1](https://github.com/chat2db/Chat2DB/assets/34710758/76b6ac7b-534f-4d11-b2e9-0416500e0bb2)

**Comment by jipengfei-jpf** [comment]
2.0.2已经修复
