### ISSUE TITLE
Bug: When accessing the web version or PC version via the web, when the mouse is parked on the tab page, a progress bar appears blocking the tab.

### ISSUE THREAD

**Issue by choudou** [chat2db/Chat2DB#1265]
### Chat2DB Version

3.1.19

### Describe the bug
Affects label selection and closing
![PixPin_2024-04-03_14-55-30](https://github.com/chat2db/Chat2DB/assets/8089031/79382170-cbeb-4a33-af03-397e5810f7cd)

**Comment by miahemu** [comment]
This problem already sloved , please try new version.
