### ISSUE TITLE
Bug: The table named ip does not appear

### ISSUE THREAD

**Issue by i18n-now** [chat2db/Chat2DB#1270]
### Chat2DB Version

3.1.19

### Describe the bug

As shown in the picture
<img width="1660" alt="image" src="https://github.com/chat2db/Chat2DB/assets/145643935/ff352906-c3e8-48e2-828a-e875024e8839">

**Comment by miahemu** [comment]
I'm OK here
<img width="1244" alt="image" src="https://github.com/chat2db/Chat2DB/assets/157001655/148c2d13-77d9-4f14-a8c7-bd50544148d7">
