### ISSUE TITLE
Suggestion: When will the new version be updated?

### ISSUE THREAD

**Issue by ZQZQOvO** [chat2db/Chat2DB#1275]
When will the new version of win system be updated?

**Comment by tmlx1990** [comment]
> 新版win系统什么时候更新？

The new version 3.1.22 has been released.
https://github.com/chat2db/Chat2DB/releases/tag/v3.1.22

**Comment by ZQZQOvO** [comment]
谢谢，一直在等你们官网的更新，在那里下载还不是新版本的
