### ISSUE TITLE
Bug: sqlserver连接不上

### ISSUE THREAD

**Issue by ZQZQOvO** [chat2db/Chat2DB#1279]
### Chat2DB Version

3.1.22

### Describe the bug

![Uploading d1c8b98b1dd973d6e25ed4d50a71f5d0.png…]()

**Comment by ZQZQOvO** [comment]
![d1c8b98b1dd973d6e25ed4d50a71f5d0](https://github.com/chat2db/Chat2DB/assets/71554000/1a4aff21-6a56-40bb-8764-6dcc876402cd)

**Comment by ZQZQOvO** [comment]
jdk有两个环境一个jdk8一个jdk11，改过java.security文件的tls配置但是还是连不上

**Comment by ZQZQOvO** [comment]
sqlserver版本2012 - 11.0.2100.60

**Comment by robinji0** [comment]
Please use java version equal or bigger than openjdk 17

**Comment by ZQZQOvO** [comment]
你指的是驱动吗

**Comment by ZQZQOvO** [comment]
那我的java版本如果使用8或者11上述情况用不了吗 低版本才可以吗？

**Comment by ZQZQOvO** [comment]
亲测3.1.19版本可以连接
