### ISSUE TITLE
Bug: 第一张表置顶，可以一直置顶，显示重复的表

### ISSUE THREAD

**Issue by activepirate** [chat2db/Chat2DB#128]
### Chat2DB Version

v2.0.0

### Describe the bug

第一张表置顶，可以一直置顶

**Comment by activepirate** [comment]
![2](https://github.com/chat2db/Chat2DB/assets/34710758/5bf6aef9-c359-4c4a-97a0-f80dc71ede35)

**Comment by chenxian01** [comment]
Fixed in the latest version.
