### ISSUE TITLE
Bug: Query directly in Chinese. For example, if you query the SMS record table for records whose transaction date is that day, you cannot find the table annotated as SMS record table.

### ISSUE THREAD

**Issue by wang3680** [chat2db/Chat2DB#1285]
### Chat2DB Version

3.1.22

### Describe the bug

Tables with the same annotations cannot be queried in Chinese

**Comment by robinji0** [comment]
Please try the Pro version.

**Comment by wang3680** [comment]
用的就是pro版本3.1.22

**Comment by miahemu** [comment]
> 用的就是pro版本3.1.22

this：https://chat2db.ai/
