### ISSUE TITLE
Bug: mysql, no data is displayed for any query

### ISSUE THREAD

**Issue by kingsonchan** [chat2db/Chat2DB#1286]
### Chat2DB Version

1.0.1

### Describe the bug

Install the latest version and connect to mysql. All tables can be displayed, but no data is displayed in any query. There are error columns and no content. I have tried both mysql driver 8.0 and 5.1

![image](https://github.com/chat2db/Chat2DB/assets/4169744/fc4f128e-04b5-41a8-9206-13bcd05867ed)

**Comment by robinji0** [comment]
how do you execute the query?

**Comment by tmlx1990** [comment]
Hello, your problem has not been reproduced. Can you provide detailed information? What does the database in the upper right corner look like?
![image](https://github.com/chat2db/Chat2DB/assets/5753992/a332b986-7bc7-4abe-96c7-cf4b5d8c7571)
