### ISSUE TITLE
Bug: View all tables function cannot be used

### ISSUE THREAD

**Issue by solitude-mix** [chat2db/Chat2DB#1288]
### Chat2DB Version

Chat2DB1.0.0

### Describe the bug

There are 1003 tables in OceanBase database. The function of viewing all tables will keep waiting in circles and cannot be viewed. SQL statements can run normally.
![微信图片_20240409175638](https://github.com/chat2db/Chat2DB/assets/71695400/88d3f8fc-12c1-4063-b4c5-5fb45b0d4c60)

**Comment by miahemu** [comment]
please try new version
