### ISSUE TITLE
Bug: Pro版本卡在启动页面

### ISSUE THREAD

**Issue by mahaonanStart** [chat2db/Chat2DB#1289]
### Chat2DB Version

Chat2DB v1.0.0

### Describe the bug

Apple M1 pro，Macos 14.2.1 (23C71)，启动后出来logo，一直卡在启动页面，也不知道啥情况

**Comment by shanhexi** [comment]
Close it and try again?

**Comment by mahaonanStart** [comment]
> Close it and try again?

卸载了重新装可以了。

**Comment by mahaonanStart** [comment]
> Close it and try again?

pro没有M1版本的吗

**Comment by shanhexi** [comment]
<img width="1335" alt="image" src="https://github.com/chat2db/Chat2DB/assets/86969353/88fae7d7-19ff-45cb-b4a8-3111fb8bd748">
I read the name of your installation package.

**Comment by mahaonanStart** [comment]
又出现了类似的问题，已经付费支持了，这还怎么用嘛。。感觉是因为上一次没有正常启动导致的。重装也没用了。
<img width="1555" alt="image" src="https://github.com/chat2db/Chat2DB/assets/44892851/b7eedd04-cac7-41ad-a904-b3d42e5153cf">
