### ISSUE TITLE
Bug: When the avatar is not set, the username in the lower left corner of the user's lower left corner is also light-colored on a light-colored background, making it difficult to see clearly.

### ISSUE THREAD

**Issue by interchen** [chat2db/Chat2DB#1305]
### Chat2DB Version

Caht2DB pro 1.0.3

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/2597576/b3eee3cd-2de2-4702-b917-717b0e11d269)

**Comment by miahemu** [comment]
The new version has solved this problem
