### ISSUE TITLE
Bug: Ubuntu下使用jar包启动，会卡在下载jdbc-lib/hive-jdbc-3.1.2-standalone.jar后面的一步

### ISSUE THREAD

**Issue by junwei-liu** [chat2db/Chat2DB#131]
### Chat2DB Version

2.0.0

### Describe the bug

ubuntu18.04启动的时候会卡在：File downloaded: /home/caden/.chat2db/jdbc-lib/hive-jdbc-3.1.2-standalone.jar

**Comment by chat2db-yx** [comment]
这代表下载启动成功了，

**Comment by junwei-liu** [comment]
> 

那该怎么访问呢？下载启动成功不是一个GUI界面吗？通过网页访问吗？
