### ISSUE TITLE
The docker image is synchronized with the latest official features

### ISSUE THREAD

**Issue by loli0123456789** [chat2db/Chat2DB#1315]
I initially used the docker image to deploy Chat2DB. Later, I went to the official website to download the client, and at the same time visited the official website web side. It turns out that the docker image is not the latest feature.
Will this area be updated with new docker images?
In addition, I found that the latest client and official website no longer have the function of configuring large models. In the future, there is no need for large models and the Chat2Db-GLM model can be used directly?

**Comment by tmlx1990** [comment]
> 我一开始使用的docker镜像部署Chat2DB，后来去官网下载了客户端、同时访问了下官网Web端，原来docker镜像不是最新功能。 请问这块是否会更新新的docker镜像？ 另外，我发现最新的客户端、官网Web端已经没有了配置大模型的功能，后续是不需要大模型，直接使用Chat2Db-GLM这个模型吗？

您好，刚看了下社区版docker镜像是有正常同步的。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/7844cf82-5bc8-45d9-9e77-8615db55bc73)

如果是pro版他是内部集成了Chat2DB-GLM，是不需要配置的。社区版需要自己配置大模型。

**Comment by loli0123456789** [comment]
> > 我一开始使用的docker镜像部署Chat2DB，后来去官网下载了客户端、同时访问了下官网Web端，原来docker镜像不是最新功能。 请问这块是否会更新新的docker镜像？ 另外，我发现最新的客户端、官网Web端已经没有了配置大模型的功能，后续是不需要大模型，直接使用Chat2Db-GLM这个模型吗？
> 
> 您好，刚看了下社区版docker镜像是有正常同步的。 ![image](https://private-user-images.githubusercontent.com/5753992/322674338-7844cf82-5bc8-45d9-9e77-8615db55bc73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzg2NjYsIm5iZiI6MTcxMzMzODM2NiwicGF0aCI6Ii81NzUzOTkyLzMyMjY3NDMzOC03ODQ0Y2Y4Mi01YmM4LTQ1ZDktOWU3Ny04NjE1ZGI1NWJjNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDcxOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JjN2I1OTg2ZDU4ZTY2NjZiNGRhZjU2OGExOWY1MzU3YmY2YTEwNDY0NmM3Mjg3ZGNlMmEwNjQyZmRmYWVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LW9Bi1zFExJkN8ALW23xcKh-Ff53dAUr2b6SPg5ZZDI)
> 
> 如果是pro版他是内部集成了Chat2DB-GLM，是不需要配置的。社区版需要自己配置大模型。

你可能没明白我的准确意思，我意思现在官网web版、客户端版界面、操作和docker最新镜像版本的界面、操作都不一样，当然是官网web版客户端版界面、操作更新、更好用。
之所以docker镜像版虽然是最新版（3.22）但属于社区版，所以和官网的不一样，是这样吗？
如果是这样，docker版的也凑合用，不过使用体验、NL2SQL效果是差一截的。
我本来是用了docker镜像版本发现问题，准备提issues的，但是发现官网上的没这个问题，而且功能更新，所以才有了这个疑问。

**Comment by tmlx1990** [comment]
> > > 我一开始使用的docker镜像部署Chat2DB，后来去官网下载了客户端、同时访问了下官网Web端，原来docker镜像不是最新功能。 请问这块是否会更新新的docker镜像？ 另外，我发现最新的客户端、官网Web端已经没有了配置大模型的功能，后续是不需要大模型，直接使用Chat2Db-GLM这个模型吗？
> > 
> > 
> > 您好，刚看了下社区版docker镜像是有正常同步的。 ![image](https://private-user-images.githubusercontent.com/5753992/322674338-7844cf82-5bc8-45d9-9e77-8615db55bc73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzg2NjYsIm5iZiI6MTcxMzMzODM2NiwicGF0aCI6Ii81NzUzOTkyLzMyMjY3NDMzOC03ODQ0Y2Y4Mi01YmM4LTQ1ZDktOWU3Ny04NjE1ZGI1NWJjNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDcxOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JjN2I1OTg2ZDU4ZTY2NjZiNGRhZjU2OGExOWY1MzU3YmY2YTEwNDY0NmM3Mjg3ZGNlMmEwNjQyZmRmYWVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LW9Bi1zFExJkN8ALW23xcKh-Ff53dAUr2b6SPg5ZZDI)
> > 如果是pro版他是内部集成了Chat2DB-GLM，是不需要配置的。社区版需要自己配置大模型。
> 
> 你可能没明白我的准确意思，我意思现在官网web版、客户端版界面、操作和docker最新镜像版本的界面、操作都不一样，当然是官网web版客户端版界面、操作更新、更好用。 之所以docker镜像版虽然是最新版（3.22）但属于社区版，所以和官网的不一样，是这样吗？ 如果是这样，docker版的也凑合用，不过使用体验、NL2SQL效果是差一截的。 我本来是用了docker镜像版本发现问题，准备提issues的，但是发现官网上的没这个问题，而且功能更新，所以才有了这个疑问。

官网的是pro版。和社区版是两个不一样的版本。pro版是直接安装的，官网可以下载。社区版是提供docker和源码的。
