### ISSUE TITLE
Bug: Connection refused

### ISSUE THREAD

**Issue by Fernwehx** [chat2db/Chat2DB#1320]
### Chat2DB Version

1.0

### Describe the bug

Connection refused，The webpage mysql cannot be connected locally

**Comment by JerryFan626** [comment]
方便发一下链接的截图吗？
还可以试一下客户端能连上吗？

**Comment by Fernwehx** [comment]
![Uploading Snipaste_2024-04-17_11-47-43.png…]()

**Comment by Fernwehx** [comment]
> 方便发一下链接的截图吗？ 还可以试一下客户端能连上吗？

![Uploading Snipaste_2024-04-17_11-47-43.png…]()

**Comment by Fernwehx** [comment]
> 方便发一下链接的截图吗？ 还可以试一下客户端能连上吗？

mysql的版本是：5.7.43，防火墙那些也是关闭了的

**Comment by Fernwehx** [comment]
![Snipaste_2024-04-17_11-47-43](https://github.com/chat2db/Chat2DB/assets/95280386/bcc98838-5dd5-427c-9db8-27cb44f67e76)

**Comment by djmfrontend** [comment]
解决了吗 我也遇到了这个问题 本地可以连接 用他这个连接不上

**Comment by miahemu** [comment]
> 解决了吗 我也遇到了这个问题 本地可以连接 用他这个连接不上

新版本也这样吗？我这边没有问题
