### ISSUE TITLE
Bug: The selected color in the edit box and left column is lighter

### ISSUE THREAD

**Issue by yanking99** [chat2db/Chat2DB#1322]
### Chat2DB Version

1.0

### Describe the bug

I see that the main color selected for the product is light green. I think it can be a little darker, or I don’t know whether it supports user customization, or it can give users several colors to choose from like a theme. I don’t know how complicated the implementation is.
![5f72618a4c4d423e48b5b2b1d121233](https://github.com/chat2db/Chat2DB/assets/43413975/769deaf2-bd16-49bd-a128-d18905169b64)

**Comment by tmlx1990** [comment]
设置里的这个您试下。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/acf4865d-9549-482f-a752-c289b334eccc)
![image](https://github.com/chat2db/Chat2DB/assets/5753992/71e286ee-a479-4a66-a9bd-8ab5bb34c9de)
