### ISSUE TITLE
建议: 是否可以支持配置数据源从git仓库获取

### ISSUE THREAD

**Issue by DUWENINK** [chat2db/Chat2DB#1329]
我拥有很多台电脑和很多台数据,当我在不同的电脑上工作的时候,配置数据源将会很麻烦,是否支持和我的私有git集成并且版本控制

**Comment by Chat2DB-Pro** [comment]
可以使用我们的Pro版本

**Comment by DUWENINK** [comment]
我用的就是pro版本的,你们只有简单的从navicat和dbeaver的导入 没有git版本控制

**Comment by DUWENINK** [comment]
你们什么情况 我买的pro版本 更新一下就没了?

**Comment by DUWENINK** [comment]
付款记录都在
