### ISSUE TITLE
Bug: Mysql’s tinyint type field only displays true and false

### ISSUE THREAD

**Issue by renchao1990** [chat2db/Chat2DB#1334]
### Chat2DB Version

Chat2DB 3.1.22

### Describe the bug

Mysql database, the value of the TINYINT(1) type field only displays true or false in the client. In fact, the value range of this field 1-9 has different meanings, so only displaying true or false will cause misunderstanding.

**Comment by miahemu** [comment]
Hi，Can you provide some screenshots?

**Comment by lhdhr5828** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/24935803/59e24423-6287-4744-9f90-afc598773672)
![image](https://github.com/chat2db/Chat2DB/assets/24935803/a379cb26-6a35-4f26-b845-d6b0dde82059)

**Comment by miahemu** [comment]
This issue seems related to #1356 .
