### ISSUE TITLE
Bug: The execution record on the right shows that the execution is completed, but the list is not yet displayed.

### ISSUE THREAD

**Issue by xiacc-cn** [chat2db/Chat2DB#1338]
### Chat2DB Version

1.0.7

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/82486481/f07fb3de-91a5-4758-b8f3-06abdca1a762)
![image](https://github.com/chat2db/Chat2DB/assets/82486481/fb565db3-efc2-4b7e-a2ca-bcb924ab8f99)
Attached table structure

**Comment by miahemu** [comment]
try refresh
