### ISSUE TITLE
Bug: (conn=399193) No database selected

### ISSUE THREAD

**Issue by Yunweifor** [chat2db/Chat2DB#134]
### Chat2DB Version

v2.0.0 build20230702163123

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/102571239/e3769c07-6cc4-4964-8619-27806e7d2f53)
执行的时候报错，明明已经选择了对应的库。

**Comment by jipengfei-jpf** [comment]
2.0.2已经修复
