### ISSUE TITLE
Bug: DM selection mode does not take effect

### ISSUE THREAD

**Issue by wwt164888** [chat2db/Chat2DB#1343]
### Chat2DB Version

1.0.7

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/62713172/0fa30728-be4c-4451-b193-30aef2fe81b3)

**Comment by miahemu** [comment]
try new version
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/ea71c229-ced3-4cec-8ba3-52e677da7f16">
