### ISSUE TITLE
Suggestions: new features

### ISSUE THREAD

**Issue by hzhanggoodbuilder** [chat2db/Chat2DB#1348]
1: The result set can be selected
2: Import and export
3: Configuration databases can be imported and exported from each other

**Comment by miahemu** [comment]
try new version！
<img width="387" alt="image" src="https://github.com/user-attachments/assets/22f76e23-686c-4dfe-9847-956a61dcb676">
<img width="550" alt="image" src="https://github.com/user-attachments/assets/1fa18510-7469-4eb2-aee3-a5022963f4e2">
