### ISSUE TITLE
优化: 产品功能体验差强人意

### ISSUE THREAD

**Issue by mylvghb** [chat2db/Chat2DB#135]
1. 在编辑 Sql 的时候，无法智能感知一个表的列。
2. 无法查看模式/架构中的其它信息，比如：存储过程、触发器、函数等。
3. 创建一个连接，默认没有选择任何架构，能否自动选择默认架构。
4. SQL 语法高亮，无法突出显示表名、字段等。

**Comment by jipengfei-jpf** [comment]
这些会在下个版本去迭代

**Comment by mylvghb** [comment]
> 这些会在下个版本去迭代

期待该产品会带来一个完美的 SQL 编辑体验，就目前来说还有很多功能还不完善。

**Comment by datafeng** [comment]
折腾半天不知道怎么用，操作交互怪怪的。。
代理设置不能关掉吗？一直提示连接错误。
最基本的创建表，编辑字段，查看表数据操作都很麻烦
能否参考下navicat的交互..

**Comment by robinji0** [comment]
marked in #404
