### ISSUE TITLE
Suggestion: Add the function of refreshing the table separately

### ISSUE THREAD

**Issue by 1614001993** [chat2db/Chat2DB#1352]
Every time the table is refreshed, the entire database needs to be refreshed. As a result, all open tables will be folded and the tables need to be reopened, which is very inefficient.

**Comment by miahemu** [comment]
Hello, you can refresh the table individually by right-clicking on tables.
![image](https://github.com/chat2db/Chat2DB/assets/157001655/dbdbff1f-fa52-4a1d-9a24-1492a73cbdc3)
