### ISSUE TITLE
Bug: Clicking to delete the table does not take effect

### ISSUE THREAD

**Issue by 1614001993** [chat2db/Chat2DB#1353]
### Chat2DB Version

1.0.7

### Describe the bug

The table cannot be deleted from the menu. Clicking to delete the table does not take effect.
![chat2dbbug反馈](https://github.com/chat2db/Chat2DB/assets/95328957/6b75d613-af69-4ae9-83cc-3ea2ce4de9dc)

**Comment by miahemu** [comment]
Hello, I have not reproduced your problem. I can delete the table normally.
