### ISSUE TITLE
Bug: The varchar2 field length is displayed incorrectly in oracle11g

### ISSUE THREAD

**Issue by wangdan1979** [chat2db/Chat2DB#1361]
### Chat2DB Version

Chat2DB3.1.17

### Describe the bug

When using oracle11g to edit an existing table, it is found that the varchar2 field length is incorrectly displayed, as shown below:
![20240504231007](https://github.com/chat2db/Chat2DB/assets/101936671/eafe97ce-358f-4e6e-afc2-86a9fad21014)

**Comment by tmlx1990** [comment]
升级到最新的3.1.22试试。
