### ISSUE TITLE
 你们什么情况 我买的pro版本 更新一下就没了?

### ISSUE THREAD

**Issue by DUWENINK** [chat2db/Chat2DB#1375]
### Chat2DB Version

latest

### Describe the bug

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

你们什么情况 我买的pro版本 更新一下就没了?

**Comment by DUWENINK** [comment]
就知道点击按钮弹出微信二维码找我要钱是吧

**Comment by tmlx1990** [comment]
?什么意思？什么叫更新一下就没了？

**Comment by DUWENINK** [comment]
> ?什么意思？什么叫更新一下就没了？

我之前开通了他们的pro  然后今天提示我更新 我重新登陆 我的本地数据库连接全没了 然后登陆账号 ,不管是 微信 邮箱 还是github登陆都显示我不是pro用户

**Comment by tmlx1990** [comment]
> > ?什么意思？什么叫更新一下就没了？
> 
> 我之前开通了他们的pro 然后今天提示我更新 我重新登陆 我的本地数据库连接全没了 然后登陆账号 ,不管是 微信 邮箱 还是github登陆都显示我不是pro用户

您看下，是不是登录页面的国家识别的不对，国内和国外是分开的用户体系。

**Comment by tmlx1990** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/5753992/bbbddf21-16c3-4510-a4c2-96896897ae67)
在左下角这里

**Comment by DUWENINK** [comment]
ok我看一下

**Comment by tmlx1990** [comment]
> ok我看一下

好的，您也可以加下官方微信群。有问题那里问可以更快得到回复。

**Comment by DUWENINK** [comment]
我常用 三处代理  中国 日本 美国,登陆方式 你们是四种 微信 ,邮箱 ,谷歌 ,github  我要匹配12种方式 这个太繁琐了 真难受啊

**Comment by DUWENINK** [comment]
问题得到解决 登错号了

**Comment by DUWENINK** [comment]
感谢感谢❀❀❀❀❀❀
