### ISSUE TITLE
Suggestion: The default username and password of the docker version are obtained from env

### ISSUE THREAD

**Issue by byl0561** [chat2db/Chat2DB#1390]
Since the current default administrator account and password are hard-coded, login authorization is useless. It is recommended to obtain it from docker env instead.

Relevant code:

package ai.chat2db.server.domain.api.enums;

import ai.chat2db.server.tools.base.enums.BaseEnum;
import lombok.Getter;

/**
 * role code
 *
 * @author Jiaju Zhuang
 */
@Getter
public enum RoleCodeEnum implements BaseEnum<String> {
    /**
     * DESKTOP
     */
    DESKTOP("DESKTOP", 1L, "_desktop_default_user_name", "_desktop_default_user_name"),

    /**
     * ADMIN
     */
    ADMIN("ADMIN", 2L, "chat2db", "chat2db"),

    /**
     * USER
     */
    USER("USER", null, null, null),

    ;
    final String description;
    final Long defaultUserId;
    final String userName;
    final String password;

    RoleCodeEnum(String description, Long defaultUserId, String userName, String password) {
        this.description = description;
        this.defaultUserId = defaultUserId;
        this.userName = userName;
        this.password = password;
    }

    @Override
    public String getCode() {
        return this.name();
    }
}

**Comment by byl0561** [comment]
可以将
ADMIN("ADMIN", 2L, "chat2db", "chat2db"),
改为
ADMIN("ADMIN", 2L, System.getenv().getOrDefault("ADMIN_NAME", "chat2db"), System.getenv().getOrDefault("ADMIN_PASS", "chat2db")),

**Comment by miahemu** [comment]
OK, accepted, thank you!

**Comment by byl0561** [comment]
Verified. Thank you.
