### ISSUE TITLE
Bug: tinyint类型默认识别为true和false

### ISSUE THREAD

**Issue by fqa2024** [chat2db/Chat2DB#1391]
### Chat2DB Version

3.1.22

### Describe the bug

![微信截图_20240517141607](https://github.com/chat2db/Chat2DB/assets/168053957/cfe1a72f-2124-4028-b3a5-0c59113bbf43)
![微信截图_20240517141640](https://github.com/chat2db/Chat2DB/assets/168053957/10673688-8be5-4fe7-a114-c3f383b18546)
我知道在许多实际应用场景中，开发人员习惯于使用 TINYINT(1) 来表示布尔值，但实际上他应该表示的是整数值，而不应该限定死为布尔值？

**Comment by miahemu** [comment]
Duplicate of #1356
