### ISSUE TITLE
Bug:  An error occurs after creating a database connection and saving it

### ISSUE THREAD

**Issue by DoveDeng57** [chat2db/Chat2DB#1397]
### Chat2DB Version

1.1.5

### Describe the bug

{"getApplicationMessage":{"env":"desktop","versions":"1.1.5","buildTime":1715795437387,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) chat2db-pro/1.1.5 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"},"errorCode":"common.paramError","errorMessage":"Required request parameter 'id' for method parameter type Long is present but converted to null","solutionLink":"https://github.com/chat2db/Chat2DB/wiki/Chat2DB","requestParams":"{\"actionType\":\"execute\",\"headers\":{\"Accept-Language\":\"zh-CN\",\"Time-Zone\":\"Asia/Shanghai\"},\"uuid\":\"a015cbd1-f4e1-4fdd-914f-50a595672074\",\"requestUrl\":\"/api/connection/datasource/create\",\"method\":\"post\",\"message\":{\"ssh\":{\"use\":false,\"hostName\":\"\",\"port\":\"22\",\"userName\":\"\",\"localPort\":\"\",\"authenticationType\":\"password\",\"password\":\"\"},\"driverConfig\":{\"jdbcDriverClass\":\"jdbc.RedisDriver\",\"jdbcDriver\":\"redis-jdbc-driver-1.5.jar\"},\"alias\":\"bjdl_redis\",\"environmentId\":2,\"storageType\":\"LOCAL\",\"host\":\"localhost\",\"port\":\"6394\",\"authenticationType\":\"2\",\"database\":\"\",\"url\":\"jdbc:redis://localhost:6394/\",\"extendInfo\":[],\"connectionEnvType\":\"DAILY\",\"type\":\"REDIS\"}}"}

**Comment by miahemu** [comment]
Hi, do you still have this problem?
