### ISSUE TITLE
Bug: The seach filter box is linked to the schema below

### ISSUE THREAD

**Issue by MrJian8** [chat2db/Chat2DB#1406]
### Chat2DB Version

1.1.5

### Describe the bug

When the Search box is filtered without expanding the schema, the filtered schema cannot be expanded, and the schema cannot be opened even if the filter condition is removed. If the schema is expanded in advance, the filtered schema can be expanded and collapsed
![image](https://github.com/chat2db/Chat2DB/assets/40019797/71daf13d-e22c-4b57-b03f-40700091bd0d)
![image](https://github.com/chat2db/Chat2DB/assets/40019797/853a755d-362d-42c8-a105-65290efdc7c3)

**Comment by miahemu** [comment]
Generally, you need to expand to get the table under the corresponding schema, and you cannot search globally from the beginning, which will affect performance.

**Comment by miahemu** [comment]
Your table will not be read without expansion.
