### ISSUE TITLE
Bug: Error when creating a new link

### ISSUE THREAD

**Issue by jins6** [chat2db/Chat2DB#1413]
### Chat2DB Version

1.2.3

### Describe the bug

{
    "getApplicationMessage": {
        "env": "desktop",
        "versions": "1.2.3",
        "buildTime": 1717172521671,
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) chat2db-pro/1.2.3 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"
    },
    "errorCode": "common.paramError",
    "errorMessage": "Required request parameter 'id' for method parameter type Long is present but converted to null",
    "solutionLink": "https://github.com/chat2db/Chat2DB/wiki/Chat2DB",
    "requestParams": ""
}
![image](https://github.com/chat2db/Chat2DB/assets/18160250/a3529ccc-e3f5-46a6-94a9-5c7837d898c4)

**Comment by miahemu** [comment]
Can you provide some specific error information and screenshots?
