### ISSUE TITLE
建议: 操作太反人类了

### ISSUE THREAD

**Issue by starnc** [chat2db/Chat2DB#143]
1、为什么不添加鼠标右键操作，用过这么多IDE都有右键，chat2db操作太难受了，还是用我的dbeaver吧
2、用java开发的桌面程序，因为控件的问题，用起来没有C#开发的winform丝滑，能不能用winform重写一遍

**Comment by Tiakon** [comment]
dbeaver ，不也是 java开发的吗

**Comment by zlichao** [comment]
> 1、为什么不添加鼠标右键操作，用过这么多IDE都有右键，chat2db操作太难受了，还是用我的dbeaver吧 2、用java开发的桌面程序，因为控件的问题，用起来没有C#开发的winform丝滑，能不能用winform重写一遍

同意你的看法，确实比较难用。但给产品一点发展时间吧。

**Comment by chenxian01** [comment]
Thanks for your attention. All the suggestions are well received, we will upgrade our product continuously.
