### ISSUE TITLE
Bug: tinyint类型填入数字时展示为false

### ISSUE THREAD

**Issue by yongfuxie** [chat2db/Chat2DB#1438]
### Chat2DB Version

2.0.1 pro 及 社区版都存在

### Describe the bug

表字段为tinyint时，填的值为0，工具展示为false，与实际不符
![image](https://github.com/chat2db/Chat2DB/assets/41229315/305e9165-0e19-4d3b-9e9e-7012f4494ad6)

在dbeaver展示
![image](https://github.com/chat2db/Chat2DB/assets/41229315/2c361942-448d-4fd2-b0da-489f00dd4ae7)

**Comment by tmlx1990** [comment]
如果是mysql需要在链接中加如下参数
tinyInt1isBit=false

**Comment by miahemu** [comment]
Duplicate of #1356
