### ISSUE TITLE
Suggestion: It is recommended to improve how to perform local debugging in the wiki or readme

### ISSUE THREAD

**Issue by Erional** [chat2db/Chat2DB#1449]
建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。

**Comment by romandata** [comment]
+10086

**Comment by miahemu** [comment]
> 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。

https://github.com/chat2db/Chat2DB.wiki.git

PR正常提交英文格式就行

**Comment by Erional** [comment]
👍

**Comment by romandata** [comment]
> > 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。
> 
> https://github.com/chat2db/Chat2DB/wiki/Chat2DB%E6%BA%90%E7%A0%81%E5%92%8CDocker%E9%83%A8%E7%BD%B2
> 
> PR正常提交英文格式就行

1、按照docker部署之后，网页还是打不开
2、会增加linux端部署的方法么？

**Comment by miahemu** [comment]
> > > 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。
> > 
> > 
> > https://github.com/chat2db/Chat2DB/wiki/Chat2DB%E6%BA%90%E7%A0%81%E5%92%8CDocker%E9%83%A8%E7%BD%B2
> > PR正常提交英文格式就行
> 
> 1、按照docker部署之后，网页还是打不开 2、会增加linux端部署的方法么？

网页打不开是没有反应吗？有没有报错信息呢？
<img width="1246" alt="image" src="https://github.com/chat2db/Chat2DB/assets/157001655/b4cc2ef3-2cc2-4d50-99b5-3324574f8ba8">

**Comment by miahemu** [comment]
> > > 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。
> > 
> > 
> > https://github.com/chat2db/Chat2DB/wiki/Chat2DB%E6%BA%90%E7%A0%81%E5%92%8CDocker%E9%83%A8%E7%BD%B2
> > PR正常提交英文格式就行
> 
> 1、按照docker部署之后，网页还是打不开 2、会增加linux端部署的方法么？

docker是跨平台的，linux端是一样的操作步骤

**Comment by romandata** [comment]
> > > > 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。
> > > 
> > > 
> > > https://github.com/chat2db/Chat2DB/wiki/Chat2DB%E6%BA%90%E7%A0%81%E5%92%8CDocker%E9%83%A8%E7%BD%B2
> > > PR正常提交英文格式就行
> > 
> > 
> > 1、按照docker部署之后，网页还是打不开 2、会增加linux端部署的方法么？
> 
> 网页打不开是没有反应吗？有没有报错信息呢？ <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/157001655/345747823-b4cc2ef3-2cc2-4d50-99b5-3324574f8ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODA1NzgsIm5iZiI6MTcyMDA4MDI3OCwicGF0aCI6Ii8xNTcwMDE2NTUvMzQ1NzQ3ODIzLWI0Y2MyZWYzLTJjYzItNGQ1MC05OWI1LTMzMjQ1NzRmOGJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwODA0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODNjYjNhMjQ5MDcyYjhjODBmOWRkNDQ4ZmNlYzcwNGMyZTA1MWZjMWE2NThhMjJhODY2ZWUzZDk1MmZlZDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CseUc_GEGUqVRbIb8dDLXIpU09T8H4lgFOtckHyLVrE">
![image](https://github.com/chat2db/Chat2DB/assets/48434127/cddc006a-5edc-4397-aa51-13aebd399fe6)
启动的错误信息，看着是字符编码的问题。我查下我的系统问题吧。

**Comment by Erional** [comment]
版本是OpenJDK 17吗？

**Comment by miahemu** [comment]
> 版本是OpenJDK 17吗？

没错

**Comment by romandata** [comment]
> 版本是OpenJDK 17吗？

是的。
![image](https://github.com/chat2db/Chat2DB/assets/48434127/46a6ee66-0c80-44e8-b9ab-511611ee1a70)

**Comment by romandata** [comment]
> > > > > 建议在wiki或readme中详细描述如何进行本地调试以及补充完善PR规则。
> > > > 
> > > > 
> > > > https://github.com/chat2db/Chat2DB/wiki/Chat2DB%E6%BA%90%E7%A0%81%E5%92%8CDocker%E9%83%A8%E7%BD%B2
> > > > PR正常提交英文格式就行
> > > 
> > > 
> > > 1、按照docker部署之后，网页还是打不开 2、会增加linux端部署的方法么？
> > 
> > 
> > 网页打不开是没有反应吗？有没有报错信息呢？ <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/157001655/345747823-b4cc2ef3-2cc2-4d50-99b5-3324574f8ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODA1NzgsIm5iZiI6MTcyMDA4MDI3OCwicGF0aCI6Ii8xNTcwMDE2NTUvMzQ1NzQ3ODIzLWI0Y2MyZWYzLTJjYzItNGQ1MC05OWI1LTMzMjQ1NzRmOGJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwODA0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODNjYjNhMjQ5MDcyYjhjODBmOWRkNDQ4ZmNlYzcwNGMyZTA1MWZjMWE2NThhMjJhODY2ZWUzZDk1MmZlZDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CseUc_GEGUqVRbIb8dDLXIpU09T8H4lgFOtckHyLVrE">
> > ![image](https://private-user-images.githubusercontent.com/48434127/345750772-cddc006a-5edc-4397-aa51-13aebd399fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODM3OTgsIm5iZiI6MTcyMDA4MzQ5OCwicGF0aCI6Ii80ODQzNDEyNy8zNDU3NTA3NzItY2RkYzAwNmEtNWVkYy00Mzk3LWFhNTEtMTNhZWJkMzk5ZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA4NTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDBmMjJjZTNjOTRlYWU2ZjQzMjgyZTVlYzJlYzJmMjJhZTFjODI4MzQyYzQ0ZDRmOTJiODEzZDQxYjlmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nj6djDpg-6okzCgnjdnil1whrun3FsxY8oSL_7b-fIY)
> > 启动的错误信息，看着是字符编码的问题。我查下我的系统问题吧。

系统字符集问题。此问题结束。谢谢~
