### ISSUE TITLE
Bug: mysql tinyint 字段 显示问题

### ISSUE THREAD

**Issue by zxqc** [chat2db/Chat2DB#1471]
### Chat2DB Version

3.2.2

### Describe the bug

tinyint 类型的 数字 展示时候 都变成 bool  ， true false 来显示了

**Comment by tmlx1990** [comment]
> ### Chat2DB Version
> 3.2.2
> 
> ### Describe the bug
> tinyint 类型的 数字 展示时候 都变成 bool ， true false 来显示了

mysql需要在链接中加如下参数
tinyInt1isBit=false
