### ISSUE TITLE
Bug：Fast Chat AI error

### ISSUE THREAD

**Issue by chalice321951** [chat2db/Chat2DB#1477]
配置了内网的ai大模型，但是用不了，显示Fast Chat AI error，这个是ai没有连接上吗，求解决，急急急急急急
![1](https://github.com/user-attachments/assets/5b7f69a1-ea38-4374-9d91-65c23a36d08e)
![2](https://github.com/user-attachments/assets/59164654-8af8-4a4d-a166-d88aa102cf56)
![3](https://github.com/user-attachments/assets/60b5a460-8e14-4b8f-a6e8-db9c10ebaeeb)

**Comment by miahemu** [comment]
具体报错日志可以发一下吗？

**Comment by chalice321951** [comment]
> 具体报错日志可以发一下吗？
感谢您的回复，我直接用的exe下载的，这个看不到日志信息哎

**Comment by miahemu** [comment]
Mac这里是能看日志的：
<img width="431" alt="image" src="https://github.com/user-attachments/assets/6d05d273-cc40-4b22-a835-a12360c8e2f3">
Win这里能打开日志：
<img width="665" alt="image" src="https://github.com/user-attachments/assets/dfc7a155-b101-44a7-8620-2c42e7a96195">

**Comment by chalice321951** [comment]
> Mac这里可以看日志的： Win这里可以打开日志： <img alt="图像" width="431" src="https://private-user-images.githubusercontent.com/157001655/351926302-6d05d273-cc40-4b22-a835-a12360c8e2f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTAwMDcsIm5iZiI6MTcyMTg4OTcwNywicGF0aCI6Ii8xNTcwMDE2NTUvMzUxOTI2MzAyLTZkMDVkMjczLWNjNDAtNGIyMi1hODM1LWExMjM2MGM4ZTJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjY4MjEwNGRjYjM2MmZiNTM0YjIxZTI1OTZmNjZlYzFmNGNiZWRhM2Y5NmUxOTQyZGNlN2I3ZDA3MDVlZWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CsF7P-AdPq_Tpqou18SmajEJA_waj5yk3j1qf1Gog5o"> <img alt="图像" width="665" src="https://private-user-images.githubusercontent.com/157001655/351926512-dfc7a155-b101-44a7-8620-2c42e7a96195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTAwMDcsIm5iZiI6MTcyMTg4OTcwNywicGF0aCI6Ii8xNTcwMDE2NTUvMzUxOTI2NTEyLWRmYzdhMTU1LWIxMDEtNDRhNy04NjIwLTJjNDJlN2E5NjE5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDJlMjBlZWRjYjRmMGZhYTAwN2E3YjBiYzE0MjFjMTc0MDJmMWNmOGE4NTNlMWQ0NDU0YmY0YWRiMWE0YWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rdy3aGAaS_uSHiIrSwr6yg-wywR1EmYfb4qiKG7Dedo">

非常感谢您的帮助，我这边已经连接成功了

**Comment by miahemu** [comment]
okok,那我把issue关了哈

**Comment by chalice321951** [comment]
> 好了，那我把问题解决了

好滴，感谢
