### ISSUE TITLE
问题：直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文

### ISSUE THREAD

**Issue by chalice321951** [chat2db/Chat2DB#1481]
直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文
![image](https://github.com/user-attachments/assets/7bc83375-15e0-434d-aedd-2a975e5e5ed7)

**Comment by tmlx1990** [comment]
> 直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文 ![image](https://private-user-images.githubusercontent.com/135098261/352399314-7bc83375-15e0-434d-aedd-2a975e5e5ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDQ1MTgsIm5iZiI6MTcyMjMwNDIxOCwicGF0aCI6Ii8xMzUwOTgyNjEvMzUyMzk5MzE0LTdiYzgzMzc1LTE1ZTAtNDM0ZC1hZWRkLTJhOTc1ZTVlNWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlmYjZlNWRjYjJjMWU1NTcwN2NhNWE1ODAzN2U3YzQwMzUyMmNjMmUwNDcwNDYwMjRlODgwZjdiZmJiZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl9czcdrqpZXR8ZGSlJdeGzHbUzIeSvj6Sqnr7CpXOI)

你退出登录重新登录试试，左下角选中国
![image](https://github.com/user-attachments/assets/8ae8c2c7-1460-4ab3-9681-ae342e5f36b0)

**Comment by chalice321951** [comment]
> > 直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文 ![image](https://private-user-images.githubusercontent.com/135098261/352399314-7bc83375-15e0-434d-aedd-2a975e5e5ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDQ1MTgsIm5iZiI6MTcyMjMwNDIxOCwicGF0aCI6Ii8xMzUwOTgyNjEvMzUyMzk5MzE0LTdiYzgzMzc1LTE1ZTAtNDM0ZC1hZWRkLTJhOTc1ZTVlNWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlmYjZlNWRjYjJjMWU1NTcwN2NhNWE1ODAzN2U3YzQwMzUyMmNjMmUwNDcwNDYwMjRlODgwZjdiZmJiZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl9czcdrqpZXR8ZGSlJdeGzHbUzIeSvj6Sqnr7CpXOI)
> 
> 你退出登录重新登录试试，左下角选中国 ![image](https://private-user-images.githubusercontent.com/5753992/353283119-8ae8c2c7-1460-4ab3-9681-ae342e5f36b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDU0MTgsIm5iZiI6MTcyMjMwNTExOCwicGF0aCI6Ii81NzUzOTkyLzM1MzI4MzExOS04YWU4YzJjNy0xNDYwLTRhYjMtOTY4MS1hZTM0MmU1ZjM2YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDIwNTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM2ZWU2MmRkZTZmNTcyYWEzOTJhNDI1MDRlNDI1MDM3OWJmYWY4MmEwOTA2YTcwN2IyZjM4OGE3ZTU5Y2Y5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L3kZbKe8Wcs4sCtYVr4au8hEalhBVCwh0DvnD_CAhc8)

我没有这个界面，我下载完打开就在下面这个界面；而且我看了源码，源码里面给大模型得输入就是英文
<img width="1081" alt="1722305222925" src="https://github.com/user-attachments/assets/327afe5e-72b8-4126-a920-786fa3390ec1">

**Comment by tmlx1990** [comment]
> > > 直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文 ![image](https://private-user-images.githubusercontent.com/135098261/352399314-7bc83375-15e0-434d-aedd-2a975e5e5ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDQ1MTgsIm5iZiI6MTcyMjMwNDIxOCwicGF0aCI6Ii8xMzUwOTgyNjEvMzUyMzk5MzE0LTdiYzgzMzc1LTE1ZTAtNDM0ZC1hZWRkLTJhOTc1ZTVlNWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlmYjZlNWRjYjJjMWU1NTcwN2NhNWE1ODAzN2U3YzQwMzUyMmNjMmUwNDcwNDYwMjRlODgwZjdiZmJiZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl9czcdrqpZXR8ZGSlJdeGzHbUzIeSvj6Sqnr7CpXOI)
> > 
> > 
> > 你退出登录重新登录试试，左下角选中国 ![image](https://private-user-images.githubusercontent.com/5753992/353283119-8ae8c2c7-1460-4ab3-9681-ae342e5f36b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDU0MTgsIm5iZiI6MTcyMjMwNTExOCwicGF0aCI6Ii81NzUzOTkyLzM1MzI4MzExOS04YWU4YzJjNy0xNDYwLTRhYjMtOTY4MS1hZTM0MmU1ZjM2YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDIwNTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM2ZWU2MmRkZTZmNTcyYWEzOTJhNDI1MDRlNDI1MDM3OWJmYWY4MmEwOTA2YTcwN2IyZjM4OGE3ZTU5Y2Y5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L3kZbKe8Wcs4sCtYVr4au8hEalhBVCwh0DvnD_CAhc8)
> 
> 我没有这个界面，我下载完打开就在下面这个界面；而且我看了源码，源码里面给大模型得输入就是英文 <img alt="1722305222925" width="1081" src="https://private-user-images.githubusercontent.com/135098261/353285636-327afe5e-72b8-4126-a920-786fa3390ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgzOTUsIm5iZiI6MTcyMjMwODA5NSwicGF0aCI6Ii8xMzUwOTgyNjEvMzUzMjg1NjM2LTMyN2FmZTVlLTcyYjgtNDEyNi1hOTIwLTc4NmZhMzM5MGVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMjU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzBiNDQxYzJmYTY5MGZhNGU5M2RiNTBkNjEzMmYwMDk3NDBiYjZmYjA1NWRlNWJiN2U0MDdiMmM2MDUzOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HSoSoiuSUYUMNoQzsg10-QI32uZSGjXP7meCVn8EoLw">

你用的开源版吗？要是开源版需要自己接入AI功能了。

**Comment by chalice321951** [comment]
> > > > 直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文 ![image](https://private-user-images.githubusercontent.com/135098261/352399314-7bc83375-15e0-434d-aedd-2a975e5e5ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDQ1MTgsIm5iZiI6MTcyMjMwNDIxOCwicGF0aCI6Ii8xMzUwOTgyNjEvMzUyMzk5MzE0LTdiYzgzMzc1LTE1ZTAtNDM0ZC1hZWRkLTJhOTc1ZTVlNWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlmYjZlNWRjYjJjMWU1NTcwN2NhNWE1ODAzN2U3YzQwMzUyMmNjMmUwNDcwNDYwMjRlODgwZjdiZmJiZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl9czcdrqpZXR8ZGSlJdeGzHbUzIeSvj6Sqnr7CpXOI)
> > > 
> > > 
> > > 你退出登录重新登录试试，左下角选中国 ![image](https://private-user-images.githubusercontent.com/5753992/353283119-8ae8c2c7-1460-4ab3-9681-ae342e5f36b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDU0MTgsIm5iZiI6MTcyMjMwNTExOCwicGF0aCI6Ii81NzUzOTkyLzM1MzI4MzExOS04YWU4YzJjNy0xNDYwLTRhYjMtOTY4MS1hZTM0MmU1ZjM2YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDIwNTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM2ZWU2MmRkZTZmNTcyYWEzOTJhNDI1MDRlNDI1MDM3OWJmYWY4MmEwOTA2YTcwN2IyZjM4OGE3ZTU5Y2Y5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L3kZbKe8Wcs4sCtYVr4au8hEalhBVCwh0DvnD_CAhc8)
> > 
> > 
> > 我没有这个界面，我下载完打开就在下面这个界面；而且我看了源码，源码里面给大模型得输入就是英文 <img alt="1722305222925" width="1081" src="https://private-user-images.githubusercontent.com/135098261/353285636-327afe5e-72b8-4126-a920-786fa3390ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgzOTUsIm5iZiI6MTcyMjMwODA5NSwicGF0aCI6Ii8xMzUwOTgyNjEvMzUzMjg1NjM2LTMyN2FmZTVlLTcyYjgtNDEyNi1hOTIwLTc4NmZhMzM5MGVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMjU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzBiNDQxYzJmYTY5MGZhNGU5M2RiNTBkNjEzMmYwMDk3NDBiYjZmYjA1NWRlNWJiN2U0MDdiMmM2MDUzOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HSoSoiuSUYUMNoQzsg10-QI32uZSGjXP7meCVn8EoLw">
> 
> 你用的开源版吗？要是开源版需要自己接入AI功能了。

**Comment by chalice321951** [comment]
> > > > > 直接下载的exe文件，选中对sql优化或者解释，返回的是英文，请问怎么改成中文 ![image](https://private-user-images.githubusercontent.com/135098261/352399314-7bc83375-15e0-434d-aedd-2a975e5e5ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDQ1MTgsIm5iZiI6MTcyMjMwNDIxOCwicGF0aCI6Ii8xMzUwOTgyNjEvMzUyMzk5MzE0LTdiYzgzMzc1LTE1ZTAtNDM0ZC1hZWRkLTJhOTc1ZTVlNWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlmYjZlNWRjYjJjMWU1NTcwN2NhNWE1ODAzN2U3YzQwMzUyMmNjMmUwNDcwNDYwMjRlODgwZjdiZmJiZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl9czcdrqpZXR8ZGSlJdeGzHbUzIeSvj6Sqnr7CpXOI)
> > > > 
> > > > 
> > > > 你退出登录重新登录试试，左下角选中国 ![image](https://private-user-images.githubusercontent.com/5753992/353283119-8ae8c2c7-1460-4ab3-9681-ae342e5f36b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDU0MTgsIm5iZiI6MTcyMjMwNTExOCwicGF0aCI6Ii81NzUzOTkyLzM1MzI4MzExOS04YWU4YzJjNy0xNDYwLTRhYjMtOTY4MS1hZTM0MmU1ZjM2YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDIwNTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM2ZWU2MmRkZTZmNTcyYWEzOTJhNDI1MDRlNDI1MDM3OWJmYWY4MmEwOTA2YTcwN2IyZjM4OGE3ZTU5Y2Y5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L3kZbKe8Wcs4sCtYVr4au8hEalhBVCwh0DvnD_CAhc8)
> > > 
> > > 
> > > 我没有这个界面，我下载完打开就在下面这个界面；而且我看了源码，源码里面给大模型得输入就是英文 <img alt="1722305222925" width="1081" src="https://private-user-images.githubusercontent.com/135098261/353285636-327afe5e-72b8-4126-a920-786fa3390ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgzOTUsIm5iZiI6MTcyMjMwODA5NSwicGF0aCI6Ii8xMzUwOTgyNjEvMzUzMjg1NjM2LTMyN2FmZTVlLTcyYjgtNDEyNi1hOTIwLTc4NmZhMzM5MGVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMjU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzBiNDQxYzJmYTY5MGZhNGU5M2RiNTBkNjEzMmYwMDk3NDBiYjZmYjA1NWRlNWJiN2U0MDdiMmM2MDUzOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HSoSoiuSUYUMNoQzsg10-QI32uZSGjXP7meCVn8EoLw">
> > 
> > 
> > 你用的开源版吗？要是开源版需要自己接入AI功能了。

对，我用的开源版得，我自己ai也对接了，然后使用得时候点击sql优化或者解释输出得就是英文；我看了源码，这块给ai输入得是英文，应该要改源码
