### ISSUE TITLE
Bug: 右侧的三个按钮点了没反应

### ISSUE THREAD

**Issue by i5baobao** [chat2db/Chat2DB#1488]
### Chat2DB Version

3.2.4

### Describe the bug

右侧的三个按钮点了没反应，我卸载重装了还是这样。Chat2DB 3.2.4
<img width="129" alt="Snipaste_2024-08-01_18-17-57" src="https://github.com/user-attachments/assets/5a375987-e259-48f3-badc-174a3bc64253">

**Comment by miahemu** [comment]
我这边没有复现到你的问题，这边是能正常打开的
<img width="443" alt="image" src="https://github.com/user-attachments/assets/4ec0dff9-8d32-4d14-9ab3-58ce16626c50">

**Comment by i5baobao** [comment]
> 我这边没有复现到你的问题，这边是能正常打开的 <img alt="image" width="443" src="https://private-user-images.githubusercontent.com/157001655/354456230-4ec0dff9-8d32-4d14-9ab3-58ce16626c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODEyMjUsIm5iZiI6MTcyMjU4MDkyNSwicGF0aCI6Ii8xNTcwMDE2NTUvMzU0NDU2MjMwLTRlYzBkZmY5LThkMzItNGQxNC05YWIzLTU4Y2UxNjYyNmM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNjQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjQzYjYyNzIwNzE5ZmMzMDJmZTUyYzE0ZTk0ZGFjODUyZmFjZDI1YTFlNGFiMTc1OTQ5NzM3MDU0ZjQ5YjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xPlHkBdemN4HFimBNEoWuMy3TzRyFXw2TxpZes9U62s">

有没有重置应用的方法？现在我重装应用感觉里面的配置还是保留的，导致重装也不能解决这个问题。

**Comment by miahemu** [comment]
你好，麻烦你加群私聊管理员😂
<img width="657" alt="image" src="https://github.com/user-attachments/assets/39757401-1802-4f42-a4c6-d2c80ee1fedd">

**Comment by i5baobao** [comment]
> 你好，麻烦你加群私聊管理员😂 <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/157001655/354499805-39757401-1802-4f42-a4c6-d2c80ee1fedd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODIzMjYsIm5iZiI6MTcyMjU4MjAyNiwicGF0aCI6Ii8xNTcwMDE2NTUvMzU0NDk5ODA1LTM5NzU3NDAxLTE4MDItNGY0Mi1hNGM2LWQyYzgwZWUxZmVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNzAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWYyNmQ1YjA5OWM3OWM2ODM5ZWI4NDliMjBiYzcwMTRlNjY2YWVlZDcyYWExZTk1YzZmZTc4NmUxZjY2MTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hp0NTc_qXtwEfh9tE8MvhSbAndB7hN5CBBlalNv-nPE">

哦，我找了专业卸载工具彻底卸载又安装，终于好了。
