### ISSUE TITLE
单独启动 chat2db-client  yarn run start:web  报错 Unbound variable "npm_config_app_version

### ISSUE THREAD

**Issue by SanpLee** [chat2db/Chat2DB#1496]
### Chat2DB Version

3.2.4

### Describe the bug

单独启动 chat2db-client  yarn run start:web  报错 Unbound variable "npm_config_app_version，

**Comment by juliet0416** [comment]
查看下chat2db-client/package.json 中的 start:web命令

**Comment by JerryFan626** [comment]
查看下chat2db-client/package.json中的 start:web 命令

**Comment by SanpLee** [comment]
> 查看下chat2db-client/package.json中的 start:web 命令

![image](https://github.com/user-attachments/assets/ab4e203c-7f97-4d9c-95cc-42cc9906813a)
还是需要 npm_config_app_version

**Comment by JerryFan626** [comment]
直接删掉就可以的

**Comment by SanpLee** [comment]
> 直接删掉就可以的

我试试
