### ISSUE TITLE
Bug: 选中表的schema将会被添加到prompt中操作中，如果表太多则无法滚动选择到自己想要的表

### ISSUE THREAD

**Issue by weiwei2012holy** [chat2db/Chat2DB#150]
### Chat2DB Version

Chat2DB v2.0.1

### Describe the bug

AI输入框后面选择表作为prompt时，表太多的情况下显示不完全导致无法勾选，建议增加滚动条&搜索框

**Comment by jipengfei-jpf** [comment]
2.0.2已经修复
