### ISSUE TITLE
优化: 🔗全部丢失

### ISSUE THREAD

**Issue by nfpss** [chat2db/Chat2DB#1513]
每次登陆chatdb2pro都需要重新登陆 登陆进去链接全部丢失了。

**Comment by Chat2DB-Pro** [comment]
你是换了不同的电脑吗？存储哪里选择cloud就所有电脑登录都可以看到了

**Comment by nfpss** [comment]
我刚刚重新登了 然后链接了链接 然后退出再次登录就没有了

**Comment by nfpss** [comment]
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/c8b39461-15b4-46c2-8add-60d7d86f924f">
并没有存储选项

**Comment by Chat2DB-Pro** [comment]
你要点保存啊

**Comment by nfpss** [comment]
> 你要点保存啊

我现在重新登录进去了然后新建不了🔗 显示必须充值，然后控制台的链接又是显示为空的 我想知道怎么删除本地存储地址。然后这个chat2pro和chat3.4.2有啥关系呀 3.4.2那个打不开一直在转圈圈

**Comment by tmlx1990** [comment]
你使用的是什么版本？开源版还是pro？

**Comment by nfpss** [comment]
> 你使用的是什么版本？开源版还是pro？

我是用的pro版本，开源的mac版本进不去 会
<img width="615" alt="image" src="https://github.com/user-attachments/assets/0e48a3df-2dd9-476f-87f0-7915a0bb9690">
<img width="438" alt="image" src="https://github.com/user-attachments/assets/e56a68ea-280b-47be-ae66-d8e8be6ad175">

然后

**Comment by tmlx1990** [comment]
pro是在创建连接的时候，可以选择本地或者云存储，你如果之前选了本地，需要在那台电脑上才能看到。

**Comment by tmlx1990** [comment]
![image](https://github.com/user-attachments/assets/4768a9c0-5b17-4f01-b2c6-3b54ef405cb0)

**Comment by nfpss** [comment]
ented [now](https://github.com/chat2db/Chat2DB/issues/1513#issuecomment-2295587281)
我早上过来在公司这电脑创建了链接 然后我推出了后重新登录就看不到链接了 然后创建新链接又会显示充值页面，一个账号的本地连接也是共享的吗 我得回去把家里的电脑连接删除才行吗？

**Comment by tmlx1990** [comment]
你看下是不是开过代理？导致登录时识别的地区不一样了？国内和国外是两套存储。

**Comment by nfpss** [comment]
> ![image](https://private-user-images.githubusercontent.com/5753992/358968273-4768a9c0-5b17-4f01-b2c6-3b54ef405cb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzc1NTksIm5iZiI6MTcyNDAzNzI1OSwicGF0aCI6Ii81NzUzOTkyLzM1ODk2ODI3My00NzY4YTljMC01YjE3LTRmMDEtYjJjNi0zYjU0ZWY0MDVjYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDMxNDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUxOGQ3NWVmMDVjN2ZiZDFmODEzYzIwOTAyYjBlMzBmZDUzMWIzNGRkZGQwYzE5NTgwMWRlMTk3YmY2YTg2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zp3NAaLeO7tbzSYYu-N97KAi2qZuthwBZ6Ku7RNGzBk)

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/1af45b36-a8b5-49ed-9c21-b53a29be4ab5">

<img width="1519" alt="image" src="https://github.com/user-attachments/assets/f0bd3a64-eee7-49bb-b5ef-10033e694704">

**Comment by tmlx1990** [comment]
存储在本地的连接 也是统计数量的。pro未付费版是有上限的。

**Comment by nfpss** [comment]
> 存储在本地的连接 也是统计数量的。pro未付费版是有上限的。

刚用微信登录了 然后尝试了下有用，可以正常创建链接，退出后还是有效的。Thanks♪(･ω･)ﾉ

**Comment by tmlx1990** [comment]
> > 存储在本地的连接 也是统计数量的。pro未付费版是有上限的。
> 
> 刚用微信登录了 然后尝试了下有用，可以正常创建链接，退出后还是有效的。Thanks♪(･ω･)ﾉ

OK，可以添加官方客服群，有问题那里沟通更方便。
