### ISSUE TITLE
建议: 网页版引入多租户管理能力

### ISSUE THREAD

**Issue by cnwelee** [chat2db/Chat2DB#154]
大家关注点可能都在AI上，特别棒的功能
不过这个要是在团队里用，要是能有个账号管理能力更好

基本需求就是两个角色
- 管理员：可以配置ai和做数据库接入，分配权限
- 普通用户：登录账号只需要使用即可不用关心配置和接入

更高阶一点的需求，账号体系最好是能接入LDAP或者OAuth~~

**Comment by cnwelee** [comment]
看了下介绍，好像就是团队协作和环境隔离这部分还没实现对吧……

**Comment by imyuanandyou** [comment]
接入OAuth支持+1

**Comment by robinji0** [comment]
duplicate with #371
