### ISSUE TITLE
Bug: 好像没有支持db2呢？

### ISSUE THREAD

**Issue by Vitammine** [chat2db/Chat2DB#160]
### Chat2DB Version

2.0.1

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/102985208/c4c858e1-3d53-467e-9a0d-da3a81d6fb7d)
![image](https://github.com/chat2db/Chat2DB/assets/102985208/d578a175-ea00-48f7-8eb9-0ff1fb6687d0)

**Comment by chenxian01** [comment]
Supported in 2.0.5 and later.
