### ISSUE TITLE
Bug: dashboard 增加数据源，选择一个连接。问题：已经添加的连接在DASHBOARD这里不显示

### ISSUE THREAD

**Issue by clouderyu** [chat2db/Chat2DB#165]
### Chat2DB Version

v2.0.1

### Describe the bug

windows客户端

dashboard 增加数据源，选择一个连接。问题：已经添加的连接在DASHBOARD这里不显示。

**Comment by chenxian01** [comment]
Cannot quite get the problem. Please provide more details, screenshot would be better.

**Comment by chenxian01** [comment]
Closed as not updated for a long time.
