### ISSUE TITLE
Bug: syntax error, expect ONLY, actual ROW, pos 60, line 1, column 58, token ROW

### ISSUE THREAD

**Issue by aliqiu** [chat2db/Chat2DB#166]
### Chat2DB Version

v2.0.1 build20230703145441

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/57788488/2aae6c6a-baed-4fad-a1ce-22ecc28bd73c)
oracle版本 19c 无法执行FETCH FIRST 1 ROW ONLY;

**Comment by chenxian01** [comment]
Need to select the corresponding SQL statement to execute. Otherwise, it would execute all the sql statement, then your sql might invoke sql syntax error.
