### ISSUE TITLE
建议: 建议增加sql脚本的导入和导出功能

### ISSUE THREAD

**Issue by minghaozhi** [chat2db/Chat2DB#167]

**Comment by fanjinyu-fjy** [comment]
导出功能已经在最新版上线了。
导入功能可以直接执行

**Comment by lihua123569** [comment]
V3.1.14 未找到导入导出入口

**Comment by tmlx1990** [comment]
> V3.1.14 未找到导入导出入口
导出的。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/12c0bc6d-539f-48b0-b06d-9bd4dc092a89)

**Comment by lihua123569** [comment]
嗯，看到单表导出了。
我是期望全库的导入导出，像navicat那样

**Comment by tmlx1990** [comment]
> 嗯，看到单表导出了。 我是期望全库的导入导出，像navicat那样

哦哦，这个功能目前还没有。等后续完善。
