### ISSUE TITLE
Bug: AzureOpenAI自然语言转SQL格式错误

### ISSUE THREAD

**Issue by johnbuddhaking** [chat2db/Chat2DB#168]
### Chat2DB Version

main

### Describe the bug

解析AzureOpenAI的流式输出时，StringUtils.isNotBlank(data)会把正常的空格过滤掉，导致最终SQL格式有误。
我这边的修改方式：
(1) AzureOpenAiStreamClient.java文件87行，改成 if(text!=null)；
(2) AzureOpenAIEventSourceListener.java文件57行，删除if isNotBlank逻辑。

![img_v2_62441f50-a877-44d9-b903-7e1ea4f49dfl](https://github.com/chat2db/Chat2DB/assets/20645652/46b4dce9-fc83-4f91-8020-70a20f17bfc0)

**Comment by chenxian01** [comment]
Fixed in the latest version.
