### ISSUE TITLE
Bug: 表结构多是，有一部分数据没有显示出来，左右没有出现相应的滚动条

### ISSUE THREAD

**Issue by hy215215** [chat2db/Chat2DB#176]
### Chat2DB Version

2.0.1

### Describe the bug

1：表字段多时，执行结果中没有显示全所有的字段，部分字段被隐藏了，下端也没有出现相应的左右滚动条。
2：window的任务栏的图标显示不全
3：新打开一个表，不能在右侧新打开一个标签页，会重复在第一个标签页中显示

**Comment by chenxian01** [comment]
Fixed in the latest version.
