### ISSUE TITLE
Bug: 为什么最多只能查1000条数据

### ISSUE THREAD

**Issue by huangkl1** [chat2db/Chat2DB#178]
### Chat2DB Version

v2.0.1

### Describe the bug

用count(*)   只显示 1000

**Comment by huangkl1** [comment]
能加上继续显示更多行的功能吗。

**Comment by huangkl1** [comment]
还有，页面上查询的时候只显示了耗时，没显示总共查出来多少行

**Comment by shanhexi** [comment]
嗯，这个在规划内 会加总条数和翻页

**Comment by chenxian01** [comment]
Supported in 2.0.5 and later.
