### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ximing66** [chat2db/Chat2DB#180]
### Chat2DB Version

2.0.1

### Describe the bug

连接达梦8数据库后无法进行语句查询，日志报错

ERROR 1 --- [io-10824-exec-1] a.c.s.s.e.EasyControllerExceptionHandler.164 : cadac300-d6c1-4c09-a3b1-b365189e2576 | 发生未知异常/api/rdb/dml/execute:ActionResult(success=false, errorCode=common.systemError, errorMessage=系统发生异常，可在帮助中点击日志查看异常详情。如无法解决，可关注微信公众号Text2SQL咨询帮助, traceId=null),请求参数:{}

java.lang.UnsupportedOperationException: null

**Comment by chenxian01** [comment]
Please try the latest version. If you still have this issue, please provide more log details.
