### ISSUE TITLE
Bug: SQL语句过长的时候，最下面几行SQL语句会被遮挡

### ISSUE THREAD

**Issue by junwei-liu** [chat2db/Chat2DB#184]
### Chat2DB Version

v2.0.1

### Describe the bug

<img width="182" alt="image" src="https://github.com/chat2db/Chat2DB/assets/78710778/85b13b1f-f69c-45b3-accc-f5cbe90749e0">

**Comment by jipengfei-jpf** [comment]
2.0.2已经支持
