### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by chenweidong32** [chat2db/Chat2DB#188]
### Chat2DB Version

2.0.1

### Describe the bug

A JavaScript error occurred in the main process
![4112d9ee9177179eac2484cc716a022](https://github.com/chat2db/Chat2DB/assets/59788992/6782580f-0a6a-4b46-808e-63fba124fe92)

**Comment by chenxian01** [comment]
Cannot reproduce in the latest version. Please try the latest version.
