### ISSUE TITLE
Bug: Azure AI的模式下，只有打开程序的第一次调用能成功，后续都会失败

### ISSUE THREAD

**Issue by JinHisAndy** [chat2db/Chat2DB#192]
### Chat2DB Version

最新版

### Describe the bug

只有首次能正常生成语句，后续都会失败

**Comment by songjiebj01** [comment]
我这边配置的Azure AI，一直不成功。也不知道在哪里查看错误日志。

**Comment by fanjinyu-fjy** [comment]
> 我这边配置的Azure AI，一直不成功。也不知道在哪里查看错误日志。

错误日志可以在，帮助->打开日志中查看

**Comment by wurong12** [comment]
到的配置信息没有问题,但是调用AI的过程一直报错.

**Comment by chenxian01** [comment]
Fixed in 2.0.4 and later.
