### ISSUE TITLE
建议: 驱动版本可以自己添加设置

### ISSUE THREAD

**Issue by Edian-Midir** [chat2db/Chat2DB#196]
能不能像dbeaver一样可以自己下载对应的驱动包，因为我现在用的**SQL Server2019**,**Chat2DB**本身自带的**openJDK17**，mssql驱动是11.2.1的

这导致我如果正常的打开软件连接sql server的话就会报错
 **驱动程序无法通过使用安全套接字层(SSL)加密与 SQL Server 建立安全连接。错误:“PKIX path building failed:** 

这个问题我原先也碰到过类似的，是因为我使用jdk 11 + mssql8.2的驱动连接SQL Server2014出现的，但是同样的连接对SQL Server2019是正常的。
![image](https://github.com/chat2db/Chat2DB/assets/75260279/3b82e8d9-cdde-4a40-a3fd-5dada1bdce33)

我个人猜测这个主要还是因为驱动版本的问题，因为我环境变量设置了jdk8，11，17在dbeaver下使用同样的jar包都能正常使用

**Comment by jipengfei-jpf** [comment]
2.0.2已支持
