### ISSUE TITLE
Bug: redis 不支持 

### ISSUE THREAD

**Issue by aaron-zzz** [chat2db/Chat2DB#197]
### Chat2DB Version

最新版

### Describe the bug

连接上redis 后，查不了 数据，把redis 当 mysql 了

**Comment by Globl** [comment]
急急急急！自己打了最新版的镜像，结果一试redis用不了。求修复

**Comment by WSharkCoder** [comment]
好好好，可以链接上Redis上了，为啥Set命令可以执行， Get命令执行就报错捏

**Comment by WSharkCoder** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/50436729/fedcda40-9c3b-4a7b-a7b7-aa9b00e171d1)
![image](https://github.com/chat2db/Chat2DB/assets/50436729/8629dbd3-6b78-4e06-8763-cb92c0fb9efe)

**Comment by robinji0** [comment]
marked in #402
