### ISSUE TITLE
Bug: presto 找不到驱动

### ISSUE THREAD

**Issue by zhangkuantian** [chat2db/Chat2DB#2]
### Chat2DB Version

Chat2DB-1.0.11.dmg

### Describe the bug

Mac 1.0.11 版本的客户端连接 presto 时报找不到驱动，报错界面如下:
![企业微信截图_fdb11426-7f8b-433b-88f8-738e3e475631](https://github.com/chat2db/Chat2DB/assets/11786332/deae1678-ad0d-4bc9-90a3-b3ccbb461af7)

**Comment by chat2db-yx** [comment]
2.0.1已修复
