### ISSUE TITLE
Bug: Chat2DB AI key配置了不能正常访问

### ISSUE THREAD

**Issue by wp2code** [chat2db/Chat2DB#209]
### Chat2DB Version

v2.0.1

### Describe the bug

# AI配置 
![1688960951100](https://github.com/chat2db/Chat2DB/assets/12785365/8141cc2b-43f8-4854-9c75-baf92f5a1c12)
# 不能正常访问
![1688960982265](https://github.com/chat2db/Chat2DB/assets/12785365/4e47153e-2bd1-42eb-b0f8-ad87536d63bf)
# 补充说明
上网要配置白名单，如果要正常访问是不是有chat2db的白名单网址？

**Comment by jipengfei-jpf** [comment]
是的
