### ISSUE TITLE
Bug: 库中表较多的情况下拉窗口抖动，无法下拉到下面，导致无法选中需要的表

### ISSUE THREAD

**Issue by liweirong** [chat2db/Chat2DB#211]
### Chat2DB Version

v2.0.1

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/25474719/5ec60d5f-40a7-4ed6-b091-2d383429e101)

**Comment by biluping** [comment]
我也遇到了，希望尽快解决下

**Comment by fanjinyu-fjy** [comment]
2.0.2 版本已修复
