### ISSUE TITLE
建议: 都Electron了，为什么不顺手打个linux

### ISSUE THREAD

**Issue by SemiThin** [chat2db/Chat2DB#213]
还是有少部分在linux下开发的呀，我就是其中之一

**Comment by GershonWang** [comment]
linux版本需求+1

**Comment by ViokingTung** [comment]
linux版本需求+1

**Comment by chenxian01** [comment]
Planned.

**Comment by longletian** [comment]
Planned.

**Comment by fanjinyu-fjy** [comment]
最新版已经支持了LInux大包

**Comment by SemiThin** [comment]
> 最新版已经支持了LInux，请下载体验下。

# ubuntu @ ubuntu in ~/Downloads [17:30:46] 
$ ./Chat2DB-2.0.11.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

**Comment by SemiThin** [comment]
sudo apt install libfuse2

**Comment by SemiThin** [comment]
# ubuntu @ ubuntu in ~/Downloads [17:37:03] C:130
$ ll Chat2DB-2.0.11.AppImage 
-rwxr-xr-x 1 ubuntu ubuntu 217M  8月 11 15:30 Chat2DB-2.0.11.AppImage

# ubuntu @ ubuntu in ~/Downloads [17:37:07] 
$ ./Chat2DB-2.0.11.AppImage 
fusermount: mount failed: Operation not permitted

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory

# ubuntu @ ubuntu in ~/Downloads [17:37:12] C:127
$ sudo ./Chat2DB-2.0.11.AppImage
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.

# ubuntu @ ubuntu in ~/Downloads [17:37:21] C:1
$

**Comment by SemiThin** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/12593507/1add331a-76d9-457a-ac71-a3933fda0a5c)
