### ISSUE TITLE
Bug: sql table name does not exist

### ISSUE THREAD

**Issue by yegetables** [chat2db/Chat2DB#214]
### Chat2DB Version

2.0.1

### Describe the bug

When converting natural language to sql to do multi-table association query, the most suitable name cannot be automatically found based on the existing table name, and a table name that does not exist is generated.
For example, in the figure below, the relational table of the database is role_permission_ref, and the relational tables in the generated SQL are named role_permission and permissionio_role.

<img width="1116" alt="image" src="https://github.com/chat2db/Chat2DB/assets/37119488/b449b940-53d9-4d27-94a7-a51adf6cc9f6">

Suggested solution: The prompt word requires the use of existing indications to find the table that best matches the description.

**Comment by chenxian01** [comment]
Planned in future. You can choose the table manually as work around.
