### ISSUE TITLE
优化: 2.0.1版本秒退

### ISSUE THREAD

**Issue by sl2026** [chat2db/Chat2DB#219]
系统情况:
OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation

其他信息:
系统制造商:       Dell Inc.
系统型号:         OptiPlex 7080
系统类型:         x64-based PC

详细描述:
双击打开之后显示一片空白,在等待约5s左右后闪一下自动关掉了,查看任务管理器,在进程中还可以看到

**Comment by jipengfei-jpf** [comment]
建议设计2.0.2
