### ISSUE TITLE
Can you clarify your license

### ISSUE THREAD

**Issue by tsodring** [chat2db/Chat2DB#220]
Hi,

There seems to be uncertainty with regards to the license your software is released under.

In README.md you point to 

> [![License](https://img.shields.io/github/license/alibaba/fastjson2?color=4D7A97&logo=apache)](https://www.apache.org/licenses/LICENSE-2.0.html)

but you also have a file called [Chat2DB_LICENSE](https://github.com/chat2db/Chat2DB/blob/main/Chat2DB_LICENSE), that states a different license. 

Then you have a note:

> License Notation: Chat2DB is constructed and distributed for personal and non-commercial use only. For commercial use of this project, please contact corresponding authors.

This seems like a very complex way to deal with licensing. There seems to be three different licenses in play. Could you clarify the license the software is licensed under.

Thanks!

**Comment by chenxian01** [comment]
You should pay attention to all those license.
