### ISSUE TITLE
优化: chat2db-client无法正常build，执行npm install报错

### ISSUE THREAD

**Issue by gwdgithubnom** [chat2db/Chat2DB#227]
![image](https://github.com/chat2db/Chat2DB/assets/13328198/b72dfae5-41f3-457f-8978-f0f5f1fcee3d)
![image](https://github.com/chat2db/Chat2DB/assets/13328198/516055e9-dc21-401c-9cc4-4d5c8ab0ca7d)

**Comment by shanhexi** [comment]
建议使用yarn，我们只维护了yarn lock
