### ISSUE TITLE
Bug: 说好的创建表修改表功能呢

### ISSUE THREAD

**Issue by zhaoliangdu** [chat2db/Chat2DB#230]
### Chat2DB Version

2.0.1

### Describe the bug

版本 | 功能介绍 | 上线时间
-- | -- | --
V1.0.x | 基础功能 | 已发布
V1.1.x | 支持环境隔离、支持团队协作 | 5月
V1.2.x | 支持创建、修改、删除表 | 6月
V1.3.x | 支持非关系型数据库 | 7月

这都安装的2.0 也不见1.2的功能在什么地方

**Comment by chenxian01** [comment]
Thanks for your reminder. We want to support this as soon as we can, but there are so many features need to be planned. So  we will try best, please stay tune.

**Comment by chenxian01** [comment]
duplicate with #193
