### ISSUE TITLE
Bug:配置Azure AI后，无法使用ChatGPT的能力

### ISSUE THREAD

**Issue by songjiesdnu** [chat2db/Chat2DB#232]
### Chat2DB Version

v2.0.1 build20230703144959

### Describe the bug

使用Chat2DB AI是没问题的，但通过微软的Azure AI就不行了。想求助下~
![Azure AI](https://github.com/chat2db/Chat2DB/assets/7113099/6be9db5b-8b7d-42f0-8610-81452cb1b546)

**Comment by wurong12** [comment]
我也是,这个微软的Azure AI存在问题,目前也不清楚他的具体配置参数是什么含义.

**Comment by chenxian01** [comment]
> ### Chat2DB Version
> v2.0.1 build20230703144959
> 
> ### Describe the bug
> 使用Chat2DB AI是没问题的，但通过微软的Azure AI就不行了。想求助下~ ![Azure AI](https://user-images.githubusercontent.com/7113099/252847875-6be9db5b-8b7d-42f0-8610-81452cb1b546.jpg)

your endpoint is not a valid host or url.

**Comment by chenxian01** [comment]
> 我也是,这个微软的Azure AI存在问题,目前也不清楚他的具体配置参数是什么含义.

Please refer this article https://learn.microsoft.com/zh-cn/rest/api/cognitiveservices/azureopenaistable/models/get?source=recommendations&tabs=HTTP
