### ISSUE TITLE
安装exe文件后，提示“无法定位程序输入点 discardvirtualmemory ”

### ISSUE THREAD

**Issue by guidexd** [chat2db/Chat2DB#235]
### Chat2DB Version

202.0.2.exe

### Describe the bug

安装windows版本后，提示报错“无法定位程序输入点 discardvirtualmemory ”，本人系统win7
![Uploading 报错.PNG…]()

**Comment by hbsjz-swl** [comment]
前一个版本还没有这个问题  更新了0.2版本以后就提示这个

**Comment by fanjinyu-fjy** [comment]
下载下最新的包，已解决
