### ISSUE TITLE
Bug: mongo链接后，无法搜到表信息，也无法进行mongo查询

### ISSUE THREAD

**Issue by yunxiaoyang01** [chat2db/Chat2DB#236]
### Chat2DB Version

v2.0.2 

### Describe the bug

<img width="984" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39183504/d5ba5e31-e0ac-482c-93a0-a5fdc7a109dc">
mongo数据库，但是链接之后，双击表名出来的是mysql的语句。
然后直接使用 mql语句查询的时候也会报错
报错信息如下：
not supported.pos 2, line 1, column 1, token IDENTIFIER db

**Comment by robinji0** [comment]
marked in #406
