### ISSUE TITLE
Bug: postgresql无法查询

### ISSUE THREAD

**Issue by pengtaomach** [chat2db/Chat2DB#237]
### Chat2DB Version

v2.0.2 build20230712081551

### Describe the bug

查询的时候指定schema.表名的时候，一直报错
<img width="906" alt="image" src="https://github.com/chat2db/Chat2DB/assets/38904475/a6f3ac2f-287e-40a9-8d14-639b43e701b9">

**Comment by jipengfei-jpf** [comment]
是不是没有选中sql？多个sql没有分割
