### ISSUE TITLE
Bug: 自定义(非默认实例)实例的SQL Server(测试过2008 2019 2022版本)都连接不上，修改过各种参数都失败

### ISSUE THREAD

**Issue by bicijinlian** [chat2db/Chat2DB#239]
### Chat2DB Version

所有

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/10394955/5eea03f8-7105-43e0-9e67-484a7225809d)
![image](https://github.com/chat2db/Chat2DB/assets/10394955/58ce86d2-267e-4064-96ff-7495e7cb8e68)

**Comment by jipengfei-jpf** [comment]
网页版本？还是客户端版本？windows还是mac？检查防火墙设置

**Comment by bicijinlian** [comment]
window 11 桌面客户端 有详细图片



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月16日 16:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chat2db/Chat2DB] Bug: 自定义(非默认实例)实例的SQL Server(测试过2008 2019 2022版本)都连接不上，修改过各种参数都失败 (Issue #239) |

网页版本？还是客户端版本？windows还是mac？检查防火墙设置

**Comment by bicijinlian** [comment]
用其它客户端均能正常连接



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月16日 16:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chat2db/Chat2DB] Bug: 自定义(非默认实例)实例的SQL Server(测试过2008 2019 2022版本)都连接不上，修改过各种参数都失败 (Issue #239) |

网页版本？还是客户端版本？windows还是mac？检查防火墙设置
