### ISSUE TITLE
Bug: 配置代理以后陷入死循环

### ISSUE THREAD

**Issue by dianming** [chat2db/Chat2DB#242]
### Chat2DB Version

2.0.2

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/7877823/abfc6c4c-4339-4245-a744-71a6a29794b1)
一直尝试连接代理，又连接不上，进不去界面

**Comment by fanjinyu-fjy** [comment]
是设置的代理吗？ 这个地方的代理，代理的是后端服务

**Comment by fanjinyu-fjy** [comment]
你上文说的代理配置应该是后端服务地址，
可以下载最新版本，再体验看看。
issue先关闭下
