### ISSUE TITLE
Bug: ai提问报错不友好，

### ISSUE THREAD

**Issue by Joe12-24** [chat2db/Chat2DB#256]
### Chat2DB Version

v2.0.4

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/46116540/6709cff9-a8cf-4596-91fd-550ce3d668fe)

**Comment by wurong12** [comment]
附议

**Comment by chenxian01** [comment]
Corner Issue. It will only happen when the server is not stable.
