### ISSUE TITLE
Bug: After deployment with dockers, static resources cannot be accessed with nginx proxy.

### ISSUE THREAD

**Issue by YeshijieY** [chat2db/Chat2DB#260]
### Chat2DB Version

latest

### Describe the bug

After deployment with dockers, static resources cannot be accessed with nginx proxy. As follows:
Nginx configuration：
![image](https://github.com/chat2db/Chat2DB/assets/103729639/0bb2b6fb-154c-48dc-b858-a3a34a8ada78)

![image](https://github.com/chat2db/Chat2DB/assets/103729639/8f937df6-3c1a-4f5c-9e88-10d64441a095)

![image](https://github.com/chat2db/Chat2DB/assets/103729639/ac84c468-80bc-4470-add0-0d5db6764309)

**Comment by 13594439126** [comment]
怎么解决的，可以解决么？

**Comment by miahemu** [comment]
try new version
