### ISSUE TITLE
Bug: MYSQL内联同一张表多次，查询结果都是第一个内联的结果。如果在sql语句中存在"---"注释，则报sql语法错误

### ISSUE THREAD

**Issue by deon818** [chat2db/Chat2DB#269]
### Chat2DB Version

 所有版本

### Describe the bug

select dp.name,dpP.name from user_info ui
INNER JOIN dept dp on ui.dept_id = dp.id 
INNER JOIN dept dpP on up.parent_id = dpP.id 
查询的结果，dp.name,dpP.name返回的值是一样的。

select id,name from user_info
where id = 1 
-- and status = 0 
有注释，则整个sql报语法错误

**Comment by chenxian01** [comment]
Will be fixed at 2.0.5 and later.
