### ISSUE TITLE
Bug: 连接不上OpeanAi

### ISSUE THREAD

**Issue by geminiwhale** [chat2db/Chat2DB#278]
### Chat2DB Version

v

### Describe the bug

<img width="393" alt="1689832093729" src="https://github.com/chat2db/Chat2DB/assets/81454170/400a5a54-66ac-46a8-8ee7-322f46fbb4bd">

如上图配置，访问报错：
<img width="958" alt="1689832150337" src="https://github.com/chat2db/Chat2DB/assets/81454170/be3cdc41-747a-4a91-9bd6-5f66d48a8061">

**Comment by User011250** [comment]
你的key过期了或者用完了，自己去官网看看

**Comment by chenxian01** [comment]
Please refer the answer By @User011250
