### ISSUE TITLE
Bug: https://chat2db.opensource.alibaba.com/docs/ai/nl2sql 自然语言生成的sql是有问题的

### ISSUE THREAD

**Issue by wcyhappyprogrammer** [chat2db/Chat2DB#28]
### Chat2DB Version

当前版本:v0.0.0 build 20230616055221

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/30967471/4ea5f35f-a8c4-4f88-b53b-8c61839ea0c2)
明显是有问题的。麻烦看一下

**Comment by wcyhappyprogrammer** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/30967471/1a6e8266-3955-448b-8bd6-c8dccdb8eed7)

**Comment by wcyhappyprogrammer** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/30967471/4a7d2c2e-42b5-4d6e-98a7-e43e842cc3ef)

**Comment by chenxian01** [comment]
The version 1.x will not be supported. Please try the latest version. If the issue still happens, please submit a new issue and provide detail log information.
