### ISSUE TITLE
Bug: PostgreSQL数据库连接的时候，schema显示问题

### ISSUE THREAD

**Issue by zengxiong1995** [chat2db/Chat2DB#283]
### Chat2DB Version

当前版本:v2.0.4 build20230717052154

### Describe the bug

使用最高权限的用户postgres连接postgres时，仅显示很少的schema，不显示所有的schema。postgres用户是pg里面的最高权限用户，应该能看到所有的shema已经所有的table，建议java后端排查修复下。

**Comment by jipengfei-jpf** [comment]
fix 2.0.5
