### ISSUE TITLE
优化: 

### ISSUE THREAD

**Issue by Tonykeng** [chat2db/Chat2DB#284]
当远程host 为https时没有能设置SSL的地方，导致只能http连接
<html> <head><title>400 The plain HTTP request was sent to HTTPS port</title></head> <body> <center><h1>400 Bad Request</h1></center> <center>The plain HTTP request was sent to HTTPS port</center> <hr><center>openresty</center> </body> </html>

**Comment by jipengfei-jpf** [comment]
截图？哪里功能？

**Comment by Tonykeng** [comment]
<img width="938" alt="image" src="https://github.com/chat2db/Chat2DB/assets/4930512/a2c79b69-ac65-4a18-8258-146aeccd0b18">

点击查看详情可以看到相关的报错

**Comment by robinji0** [comment]
marked in #407
