### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by zwq652997** [chat2db/Chat2DB#3]
### Chat2DB Version

COMMON_SYSTEM_ERROR: 系统开小差啦，请尝试刷新页面或者联系管理员

### Describe the bug

<img width="677" alt="image" src="https://github.com/chat2db/Chat2DB/assets/31612408/09761d8b-7c5c-4956-9db8-1f7c0c3cada9">

**Comment by zwq652997** [comment]
但是测试连接提示成功，使用的是 mongodb 连接

**Comment by chenxian01** [comment]
Will plan in future.
