### ISSUE TITLE
优化: 当我选中库时，prompt中就自动添加了一些表，是否可以不自动添加

### ISSUE THREAD

**Issue by xiaobai3310** [chat2db/Chat2DB#315]
不太了解自动添加表时，确定添加哪些表的依据是啥。现在用基本都是每次手动清空后然后自己添加需要的表，没有用自动添加的。
![自动添加的表](https://i.hd-r.cn/37f89ec26e4a96077e1ce5248b1aa47a.png)

**Comment by chenxian01** [comment]
duplicate with #326
