### ISSUE TITLE
Bug: 新版本选择openai api key，执行时依然弹出微信扫描二维码并关注公众号“每天”可以获得 25 次 AI 使用机会。

### ISSUE THREAD

**Issue by zmcmcc** [chat2db/Chat2DB#328]
### Chat2DB Version

v2.0.5 build20230724083906

### Describe the bug

新版本在设置里选择openai api key，执行时依然弹出微信扫描二维码并关注公众号“每天”可以获得 25 次 AI 使用机会。右侧remaining那边是~remaining

**Comment by ericivan** [comment]
感觉是故意的，旧版也显示了次数出问题

**Comment by Voilett** [comment]
web端无法设置openai的key了

**Comment by zmcmcc** [comment]
意思是现在必须用他们自己的api了吗？？这不是本末倒置吗。。

**Comment by wolf27w** [comment]
这玩意是不是应该弄个开关，如果我不使用免费的就不提示了，如果使用在提示一样的呀

**Comment by oldweipro** [comment]
看来我不是个例。

**Comment by apegeek** [comment]
同样的问题， 版本2.0.6。 不过作者已经很棒了， 期望未来更好吧

**Comment by chenxian01** [comment]
Fixed in 2.0.7.
