### ISSUE TITLE
Bug: Clickhouse查询默认没有加数据库名称,查询会报错

### ISSUE THREAD

**Issue by cheng896911036** [chat2db/Chat2DB#329]
### Chat2DB Version

2.0.5

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/23022025/3558d163-075e-425f-833f-6c25b845dcde)
![image](https://github.com/chat2db/Chat2DB/assets/23022025/2e76418f-dbce-4da9-860c-6c58f9d21ea9)

**Comment by chenxian01** [comment]
Known issue, will fixed in feature.

**Comment by robinji0** [comment]
duplicate with #407
