### ISSUE TITLE
Bug: logo 显示不完整

### ISSUE THREAD

**Issue by NaBian** [chat2db/Chat2DB#334]
### Chat2DB Version

2.0.5

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/17383395/81b89347-e159-49da-b744-539c2d3de76c)
如图，左上角 logo 显示不完整，以下是机器信息：
![image](https://github.com/chat2db/Chat2DB/assets/17383395/1d772781-7fc2-4f03-a472-fc772d804706)
![image](https://github.com/chat2db/Chat2DB/assets/17383395/837c8fee-5c71-424a-a430-82a0353d1aee)
![image](https://github.com/chat2db/Chat2DB/assets/17383395/dcf476fb-c210-4c5a-b9bd-768fb080dd70)

**Comment by shanhexi** [comment]
最新版本已修复
