### ISSUE TITLE
本地启动后Bug: 

### ISSUE THREAD

**Issue by nuaabuaa07** [chat2db/Chat2DB#335]
### Chat2DB Version

master

### Describe the bug

<img width="1160" alt="image" src="https://github.com/chat2db/Chat2DB/assets/25834421/070dc2b4-0dd7-40e3-bced-6e4bf57288a1">
<img width="1297" alt="image" src="https://github.com/chat2db/Chat2DB/assets/25834421/ac4caebd-a909-4514-a85b-3d1956925206">

本地启动前、后端调试时，前端在登录页面，“画圈圈”，看到如图错误。貌似链接不上后端服务器，这是端口错误问题导致的吗？

**Comment by fanjinyu-fjy** [comment]
前端有代理映射到后端，代理的是10821的端口
但是你这个接口看上去没有报错
可以贴一下这个接口的返回信息

**Comment by fanjinyu-fjy** [comment]
可以拉取下最新版本代码，按上述回复操作下

issues先关闭了，有问题再开
