### ISSUE TITLE
Bug: jar包启动报错

### ISSUE THREAD

**Issue by huangkl1** [chat2db/Chat2DB#337]
### Chat2DB Version

2.0.6

### Describe the bug

之前都是使用java -jar 正常启动。这次更新后下载最新版本启动会报错
![QQ截图20230726112216](https://github.com/chat2db/Chat2DB/assets/47739972/08cc42ff-0879-47db-82e6-3339e11a6e99)

**Comment by jipengfei-jpf** [comment]
因为把lib包拆出来了
