### ISSUE TITLE
Bug: 配置openapi总是提示扫描公众号

### ISSUE THREAD

**Issue by wolf27w** [chat2db/Chat2DB#339]
### Chat2DB Version

2.0.6

### Describe the bug

我本地安装，也设置的全局vpn，并且加了openapi的key，总是提示扫描公众号

**Comment by 188140040** [comment]
我也一样

**Comment by 188140040** [comment]
阿里程序员写的代码 到处是bug 也敢发，我真服了

**Comment by vlean** [comment]
这也能5k star，AIGC是真的热了

**Comment by chenxian01** [comment]
Fixed in 2.0.7
