### ISSUE TITLE
Bug:   已配置Chat2DBAI 和 Azure Ai 钧报错unexpected end of stream on http://test.sqlgpt.cn/... 

### ISSUE THREAD

**Issue by tomson5566** [chat2db/Chat2DB#344]
### Chat2DB Version

Current Version:v2.0.6

### Describe the bug

2023-07-26 21:41:13.609 ERROR 1 --- [io-10824-exec-5] a.c.s.s.e.EasyControllerExceptionHandler.164 : 40b8864d-a9ec-4801-9645-9181160c3ad3 | 发生未知异常/api/ai/config/getLoginQrCode:ActionResult(success=false, errorCode=common.systemError, errorMessage=An exception occurs, you can view the exception details in the log in the help menu., errorDetail= 
chat2db-latest  |  com.dtflys.forest.exceptions.ForestRuntimeException: java.io.IOException: unexpected end of stream on http://test.sqlgpt.cn/...
chat2db-latest  |       at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleError(MethodLifeCycleHandler.java:166)
chat2db-latest  |       at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSyncWithException(MethodLifeCycleHandler.java:73)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:217)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:278)
chat2db-latest  |       at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:4706)
chat2db-latest  |       at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1477)
chat2db-latest  |       at com.dtflys.forest.proxy.InterfaceProxyHandler.invoke(InterfaceProxyHandler.java:236)
chat2db-latest  |       at jdk.proxy2/jdk.proxy2.$Proxy107.getLoginQrCode(Unknown Source)
chat2db-latest  |       at ai.chat2db.server.web.api.controller.ai.AiConfigController.getLoginQrCode(AiConfigController.java:51)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
chat2db-latest  |       at ai.chat2db.server.web.api.aspect.ConnectionInfoHandler.connectionInfoHandler(ConnectionInfoHandler.java:51)
chat2db-latest  |       at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
chat2db-latest  |       at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
chat2db-latest  |       at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
chat2db-latest  |       at ai.chat2db.server.web.api.controller.ai.AiConfigController$$SpringCGLIB$$0.getLoginQrCode(<generated>)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
chat2db-latest  |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
chat2db-latest  |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
chat2db-latest  |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
chat2db-latest  |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
chat2db-latest  |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at ai.chat2db.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:37)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
chat2db-latest  |       at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at ai.chat2db.server.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
chat2db-latest  |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
chat2db-latest  |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
chat2db-latest  |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
chat2db-latest  |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
chat2db-latest  |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
chat2db-latest  |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
chat2db-latest  |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
chat2db-latest  |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
chat2db-latest  |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
chat2db-latest  |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
chat2db-latest  |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
chat2db-latest  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
chat2db-latest  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
chat2db-latest  |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
chat2db-latest  |       at java.base/java.lang.Thread.run(Thread.java:833)
chat2db-latest  | Caused by: java.io.IOException: unexpected end of stream on http://test.sqlgpt.cn/...
chat2db-latest  |       at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
chat2db-latest  |       at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
chat2db-latest  |       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
chat2db-latest  |       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:203)
chat2db-latest  |       ... 90 more
chat2db-latest  | Caused by: java.io.EOFException: \n not found: limit=0 content=…
chat2db-latest  |       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
chat2db-latest  |       at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
chat2db-latest  |       at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
chat2db-latest  |       ... 104 more
chat2db-latest  |  
chat2db-latest  |  , solutionLink=https://github.com/chat2db/Chat2DB/wiki/Chat2DB, traceId=null),请求参数:{}
chat2db-latest  | 
chat2db-latest  | com.dtflys.forest.exceptions.ForestRuntimeException: java.io.IOException: unexpected end of stream on http://test.sqlgpt.cn/...
chat2db-latest  |       at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleError(MethodLifeCycleHandler.java:166)
chat2db-latest  |       at com.dtflys.forest.reflection.MethodLifeCycleHandler.handleSyncWithException(MethodLifeCycleHandler.java:73)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:217)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:278)
chat2db-latest  |       at com.dtflys.forest.http.ForestRequest.execute(ForestRequest.java:4706)
chat2db-latest  |       at com.dtflys.forest.reflection.ForestMethod.invoke(ForestMethod.java:1477)
chat2db-latest  |       at com.dtflys.forest.proxy.InterfaceProxyHandler.invoke(InterfaceProxyHandler.java:236)
chat2db-latest  |       at jdk.proxy2/jdk.proxy2.$Proxy107.getLoginQrCode(Unknown Source)
chat2db-latest  |       at ai.chat2db.server.web.api.controller.ai.AiConfigController.getLoginQrCode(AiConfigController.java:51)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
chat2db-latest  |       at ai.chat2db.server.web.api.aspect.ConnectionInfoHandler.connectionInfoHandler(ConnectionInfoHandler.java:51)
chat2db-latest  |       at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
chat2db-latest  |       at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
chat2db-latest  |       at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
chat2db-latest  |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
chat2db-latest  |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
chat2db-latest  |       at ai.chat2db.server.web.api.controller.ai.AiConfigController$$SpringCGLIB$$0.getLoginQrCode(<generated>)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chat2db-latest  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
chat2db-latest  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chat2db-latest  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
chat2db-latest  |       at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
chat2db-latest  |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
chat2db-latest  |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
chat2db-latest  |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
chat2db-latest  |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
chat2db-latest  |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
chat2db-latest  |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
chat2db-latest  |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at ai.chat2db.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:37)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
chat2db-latest  |       at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at ai.chat2db.server.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
chat2db-latest  |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
chat2db-latest  |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
chat2db-latest  |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
chat2db-latest  |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
chat2db-latest  |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
chat2db-latest  |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
chat2db-latest  |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
chat2db-latest  |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
chat2db-latest  |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
chat2db-latest  |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
chat2db-latest  |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
chat2db-latest  |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
chat2db-latest  |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
chat2db-latest  |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
chat2db-latest  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
chat2db-latest  |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
chat2db-latest  |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
chat2db-latest  |       at java.base/java.lang.Thread.run(Thread.java:833)
chat2db-latest  | Caused by: java.io.IOException: unexpected end of stream on http://test.sqlgpt.cn/...
chat2db-latest  |       at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
chat2db-latest  |       at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
chat2db-latest  |       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
chat2db-latest  |       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
chat2db-latest  |       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
chat2db-latest  |       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
chat2db-latest  |       at com.dtflys.forest.backend.okhttp3.executor.OkHttp3Executor.execute(OkHttp3Executor.java:203)
chat2db-latest  |       ... 90 common frames omitted
chat2db-latest  | Caused by: java.io.EOFException: \n not found: limit=0 content=…
chat2db-latest  |       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
chat2db-latest  |       at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
chat2db-latest  |       at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
chat2db-latest  |       ... 104 common frames omitted

**Comment by chenxian01** [comment]
Fixed in 2.0.7

**Comment by tomson5566** [comment]
I text in 2.09 , has been fixed。  goog job !
