### ISSUE TITLE
Bug: 配置openAi key之后无法使用执行返回  unexpected end of stream on http://test.sqlgpt.cn/...

### ISSUE THREAD

**Issue by Swordsman007** [chat2db/Chat2DB#346]
### Chat2DB Version

2.0.6

### Describe the bug

1：后台配置了自己的openApi key，点击查询报错，再看后台配置的api-key被改变。hosts地址变成了http://test.sqlgpt.cn
2：而且剩余次数变成0，需要重新关注公众号

![image](https://github.com/chat2db/Chat2DB/assets/36924421/f1d45392-c14f-410d-831b-ad19394baa8f)

**Comment by 188140040** [comment]
开始割韭菜

**Comment by chenxian01** [comment]
fixed in 2.0.7
