### ISSUE TITLE
Bug: 配置了openai key 也提示扫公众，阿里程序员真的是这种Bug也敢发推送上线，我真佩服

### ISSUE THREAD

**Issue by 188140040** [chat2db/Chat2DB#349]
### Chat2DB Version

2.0.6

### Describe the bug

配置了openai key 也提示扫公众，阿里程序员真的是这种Bug也敢发推送上线，我真佩服.

**Comment by shanhexi** [comment]
完全业余时间开发，希望理解 周末修复

**Comment by kesai110** [comment]
> ### Chat2DB Version
> 2.0.6
> 
> ### Describe the bug
> 配置了openai key 也提示扫公众，阿里程序员真的是这种Bug也敢发推送上线，我真佩服.

哟哟哟，谁给你的勇气啊，你为社区做了啥贡献？你丫一个调库狗也好意思说别人，老纸一拳打你小肚子上。人家范点儿小错咋了？你有本事自己去写SQL啊，滚吧你~死辣鸡~
