### ISSUE TITLE
建议: 有没有数据结构对比的功能啊？

### ISSUE THREAD

**Issue by apple1563** [chat2db/Chat2DB#351]
想对比两张表，然后同步

**Comment by chenxian01** [comment]
Not planned at this time. You can use third tool as alternative solution.

**Comment by LuckLin520** [comment]
> Not planned at this time. You can use third tool as alternative solution.
如果不支持这个功能的话这个产品走不远，毕竟实际开发中结构对比同步，数据迁移才是最实用的，而AI现在烂大街，不稀罕
