### ISSUE TITLE
Bug: [mysql] Create Table Exception

### ISSUE THREAD

**Issue by liugddx** [chat2db/Chat2DB#36]
### Chat2DB Version

main

### Describe the bug

When I am creating the table the prompt looks like this.

<img width="1365" alt="image" src="https://github.com/chat2db/Chat2DB/assets/48236177/c2c0ab0b-a3ca-4284-a1e3-73b037743dab">

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.
