### ISSUE TITLE
Bug: 打开报错：

### ISSUE THREAD

**Issue by sunshe35** [chat2db/Chat2DB#368]
### Chat2DB Version

2.07

### Describe the bug

打开没有响应，卡死状态。报错日志如下：

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 10824 was already in use.

Action:

Identify and stop the process that's listening on port 10824 or configure this application to listen on another port.

2023-07-31 11:10:28.951  INFO 22416 --- [Thread-2] a.c.s.start.config.util.SystemUtils     .28 :  | 开始退出系统应用

**Comment by sunshe35** [comment]
补充：
打开chat2DB后端口情况：
(base) PS C:\Users\sunshe35> NETSTAT.EXE -ant | findstr.exe 10824
  TCP    127.0.0.1:45549        127.0.0.1:10824        SYN_SENT        InHost
  TCP    127.0.0.1:45550        127.0.0.1:10824        SYN_SENT        InHost

关闭chat2DB后端口情况
(base) PS C:\Users\sunshe35> NETSTAT.EXE -ant | findstr.exe 10824
(base) PS C:\Users\sunshe35>

**Comment by chenxian01** [comment]
The prompt is clear "Port 10824 was already in use".  Kill the process which use 10824 and restart the client.
