### ISSUE TITLE
Bug: 无法使用自定义AI

### ISSUE THREAD

**Issue by H9990HH969** [chat2db/Chat2DB#373]
### Chat2DB Version

v2.0.6 windows版本

### Describe the bug

设置了自定义AI，但是使用aigc的时候，还是会跳出二维码，并没有去访问我的接口
![1690793346408](https://github.com/chat2db/Chat2DB/assets/133352113/895d1362-3ce4-4a2c-9ff8-b727c41a3287)

![1690793458927](https://github.com/chat2db/Chat2DB/assets/133352113/df7ae77f-609d-448a-8f5e-ea3ed3bd007d)

**Comment by shanhexi** [comment]
升级2.0.7
