### ISSUE TITLE
优化: 官方网站里在api和常见问题中对于ExcelIgnoreUnannotated表述不一

### ISSUE THREAD

**Issue by YIYOIY** [chat2db/Chat2DB#374]
Api
ExcelIgnoreUnannotated
默认不加ExcelProperty 的注解的都会参与读写，加了不会参与读写
常见问题
升级了还有，在类的最上面加入@ExcelIgnoreUnannotated注解，加入这个注解后只有加了@ExcelProperty才会参与读写。

**Comment by robinji0** [comment]
Easy excel is not from this project.
