### ISSUE TITLE
Bug: 官网windows安装包无法下载

### ISSUE THREAD

**Issue by PoemAndDistant** [chat2db/Chat2DB#375]
### Chat2DB Version

2.0.7

### Describe the bug

官网windows下载地址中，字符编码后为 20%；点击链接无法直接下载，需要手动复制修改后才能下载对应的exe文件，
![image](https://github.com/chat2db/Chat2DB/assets/37179147/aacdfa24-33da-4b71-8777-f430d0126ab2)

**Comment by fanjinyu-fjy** [comment]
已修复
