### ISSUE TITLE
建议:  可以新增以下部分功能

### ISSUE THREAD

**Issue by xhyym** [chat2db/Chat2DB#378]
1、不知道其他开发者平时对DB软件的使用习惯，希望在表名的右侧增加表的注释（如果表有注释的话）
<img width="352" alt="image" src="https://github.com/chat2db/Chat2DB/assets/59786372/c05a1972-c283-4b63-9196-725241e93269">
并且在表名的左侧增加下拉按钮，展示对应列，索引等信息（参考市面上大多数的界面布局，比如datagrip，Navicat，DBeaver等）
2、目前需要查看表的DDL只能通过右键导出的形式，不知道大佬能否直接做个快捷键或者直接在表名右键显示DDL
3、针对单表查询的字段，鼠标放在查询结果上，可以展示对应注释字段（datagrip上的功能）
4、有时候返回的结果，会出现科学计数法
<img width="462" alt="image" src="https://github.com/chat2db/Chat2DB/assets/59786372/f0cf95b4-d23c-4606-bcc1-e28474d3cd7f">
5、对where条件后的列貌似也不是很友好
<img width="767" alt="image" src="https://github.com/chat2db/Chat2DB/assets/59786372/92815f97-0648-4533-8ef4-46adc3ddee72">
无法提示出输入的列。
6、界面没看见哪儿可以执行SQL脚本，如果想外部执行SQL脚本的话只能复制到控制台上面去执行了。
以上是对目前版本的一点拙见，望参考，谢谢大佬。

**Comment by zhuangjiaju** [comment]
这些在规划中了，
其中 科学计数法我这里无法复现，情况下 你是 2.0.7版本么？ 如果是的化 可以提供下 数据库名字+建表的这个字段语句+存储的内容么？

**Comment by xhyym** [comment]
版本：2.0.7
提供一下建表SQL：-- auto-generated definition
create table base_ptype
(
    id                       bigint unsigned default 0                    not null comment '商品ID'
        primary key,
    profile_id               bigint unsigned default 0                    not null comment '帐套ID',
    typeid                   varchar(25)     default ''                   not null comment '层级ID',
    partypeid                varchar(25)     default ''                   not null comment '父类层级ID',
    usercode                 varchar(100)    default ''                   not null comment '商品编号',
    fullname                 varchar(200)    default ''                   not null comment '商品全名',
    shortname                varchar(200)    default ''                   not null comment '商品简名',
    namepy                   varchar(30)     default ''                   not null comment '拼音码',
    classed                  tinyint(1)      default 0                    not null comment '分类标记',
    stoped                   tinyint(1)      default 0                    not null comment '是否停用',
    deleted                  tinyint(1)      default 0                    not null comment '是否已删除',
    rowindex                 bigint unsigned default 0                    not null comment '排序',
    barcode                  varchar(100)    default ''                   not null comment '商品条码(用于批量生成fullbarcode)',
    standard                 varchar(120)    default ''                   not null comment '商品规格',
    ptype_type               varchar(120)    default ''                   not null comment '商品型号',
    ptype_area               varchar(30)     default ''                   not null comment '商品产地',
    memo                     varchar(300)    default ''                   not null comment '备注',
    create_type              int(10)         default 0                    not null comment '创建类型:0-手工,1-下载,2-平台下载,3-导入',
    cost_mode                tinyint(2)      default 0                    not null comment '成本算法：0-全月加权平均,1-个别计价,2-移动加权平均',
    pcategory                tinyint(2)      default 0                    not null comment '商品类型：0-实物商品，1-虚拟商品, 2-套餐商品',
    tax_number               varchar(32)     default ''                   not null comment '税收编码',
    tax_rate                 decimal(22, 8)  default 0.00000000           not null comment '税率',
    cost_price               decimal(22, 8)  default 0.00000000           not null comment '参考成本价',
    brand_id                 bigint unsigned default 0                    not null comment '品牌id',
    ktype_limit              tinyint(1)      default 0                    not null comment '是否限制仓库（0全部仓库可见  1部分仓库可见）',
    snenabled                int(10)         default 0                    not null comment '序列号管理:0=未启用，1=严格管理，2=宽松管理',
    propenabled              tinyint(1)      default 0                    not null comment '是否启用属性管理',
    batchenabled             tinyint(1)      default 0                    not null comment '是否开启批次管理',
    protect_days             int(10)         default 0                    not null comment '保质期天数(天):0不启用保质期 大于1启用',
    protect_days_unit        tinyint(2)      default 0                    not null comment '保质期表示方式:0天 1周 2月 3年',
    protect_warndays         int(10)         default 0                    not null comment '报警天数(天)',
    protect_warndays_unit    tinyint(2)      default 0                    not null comment '报警天数表示方式:0天 1周 2月 3年',
    weight                   decimal(22, 8)  default 0.00000000           not null comment '单位商品重量',
    weight_unit              tinyint(2)      default 1                    not null comment '重量单位:0-g,1-kg',
    retail_default_unit      bigint unsigned default 0                    not null comment '零售类单据默认单位',
    sale_default_unit        bigint unsigned default 0                    not null comment '销售类单据默认单位',
    buy_default_unit         bigint unsigned default 0                    not null comment '进货类单据默认单位',
    stock_default_unit       bigint unsigned default 0                    not null comment '库存类单据默认单位',
    ptype_length             decimal(22, 8)  default 0.00000000           not null comment '长',
    ptype_width              decimal(22, 8)  default 0.00000000           not null comment '宽',
    ptype_height             decimal(22, 8)  default 0.00000000           not null comment '高',
    length_unit              tinyint(2)      default 1                    not null comment '长度单位(0=厘米,1=米)',
    create_time              timestamp(3)    default CURRENT_TIMESTAMP(3) not null comment '创建时间',
    update_time              timestamp(3)    default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '修改时间',
    sku_price                tinyint(2)      default 0                    not null comment 'SKU价格管理 0未启用 1启用',
    propvalues_descart_count int(10)         default 0                    not null comment '属性组合笛卡尔数量',
    fullbarcode_rule_id      bigint unsigned default 0                    not null comment '条码策略id',
    sub_unit                 varchar(8)      default ''                   not null comment '副单位名称',
    share_type               tinyint(2)      default 0                    not null comment '分摊类型 0一次性  1按时间',
    invoice_fullname         varchar(200)    default ''                   not null comment '开票名称',
    preparation_type         tinyint(2)      default 0                    not null comment '备货类型 0安全库存备货 1销售趋势备货 2先销后采备货',
    industry_category        tinyint(2)      default 0                    not null comment '行业类目（0默认 1手机）',
    audit_state              tinyint(2)      default 0                    not null comment '商品审核状态（0待审核 1已审核 2审核不通过）',
    buy_days                 int(10)         default 0                    not null comment '采购周期（天）',
    constraint IX_profileid_typeid
        unique (profile_id, typeid)
)
    comment '商品信息';

create index IX_profi_pcate_class
    on base_ptype (profile_id, pcategory, classed);

create index IX_profi_rowin
    on base_ptype (profile_id, rowindex);

create index IX_profileid_costmode
    on base_ptype (profile_id, cost_mode);

create index IX_profileid_partypeid
    on base_ptype (profile_id, partypeid);

create index proflie_code_pcat
    on base_ptype (profile_id, usercode(20), pcategory);

出现科学计数法的列：
![image](https://github.com/chat2db/Chat2DB/assets/59786372/95dbe3e0-6d0d-4b63-931c-07b36ce04483)
看样子是decimal类型导致的问题。为0的时候显示了默认的8位科学计数法

**Comment by xhyym** [comment]
、作伴
***@***.***




issue上已经备注了，谢谢大佬。



                       
原始邮件
                       
                     

发件人："Jiaju Zhuang"< ***@***.*** &gt;;

发件时间：2023/8/2 19:28

收件人："chat2db/Chat2DB"< ***@***.*** &gt;;

抄送人："xhyym"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [chat2db/Chat2DB] 建议:  可以新增以下部分功能 (Issue #378)




 
这些在规划中了，
 其中 科学计数法我这里无法复现，情况下 你是 2.0.7版本么？ 如果是的化 可以提供下 数据库名字+建表的这个字段语句+存储的内容么？

**Comment by shanhexi** [comment]
大部分已经优化，3.0.0 已经修复
