### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ryze-T** [chat2db/Chat2DB#380]
### Chat2DB Version

2.0.7

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/76553352/2e236543-1e09-4a14-8832-b922551a14f5)

**Comment by shanhexi** [comment]
之前下载过吧，
这个应该是 之前的版本关闭应用时有bug 导致进程没杀掉，
解决办法：
lsof -i tcp:10824 查到进程号
kill -9 进程号，
之后再重启就好了
