### ISSUE TITLE
Bug: 图示比重占比不准确

### ISSUE THREAD

**Issue by hm0223** [chat2db/Chat2DB#385]
### Chat2DB Version

Mac intel v2.0.2 

### Describe the bug

<img width="1420" alt="image" src="https://github.com/chat2db/Chat2DB/assets/85843425/480db4f0-a8a0-4b52-ac11-e7516441a138">
比重问题

**Comment by fanjinyu-fjy** [comment]
<img width="375" alt="image" src="https://github.com/chat2db/Chat2DB/assets/7688101/4b821a7e-bb73-4b7c-9d0d-42a642726e8b">

这里的是图例，鼠标hover上去有具体数据
