### ISSUE TITLE
Bug: 闪退bug（包括浏览器场景）

### ISSUE THREAD

**Issue by acanyo** [chat2db/Chat2DB#39]
### Chat2DB Version

1.0.10

### Describe the bug

Describe the bug
BUG：使用闪退，浏览器场景直接关闭我的浏览器！很严重
优化：不支持 视图 存储过程 包 序列等功能 我现在使用的场景是Oracle，希望database支持搜索

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version. Your suggestions are well received, will plan in future.
