### ISSUE TITLE
Bug: 搜索表之后右键三个点导出报错

### ISSUE THREAD

**Issue by xhyym** [chat2db/Chat2DB#393]
### Chat2DB Version

2.0.7

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/59786372/3cfb70a4-7bf2-4058-b732-90deaffa48cd)
看样子是搜索之后选择导出，无法找到数据表的源导致提示不存在了。

**Comment by shanhexi** [comment]
最新版已解决
