### ISSUE TITLE
Bug:Add with syntax of ClickHouse.

### ISSUE THREAD

**Issue by RiwenY** [chat2db/Chat2DB#414]
### Chat2DB Version

2.0.10

### Describe the bug

Connect ClickHouse to the console to execute sql with as, which cannot be executed. If there is an error, please add with syntax support.

Error screenshot
![image](https://github.com/chat2db/Chat2DB/assets/141597788/8f9952e2-95f2-407d-a358-e19783bb7b87)

**Comment by miahemu** [comment]
new version has solved this problem
<img width="1195" alt="image" src="https://github.com/chat2db/Chat2DB/assets/157001655/3e6ab227-0eaf-4928-b185-c621301683e8">
