### ISSUE TITLE
Bug: 表提示自动生成`表名`

### ISSUE THREAD

**Issue by aliqiu** [chat2db/Chat2DB#415]
### Chat2DB Version

v2.0.10 build20230807024422

### Describe the bug

直接执行会报错
![Snipaste_2023-08-07_15-05-59](https://github.com/chat2db/Chat2DB/assets/57788488/0352a8d6-0770-4c52-b0a2-5ea76febf6ab)

**Comment by robinji0** [comment]
I don't quite get your question. Please provide more error log details.

**Comment by robinji0** [comment]
close since no update
