### ISSUE TITLE
Bug: 格式化SQL失败

### ISSUE THREAD

**Issue by xhyym** [chat2db/Chat2DB#421]
### Chat2DB Version

2.0.10

### Describe the bug

<img width="1228" alt="image" src="https://github.com/chat2db/Chat2DB/assets/59786372/a9c266c7-c353-4997-a720-369368d9ddac">
无论是选中SQL还是全选SQL都无法格式化；建表SQL如下：
CREATE TABLE `sys_profile_model` (
  `id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '主键',
  `profile_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '账套ID',
  `model_key` varchar(55) NOT NULL DEFAULT '' COMMENT '资产key(英文名)',
  `model_code` int(10) NOT NULL DEFAULT '0' COMMENT '资产code',
  `model_name` varchar(155) NOT NULL DEFAULT '' COMMENT '资产名称',
  `free_enable` smallint(5) NOT NULL DEFAULT '0' COMMENT '是否免费（0收费，1免费，2限时免费，默认0）',
  `config_enable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '客户配置是否可见',
  `buyed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否购买',
  `model_status` smallint(5) NOT NULL DEFAULT '0' COMMENT '开启状态（0全关，1全开，2单量限制，3时间限制）',
  `trial_qty` int(10) NOT NULL DEFAULT '0' COMMENT '数量（如单据数量）',
  `trial_expiredate` date NOT NULL DEFAULT '0001-01-01' COMMENT '试用到期时间',
  `trial_times` int(10) NOT NULL DEFAULT '0' COMMENT '已试用次数',
  `trial_type` smallint(5) NOT NULL DEFAULT '0' COMMENT '试用类型（0不试用，1按时限试用，2按单量试用）',
  `saleqty_enable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '存货点是否算可销售库存',
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UN_profi_code` (`profile_id`,`model_code`),
  UNIQUE KEY `UN_profi_key` (`profile_id`,`model_key`(20)),
  KEY `IX_profi_status` (`profile_id`,`model_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产模块表'

**Comment by shanhexi** [comment]
2.0.12已修复
