### ISSUE TITLE
建议: 是否考虑增加控制访问权限的功能

### ISSUE THREAD

**Issue by Kagenui-yozuru** [chat2db/Chat2DB#426]
我认为能在web端访问是Chat2DB的优点之一。
但是本身没有提供任何用户认证的功能，且服务端是有状态的。
这样的话系统部署在公网环境下就等于在带着数据库裸奔。
希望可以增加一个简易的安全模块（类似Nacos的那种）

**Comment by SwallowGG** [comment]
已经在开发中
