### ISSUE TITLE
Bug: 使用系统自动提示的表名，执行报错

### ISSUE THREAD

**Issue by Johan-He** [chat2db/Chat2DB#431]
### Chat2DB Version

2.0.11

### Describe the bug

![微信图片_20230809153308](https://github.com/chat2db/Chat2DB/assets/141814904/d7e8936b-7481-4841-a1ba-a2bc8752fbc9)
我是Oracle数据库，查询一个表时，系统自动弹出的表名自带单引号，但是执行的时候，软件报错“无效字符”，需要删除系统提供的单引号才可以正常执行，如果单引号是错误的，软件为什么要自动加上单引号？

**Comment by shanhexi** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/86969353/559497c5-2388-4e4d-8ea3-9e9d393b9211)
我们暂时无法复现，帮忙打开控制台点击刷新，看看这里的表名是否是正确的，

**Comment by Johan-He** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/141814904/72ac3df9-97cd-4d66-8ef4-e59bf57a30b9)
![image](https://github.com/chat2db/Chat2DB/assets/141814904/eed2f7ac-485c-4da7-82c9-593657aacbda)

**Comment by SwallowGG** [comment]
2.0.13修复了
