### ISSUE TITLE
Bug: 新建oracle数据库连接报错

### ISSUE THREAD

**Issue by Johan-He** [chat2db/Chat2DB#432]
### Chat2DB Version

2.0.11

### Describe the bug

![无标题](https://github.com/chat2db/Chat2DB/assets/141814904/bb88abd7-4958-4a8f-b637-b0fe3532be66)

新建oracle数据库连接，系统自动给出的是URL是端口:SID，点击测试连接报错，需要把冒号改成斜杆才能正常测试通过

**Comment by SwallowGG** [comment]
3.0.11已经修复
