### ISSUE TITLE
优化: 我建议现在不是我要修改一个表里面的字段还要执行sql 语句来修改 可以在页面上进行修改然后保存这样方便

### ISSUE THREAD

**Issue by itveteran9** [chat2db/Chat2DB#437]
我建议现在不是，我要修改一个表里面的字段，或者一个字段里面的内容，还要执行sql 语句来修改 ，我觉得可以在页面上可以进行修改然后保存这样方便
用户想用那种改都可以

**Comment by robinji0** [comment]
duplicate with #404
