### ISSUE TITLE
Bug: Chat2DB 2.0.10版本打开日志，用户名以及密码会以明文形式保存在application.log文件中

### ISSUE THREAD

**Issue by cnwangk** [chat2db/Chat2DB#438]
### Chat2DB Version

2.0.10

### Describe the bug

平台：Windows 11 22621.1992

当前版本：Chat2DB v2.0.10 build20230807024422 
当前环境：desktop

DBMS：MySQL 8.0.33

bug：Chat2DB v2.0.10 版本打开日志，发现用户名以及密码会以明文形式保存在 application.log 文件中，其中包含软件自带的示例数据库demo。

疑问：本身这样设计？还是设计漏洞？

期望：将密码保存在本地权限交给用户，以选着形式选择是否保存在本地。

**Comment by robinji0** [comment]
fixed in 2.0.12
