### ISSUE TITLE
The tables are empty.

### ISSUE THREAD

**Issue by zhangyongquan88** [chat2db/Chat2DB#439]
我连接远程数据库成功了，库里面没有表信息，是个空库，是什么原因呢，另外，日志里面我的用户名和密码是明文的，很容易泄露啊，

**Comment by SliverYuki** [comment]
同样的问题，但另一个库连接正常

**Comment by robinji0** [comment]
switch database here to find the corresponding tables.
![image](https://github.com/chat2db/Chat2DB/assets/137188352/1e1a311c-d440-47ff-b790-a3ddcd41e604)
