### ISSUE TITLE
优化: DM数据库长文本TEXT字段内容无法查看

### ISSUE THREAD

**Issue by SwagDYoung** [chat2db/Chat2DB#440]
![image](https://github.com/chat2db/Chat2DB/assets/87689570/3d97df38-0998-4e3d-bd89-94c53f16fac9)
![image](https://github.com/chat2db/Chat2DB/assets/87689570/52809e9b-6c8a-41c6-a178-7f2e418570b0)
![image](https://github.com/chat2db/Chat2DB/assets/87689570/9a8bd0e0-4481-4236-8605-a79386163eff)
在DM管理工具中可以看到Text数据类型内容，而chat2DB中无法查看TEXT数据类型内容

**Comment by SwallowGG** [comment]
2.0.13已修复
