### ISSUE TITLE
Bug: 在系统默认的dashboard里，运行默认的sql，会导致查询不出，一直在转圈，无法操作

### ISSUE THREAD

**Issue by lzy1122** [chat2db/Chat2DB#441]
### Chat2DB Version

2.0.11

### Describe the bug

![6d5c12e115b5a22e113b4efc0d43ecf](https://github.com/chat2db/Chat2DB/assets/78611195/e884dbc3-2aab-4291-847c-b7686e7a283f)

**Comment by robinji0** [comment]
Please check if your network can connect to the demo database. If it's ok, please provide more log details.

**Comment by robinji0** [comment]
close since no update
