### ISSUE TITLE
Bug: common.systemError

### ISSUE THREAD

**Issue by moxixuan** [chat2db/Chat2DB#449]
### Chat2DB Version

v2.0.11

### Describe the bug

{"getApplicationMessage":{"env":"desktop","versions":"2.0.11","buildTime":1691489139135,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) chat2db/2.0.11 Chrome/108.0.5359.215 Electron/22.3.18 Safari/537.36"},"requestUrl":"http://127.0.0.1:10824/api/connection/datasource/create","requestParams":"{\"ssh\":{\"use\":false,\"hostName\":\"\",\"port\":\"22\",\"userName\":\"\",\"localPort\":\"\",\"authenticationType\":\"password\",\"password\":\"\"},\"driverConfig\":{},\"alias\":\"nrop_test\",\"host\":\"home.mworkspace.cn\",\"port\":\"33306\",\"authenticationType\":\"1\",\"user\":\"nrop_user\",\"password\":\"\",\"database\":\"acme_nrop\",\"url\":\"jdbc:mysql://home.mworkspace.cn:33306/acme_nrop\",\"extendInfo\":[{\"key\":\"zeroDateTimeBehavior\",\"value\":\"convertToNull\"}],\"connectionEnvType\":\"DAILY\",\"type\":\"MYSQL\"}","errorCode":"common.systemError","errorMessage":"An exception occurs, you can view the exception details in the log in the help menu.","errorDetail":"java.lang.NullPointerException\n","solutionLink":"https://github.com/chat2db/Chat2DB/wiki/Chat2DB"}

![图片](https://github.com/chat2db/Chat2DB/assets/19483437/7057b403-4358-41ff-a1c4-2732d11e5094)

![图片](https://github.com/chat2db/Chat2DB/assets/19483437/303a516f-4c13-4fd0-aa54-6299b49fbc0d)

**Comment by SwallowGG** [comment]
2.0.13已经修复
