### ISSUE TITLE
Optimization: Configure the database connection, and after entering the password, it is recommended to set it not to be displayed in clear text.

### ISSUE THREAD

**Issue by RiwenY** [chat2db/Chat2DB#454]
After configuring the database connection and entering the password, a button to hide the password is currently configured. From the security point of view, it is recommended to set it not to be displayed in plain text to avoid password disclosure.
![image](https://github.com/chat2db/Chat2DB/assets/141597788/38568fe9-f171-4aaa-ad72-fb4042a08087)

**Comment by miahemu** [comment]
We adopted the option of not displaying passwords in new version
