### ISSUE TITLE
优化: 在控制台输入自然语言后，生成的SQL语句前，建议附加上提示语

### ISSUE THREAD

**Issue by RiwenY** [chat2db/Chat2DB#455]
在控制台输入自然语言后，生成的SQL语句前，建议附加上提示语

![image](https://github.com/chat2db/Chat2DB/assets/141597788/17699d91-60ec-43f8-b384-d56f33dac2b3)

**Comment by robinji0** [comment]
since it will impact the accuracy of prompt, mark this as won't fix for now.
