### ISSUE TITLE
Bug: 创建Redis打不开页面，显示空白

### ISSUE THREAD

**Issue by li-junpeng** [chat2db/Chat2DB#458]
### Chat2DB Version

v2.0.12

### Describe the bug

刚升级到了v2.0.12版本，创建Redis、MongoDB时出现空白页面。打开控制台报错如下：

![image](https://github.com/chat2db/Chat2DB/assets/107396800/1fb2da3b-d748-480f-982a-4d9e91ac83b7)

日志里面没有发现error

**Comment by shanhexi** [comment]
暂不支持非关系型数据库，九月之后会陆续支持，
这个白屏问题周末修一下
