### ISSUE TITLE
无法动态刷新schema

### ISSUE THREAD

**Issue by qtvbwfn** [chat2db/Chat2DB#459]
### Chat2DB Version

2.0.12

### Describe the bug

见截图，数据库连接默认配置的数据库是sc,通过导航栏切换到其他数据库，执行查询语句时，无法动态切换schema，导致SQL查询异常

![image](https://github.com/chat2db/Chat2DB/assets/5848026/ef74223c-f65a-4c59-9bc3-1757c96143fe)

**Comment by robinji0** [comment]
From the screenshot, there is no table sc_device_attribute. If you switch database successfully, you should see all the table on the left panel while there is no such table named sc_device_attribute. Please make sure you switch database successfully.

**Comment by shanhexi** [comment]
下载最新版本，已修复
