### ISSUE TITLE
建议: 建议添加查询结果导出Excel功能和Excel导入功能

### ISSUE THREAD

**Issue by houfeibin** [chat2db/Chat2DB#46]

**Comment by robinji0** [comment]
Supported in 2.0.9.

**Comment by czxin788** [comment]
我用的Chat2DB版本是3.0.12，还是没有导出excel功能，只有导出csv功能。

![image](https://github.com/chat2db/Chat2DB/assets/13861904/b5f127a1-f3d1-478a-80b5-f2698eeffe00)
