### ISSUE TITLE
mac m1无法使用redis、mongodb，点击直接白屏无显示。

### ISSUE THREAD

**Issue by 18514098548** [chat2db/Chat2DB#463]
### Chat2DB Version

https://oss.sqlgpt.cn/release/2.0.12/Chat2DB-2.0.12-arm64.dmg

### Describe the bug

<img width="1370" alt="WeChat2fb539ff32dabd60fd559f5a3ac4b238" src="https://github.com/chat2db/Chat2DB/assets/51153374/7e7182e4-0c7c-4714-9d7b-18583937780e">

**Comment by shanhexi** [comment]
暂不支持非关系型数据库，九月之后会陆续支持，
这个白屏问题周末修一下
