### ISSUE TITLE
建议: 保存的记录可以自定义名称

### ISSUE THREAD

**Issue by LeWinCheng** [chat2db/Chat2DB#465]
目前 new console 之后，名称都是固定的，无法修改；影响使用体验，建议优化

**Comment by shanhexi** [comment]
这个console打开的时候双击tab 可以修改名称的，
后续再加保存以后可以修改名称吧

**Comment by LeWinCheng** [comment]
> 这个console打开的时候双击tab 可以修改名称的， 后续再加保存以后可以修改名称吧

之前未曾发现，感谢提示
