### ISSUE TITLE
建议: database切换可以增加筛选

### ISSUE THREAD

**Issue by zengdecai** [chat2db/Chat2DB#466]
可能是小众需求，现在我这边mysql数据库实例中的database数量超过400，个人维护和开发项目需要在这400个database中来回的切换，下拉选择很难定位到自己需要切换的database，希望可以输入关键字进行筛选
![image](https://github.com/chat2db/Chat2DB/assets/48974979/d14f0bc8-98dc-4990-bb08-33b5f0b98ac3)

**Comment by shanhexi** [comment]
get下周的13版本会支持

**Comment by shanhexi** [comment]
已支持
