### ISSUE TITLE
Bug: oracle数据库连接，只能用SID连接，无法用服务名连接

### ISSUE THREAD

**Issue by Vergange** [chat2db/Chat2DB#469]
### Chat2DB Version

v2.0.12

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/92494136/a102d90b-d353-41e8-9b4c-78f9800ac0d6)
这里只提供了SID连接方式，如果没有用服务名连接的地方吗？就不能跟nivcat一样，整一个选择框吗？
![image](https://github.com/chat2db/Chat2DB/assets/92494136/99a0ee84-ff3b-4382-8a93-a3fedb0514b9)

**Comment by xkyang1** [comment]
最新版本，mac同样的环境，连接oracle ，navicat 成功，chat2db 失败；

**Comment by shanhexi** [comment]
2023-11-10的 3.0.11版本已支持服务名连接，
