### ISSUE TITLE
Bug: 新建数据库连接拒绝访问，Access denied for user，这个报错的ip和连接的ip不一样

### ISSUE THREAD

**Issue by chan225-netizen** [chat2db/Chat2DB#474]
### Chat2DB Version

2.0.12

### Describe the bug

新建数据库连接拒绝访问，账号密码是对的
Error
Access denied for user 'ulearningdb'@'*.*.*.*' (using password: YES)（*.*.*.*为ip地址，并且这个报错的ip和连接的ip不一样）
麻烦帮忙看一下

**Comment by chan225-netizen** [comment]
1

**Comment by SwallowGG** [comment]
什么数据库？IP不一样有什么规律吗？

**Comment by SwallowGG** [comment]
麻烦加一下微信或者钉钉吧，微信 yxccw132

**Comment by robinji0** [comment]
close since not update for a long time.
