### ISSUE TITLE
Bug: run debug error

### ISSUE THREAD

**Issue by lpxiangyan9** [chat2db/Chat2DB#477]
### Chat2DB Version

main

### Describe the bug

PS F:\workspaces\Chat2DB\chat2db-server\chat2db-server-start> java -version
openjdk version "17.0.8" 2023-07-18 LTS
OpenJDK Runtime Environment Microsoft-8035246 (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Microsoft-8035246 (build 17.0.8+7-LTS, mixed mode, sharing)
PS F:\workspaces\Chat2DB\chat2db-server\chat2db-server-start> mvn -v
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: F:\tools\apache-maven-3.8.8
Java version: 17.0.8, vendor: Microsoft, runtime: D:\Program Files\Microsoft\jdk-17.0.8.7-hotspot
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
PS F:\workspaces\Chat2DB\chat2db-server\chat2db-server-start> 

错误: 找不到或无法加载主类 .path=..lib
原因: java.lang.ClassNotFoundException: /path=//lib

**Comment by robinji0** [comment]
It's a problem for your editor. Please google search the solution.
