### ISSUE TITLE
Bug: clickhouse查询异常

### ISSUE THREAD

**Issue by X-rapido** [chat2db/Chat2DB#480]
### Chat2DB Version

v2.0.12

### Describe the bug

chat2db查询sql异常，chat2db 驱动 clickhouse-jdbc-0.3.2、clickhouse 版本 22.2.3.1

![image](https://github.com/chat2db/Chat2DB/assets/9986850/f761638d-1115-4e81-a542-64c8469b16b7)
![image](https://github.com/chat2db/Chat2DB/assets/9986850/350f1f09-8eb6-413c-9584-a8989432ebd5)

同样sql在datagrip和dbever查询正常，chat2db更换驱动 clickhouse-jdbc-0.4.2 查询出现lz4异常
![image](https://github.com/chat2db/Chat2DB/assets/9986850/bcb73e4b-5acd-4537-8076-afe828cd45e3)

**Comment by robinji0** [comment]
move to #407
