### ISSUE TITLE
Bug: 内网部署后，在无互联网的环境下无法正常使用。添加数据库连接报错。

### ISSUE THREAD

**Issue by lonsel** [chat2db/Chat2DB#481]
### Chat2DB Version

2.0.11

### Describe the bug

<img width="1499" alt="image" src="https://github.com/chat2db/Chat2DB/assets/6881365/2164cfbb-3c22-4b02-ae38-d53e16e45fed">

**Comment by SwallowGG** [comment]
无法联网的情况需要手动下载驱动
