### ISSUE TITLE
建议: 建议支持一下国产的AI

### ISSUE THREAD

**Issue by skjanyou** [chat2db/Chat2DB#488]
白嫖党强烈建议能够支持一下国产AI，毕竟OpenAi的token需要钱，而国内的AI目前还不要钱。

**Comment by robinji0** [comment]
Please provide the specific llm name which is open and free, we will follow up.

**Comment by Solo8World** [comment]
额 国内的ai现在有哪个能生成准确的sql，支持也是鸡肋
