### ISSUE TITLE
Bug: 没有mongo数据库连接

### ISSUE THREAD

**Issue by charming-cc** [chat2db/Chat2DB#490]
### Chat2DB Version

2.0.13

### Describe the bug

<img width="999" alt="image" src="https://github.com/chat2db/Chat2DB/assets/73381532/6026aad0-949c-4184-b23a-0424f226abd9">
没有mongo数据库连接，mac arm版

**Comment by hiccuplp** [comment]
mongodb的连接以及text2mongodb查询语句，应该算新需求了吧？

**Comment by robinji0** [comment]
move to #407
