### ISSUE TITLE
Bug: Windows11 版本无Redis和MongoDB连接模板，客户端出现图标显示半截

### ISSUE THREAD

**Issue by cnwangk** [chat2db/Chat2DB#493]
### Chat2DB Version

2.0.13

### Describe the bug

Windows 11 版本无 Redis 和 MongoDB 连接模板，客户端出现图标显示半截，如下图所示：

1. 打开 chat2db 客户端无 Redis 和 MongoDB 模板（新版本取消此功能了么）。
2. 客户端左上角图标显示半截（2.0.12 和 2.0.13 均有此现象）。

![bug_chat2db_v2 0 13_no_redis_mongodb](https://github.com/chat2db/Chat2DB/assets/26670266/d37fe4b2-02fe-4c8e-be77-e9692cb77e90)

**Comment by robinji0** [comment]
Yes, Redis and MongoDB are not supported right now. Move to #407
