### ISSUE TITLE
建议: [mysql]，查询结果在滑动鼠标可以选中数据，然后可以

### ISSUE THREAD

**Issue by luoxingyong-lxy** [chat2db/Chat2DB#50]
建议: [mysql]，查询结果在滑动鼠标可以选中数据，然后可以通过键盘复制选中的数据，像navicat那样的，现在需要鼠标点击复制按钮，按钮还很小，复制不方便。

**Comment by shanhexi** [comment]
get

**Comment by chenxian01** [comment]
Supported in latest version.
