### ISSUE TITLE
Optimization: unclear classification of functions and stored procedures

### ISSUE THREAD

**Issue by HealerBai** [chat2db/Chat2DB#500]
The classification of functions and stored procedures is not clear. Functions contain stored procedures, and stored procedures contain functions.

**Comment by robinji0** [comment]
Could you provide more screenshot to describe your problem?

**Comment by HealerBai** [comment]
<img width="539" alt="iShot_2023-09-05_15 42 07" src="https://github.com/chat2db/Chat2DB/assets/29203944/d5a6bfb8-e935-40b8-bb0d-ca146a7d72d7">

**Comment by robinji0** [comment]
OK，Got it. I will check this later.

**Comment by miahemu** [comment]
try pro version
https://chat2db.ai/zh-CN/download
