### ISSUE TITLE
Bug:  Mysql 库内表数量超过一定值后，无法根据表名筛选

### ISSUE THREAD

**Issue by hhhhkkk** [chat2db/Chat2DB#510]
### Chat2DB Version

2.0.13

### Describe the bug

库内共计4000张表，在左侧根据表名筛选应该是仅有几百条数据。
<img width="726" alt="image" src="https://github.com/chat2db/Chat2DB/assets/30823118/5e6f21df-31bd-4073-ab9c-bb6be1562d83">

**Comment by shanhexi** [comment]
已发布3.0.0版本 已经修复
