### ISSUE TITLE
Bug: 未正确根据表获取对应的id

### ISSUE THREAD

**Issue by AlexhahahaDrag** [chat2db/Chat2DB#511]
### Chat2DB Version

v2.0.11 build20230809020928

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/40189082/a9a73f0f-0847-458a-b0c1-3d5da771390d)
![image](https://github.com/chat2db/Chat2DB/assets/40189082/541548a5-cb85-4057-a50f-e81c316fe311)

**Comment by shanhexi** [comment]
已发布3.0.0版本 已经修复
