### ISSUE TITLE
建议: 是否可以增加sql格式化功能

### ISSUE THREAD

**Issue by AlexhahahaDrag** [chat2db/Chat2DB#512]
编写完sql没有sql格式化功能

**Comment by shanhexi** [comment]
![Uploading image.png…]()
怎么说

**Comment by shanhexi** [comment]
怎么说
![image](https://github.com/chat2db/Chat2DB/assets/86969353/5d98f73f-7150-486a-ba06-c170d8595707)

**Comment by AlexhahahaDrag** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/40189082/c7d1e85d-521b-4130-a5ba-1ae62f4f04e0)
点击报错

**Comment by robinji0** [comment]
You need to select your sql first and only sql, then click 'Format'. That should work.

**Comment by shanhexi** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/86969353/2f16a939-31e5-4ce1-9cb6-f5a2a79ce521)
2.0.13 无法复现您的问题
