### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by WudaxStudio** [chat2db/Chat2DB#518]
### Chat2DB Version

2.0.13

### Describe the bug

第一次安装后，启动时报错

![image](https://github.com/chat2db/Chat2DB/assets/130849175/f0aee829-0158-47d1-a427-093485d5c41e)

**Comment by SwallowGG** [comment]
重新安装会好吗

**Comment by GangLiCN** [comment]
你的机器是不是装了NodeJS的其他版本 ？ 先卸载，清空相关环境变量。
