### ISSUE TITLE
Bug: 查询结果整型值显示为boolean型

### ISSUE THREAD

**Issue by GZHOU34** [chat2db/Chat2DB#524]
### Chat2DB Version

v2.0.9

### Describe the bug

docker部署web版本  数据库实际值为1  前端展示为true
![微信截图_20230908143006](https://github.com/chat2db/Chat2DB/assets/144420294/a7eba4e5-4f71-428f-90b6-dfbb5ef4cb23)

**Comment by GZHOU34** [comment]
![Uploading 微信截图_20230908143006.png…]()

**Comment by shanhexi** [comment]
已发布3.0.0版本可能已经修复，或加群提供更详细的信息
