### ISSUE TITLE
Bug: Docker pulls the database before mirror mapping again. Chat2DB does not display the previous link information.

### ISSUE THREAD

**Issue by 101536363** [chat2db/Chat2DB#542]
### Chat2DB Version

Docker 2.1.0

### Describe the bug

Docker re-pulls the database before mirror mapping. chat2db does not display the previous link information. After opening. chat2db, you can see that the link information is still there.
![image](https://github.com/chat2db/Chat2DB/assets/72073965/34efc5ae-048e-4479-80a5-c1dfe5739b43)
The old db file can find the information of the previous library, but it is not displayed on the page.
<img width="1353" alt="image" src="https://github.com/chat2db/Chat2DB/assets/72073965/1b3d4e6a-ab72-4e71-a8b7-dd18ce393865">

No obvious errors were found in the log.
<img width="1373" alt="image" src="https://github.com/chat2db/Chat2DB/assets/72073965/f65e8175-9c12-4931-a1cc-5aba0a53f00e">

**Comment by miahemu** [comment]
try new version
