### ISSUE TITLE
建议: 关键词提示能否优先提示常用关键词，比如输入SE后SELECT能出现在第一位，这种常用的细节很影响使用体验

### ISSUE THREAD

**Issue by Yanch1994** [chat2db/Chat2DB#544]
<img width="642" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/ec9cb60e-65f6-4de4-a645-336b69e17ece">

**Comment by Yanch1994** [comment]
表字段提示也没有，建议先完善基础功能，提高基础体验。

**Comment by shanhexi** [comment]
已经优化3.0.0 已经修复，可以下载体验
