### ISSUE TITLE
Bug: The database connection executed by sql in the dashboard lacks self-built library loading (mysql).

### ISSUE THREAD

**Issue by moralibiao** [chat2db/Chat2DB#546]
### Chat2DB Version

2.0.13

### Describe the bug

In the dashboard, only the built-in schema is loaded in the database loading part (Mysql) next to SQL execution, and the created schema cannot be loaded.
<img width="1359" alt="image" src="https://github.com/chat2db/Chat2DB/assets/5055324/7e6d1b87-3c84-4efe-b9ed-2e2cf99b4c7c">

**Comment by miahemu** [comment]
try pro version
https://chat2db.ai/zh-CN/download
