### ISSUE TITLE
建议: web版支持一下PWA

### ISSUE THREAD

**Issue by augusl** [chat2db/Chat2DB#547]

**Comment by shanhexi** [comment]
哪个方面？

**Comment by augusl** [comment]
像GitHub就是支持的 ![CleanShot20230926at17.51.59@2x](https://i.imgur.com/85pzeAR.png)  可以添加到电脑手机pad等桌面上 启动后不用打开浏览器就能用,体验接近于APP

**Comment by augusl** [comment]
> 哪个方面？

像GitHub就是支持的 ![CleanShot20230926at17.51.59@2x](https://i.imgur.com/85pzeAR.png)  可以添加到手机 pad 电脑桌面上 不用打开浏览器就能用 体验接近于app

**Comment by shanhexi** [comment]
了解，后续我们搞一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月26日 17:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chat2db/Chat2DB] 建议: web版支持一下PWA (Issue #547) |

像GitHub就是支持的 可以添加到电脑手机pad等桌面上 启动后不用打开浏览器就能用,体验接近于APP
