### ISSUE TITLE
建议: 使用教程中驱动配置中链接和连接文字不一致

### ISSUE THREAD

**Issue by liangpengzhou** [chat2db/Chat2DB#548]
<img width="1473" alt="image" src="https://github.com/chat2db/Chat2DB/assets/7140834/6187b13a-2389-43cb-afd5-131988466fca">
在使用教程中的地方出现了两处文字不一致的描述

**Comment by shanhexi** [comment]
无法理解你的意思，如有需要可以加群@管理哦
