### ISSUE TITLE
建议: Ctrl+Enter执行查询的时候直接查询光标当前语句，而不需要选中sql。像dbeaver 那样

### ISSUE THREAD

**Issue by wellleehoho** [chat2db/Chat2DB#55]
Ctrl+Enter执行查询的时候直接查询光标当前语句，而不需要选中sql再执行。像dbeaver那样

**Comment by fanjinyu-fjy** [comment]
这个和当前的设计有冲突。
不选中，现在执行的console框内全部的SQL

**Comment by wangxin-inagora** [comment]
查询光标当前语句比较合理一些，一般不会每次都要查询所有的语句

**Comment by zhouxx2018** [comment]
> 这个和当前的设计有冲突。 不选中，现在执行的控制台框内全部的SQL

所以是不会做这个功能了是吗，感觉很不方便啊，每次都要用鼠标选中要执行的语句

**Comment by wangxin-inagora** [comment]
强烈需求这个功能
