### ISSUE TITLE
Bug: PostgreSql 表存在，但报错。

### ISSUE THREAD

**Issue by xiaoxi1313** [chat2db/Chat2DB#552]
### Chat2DB Version

v2.1.0

### Describe the bug

ERROR: relation "**" does not exist   位置：15

<img width="1125" alt="image" src="https://github.com/chat2db/Chat2DB/assets/7543595/6e5e3fba-38d1-43e6-90e5-da2d59c19b52">

**Comment by SwallowGG** [comment]
3.0.11已经修复
