### ISSUE TITLE
Bug: 打开数据库连接，表那里没有显示出表

### ISSUE THREAD

**Issue by zuxianghuang** [chat2db/Chat2DB#565]
### Chat2DB Version

v2.0.13

### Describe the bug

为什么这里没有显示表

<img width="1647" alt="WXWorkCapture_16966639586536" src="https://github.com/chat2db/Chat2DB/assets/7301534/32d58a8d-9ef2-4448-a49e-e1bfb0151ef4">

**Comment by zuxianghuang** [comment]
<img width="1647" alt="WXWorkCapture_16966639586536" src="https://github.com/chat2db/Chat2DB/assets/7301534/110aa88d-0734-422d-abd9-a3819a60ea0f">

**Comment by SwallowGG** [comment]
在头部左上角 切换 database
