### ISSUE TITLE
Bug: SQL server无法连接

### ISSUE THREAD

**Issue by Duanmj0430** [chat2db/Chat2DB#58]
### Chat2DB Version

1.0.11

### Describe the bug

链接SQL server时提示：The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]: null

修改java.security的默认限制
`jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL`
改为：
`jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, anon, NULL, \
   include jdk.disabled.namedCurves`
后连接成功，但是，点击连接概览的数据库时提示：COMMON_SYSTEM_ERROR: 系统开小差啦，请尝试刷新页面或者联系管理员

**Comment by xiaosageee** [comment]
修改Chat2Db 文件夹下 resources\app\jre\conf\security\java.security 的相同内容。

**Comment by fanhua1550** [comment]
同样的错误，修改的是 resources\app\jre\conf\security\java.security 文件信息。没法子用。
