### ISSUE TITLE
Bug: 关于Chat2DB页面，版本显示不正确

### ISSUE THREAD

**Issue by Zhuoyuan1** [chat2db/Chat2DB#59]
### Chat2DB Version

1.0.11

### Describe the bug

**系统**
Windows10 22H2
**位置**
设置-关于Chat2DB
![image](https://github.com/chat2db/Chat2DB/assets/41421622/5ff2e797-05b0-43dc-b48e-82d44da02425)
**问题**
版本显示v0.0.0

**Comment by shanhexi** [comment]
最新版本 已修复
