### ISSUE TITLE
Bug: 当sql语句结果集中存在重名的参数，且其中一个是null时，同名的参数的值即便后台返回了值，页面也会展示成null

### ISSUE THREAD

**Issue by zerowindy** [chat2db/Chat2DB#590]
### Chat2DB Version

v2.0.13

### Describe the bug

当sql语句结果集中存在重名的参数，且其中一个是null时，同名的参数的值即便后台返回了值，页面也会展示成null

**Comment by shanhexi** [comment]
已经修复，可以关注3.0.0的版本
