### ISSUE TITLE
Optimization: database comment function

### ISSUE THREAD

**Issue by fuce1314** [chat2db/Chat2DB#623]
Make a name comment on the database.
![image](https://github.com/chat2db/Chat2DB/assets/3125727/d8db96a9-d7f3-4055-aaac-697b3737ffe5)

Scenario: I don't know what this database does after a long time. If you can make notes when creating the database, you can modify such a function at any time. Will be very useful. Comments on the database. This function is not available in any console. I hope this issue can add highlights to the project.

**Comment by miahemu** [comment]
try pro veriosn
https://chat2db.ai/zh-CN/download
