### ISSUE TITLE
Bug: 登录显示 JCE cannot authenticate the provider BC  JDK版本是17

### ISSUE THREAD

**Issue by xuezimo** [chat2db/Chat2DB#646]
### Chat2DB Version

3.0

### Describe the bug

{"getApplicationMessage":{"env":"prod","versions":"3.0.7","buildTime":1698161925762,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"},"requestUrl":"http://10.41.46.38:10821/api/oauth/login_a","requestParams":"{\"userName\":\"chat2db\",\"password\":\"chat2db\"}","errorCode":"common.systemError","errorMessage":"An exception occurs, you can view the exception details in the log in the help menu.","errorDetail":"cn.hutool.crypto.CryptoException: SecurityException: JCE cannot authenticate the provider BC\n\tat cn.hutool.crypto.digest.mac.DefaultHMacEngine.init(DefaultHMacEngine.java:105)\n\tat cn.hutool.crypto.digest.mac.DefaultHMacEngine.<init>(DefaultHMacEngine.java:56)\n\tat cn.hutool.crypto.digest.mac.MacEngineFactory.createEngine(MacEngineFactory.java:42)\n\tat cn.hutool.crypto.digest.HMac.<init>(HMac.java:86)\n\tat cn.hutool.crypto.digest.HMac.<init>(HMac.java:74)\n\tat cn.hutool.crypto.digest.HMac.<init>(HMac.java:63)\n\tat cn.hutool.jwt.signers.HMacJWTSigner.<init>(HMacJWTSigner.java:28)\n\tat cn.hutool.jwt.signers.JWTSignerUtil.createSigner(JWTSignerUtil.java:239)\n\tat cn.hutool.jwt.signers.JWTSignerUtil.hs256(JWTSignerUtil.java:36)\n\tat cn.hutool.jwt.JWT.setKey(JWT.java:126)\n\tat cn.dev33.satoken.jwt.SaJwtTemplate.generateToken(SaJwtTemplate.java:119)\n\tat cn.dev33.satoken.jwt.SaJwtTemplate.createToken(SaJwtTemplate.java:109)\n\tat cn.dev33.satoken.jwt.SaJwtUtil.createToken(SaJwtUtil.java:100)\n\tat cn.dev33.satoken.jwt.StpLogicJwtForStateless.createTokenValue(StpLogicJwtForStateless.java:60)\n\tat cn.dev33.satoken.jwt.StpLogicJwtForStateless.createLoginSession(StpLogicJwtForStateless.java:99)\n\tat cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:331)\n\tat cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:293)\n\tat cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:135)\n\tat ai.chat2db.server.start.controller.oauth.OauthController.doLogin(OauthController.java:73)\n\tat ai.chat2db.server.start.controller.oauth.OauthController.login(OauthController.java:63)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat ai.chat2db.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:37)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)\n\tat org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat ai.chat2db.server.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.SecurityException: JCE cannot authenticate the provider BC\n\tat java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:144)\n\tat java.base/javax.crypto.Mac.getInstance(Mac.java:272)\n\tat cn.hutool.crypto.SecureUtil.createMac(SecureUtil.java:1086)\n\tat cn.hutool.crypto.digest.mac.DefaultHMacEngine.init(DefaultHMacEngine.java:95)\n\t... 80 more\nCaused by: java.lang.IllegalStateException: zip file closed\n\tat java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:839)\n\tat java.base/java.util.zip.ZipFile.getManifestName(ZipFile.java:1065)\n\tat java.base/java.util.zip.ZipFile$1.getManifestName(ZipFile.java:1108)\n\tat java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)\n\tat java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:320)\n\tat java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:263)\n\tat java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)\n\tat java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)\n\tat java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)\n\tat java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:140)\n\t... 83 more\n","solutionLink":"https://github.com/chat2db/Chat2DB/wiki/Chat2DB"}

**Comment by fanjinyu-fjy** [comment]
@xuezimo 请使用Open JDK 17
