### ISSUE TITLE
建议: 增加自定义驱动文件功能

### ISSUE THREAD

**Issue by galenliu6** [chat2db/Chat2DB#65]
我们这边的hive是CDH版本的，无法连接，需要你们这边增加自定义驱动文件的功能

**Comment by zlichao** [comment]
> 我们这边的hive是CDH版本的，无法连接，需要你们这边增加自定义驱动文件的功能
上传驱动，应该可以满足你的需求
![image](https://github.com/chat2db/Chat2DB/assets/3265227/6127a00e-0914-4142-9511-09774f3eb020)

**Comment by chenxian01** [comment]
Supported in the latest version.
