### ISSUE TITLE
Bug: clickhouse 数据源 切换数据库异常

### ISSUE THREAD

**Issue by OttoWu** [chat2db/Chat2DB#650]
### Chat2DB Version

v3.0.7

### 问题描述
在配置好clickhouse数据源之后（假设数据源叫datasource_1），切换其中的某个数据库，假设从db_A切换到db_B时，左侧table页面能够正常显示db_B下的所有表，但双击其中的表，会提示表不存在，通过console查询（不带具体的库名前缀查询表）也无法进行查询。

### 问题复现步骤1
1、数据源界面正确配置clickhouse数据源，例如jdbc:clickhouse://host1:8123
2、切换数据库从default至db_B，双击左侧table页中的某个表，无法查询，提示`Code: 60. DB::Exception: Table default.tablexxx doesn't exist.  ` (仍在default数据库下)

### 问题复现步骤2
1、数据源界面正确配置clickhouse数据源，例如jdbc:clickhouse://host1:8123/db_A （同复现步骤1一致，提前配置好数据库为db_A）
2、切换数据库从db_A至db_B，双击左侧table页中的某个表，无法查询，提示`Code: 60. DB::Exception: Table db_A.tablexxx doesn't exist.  ` (仍在db_A数据库下)

### 问题现象猜测
复现步骤2侧面说明除table列表外，其余console与查询数据页面的数据库均与数据源配置时指定的数据库一致，没有正确切换

**Comment by OttoWu** [comment]
> 3.0.8 已修复 #663

3.0.8 中仍存在获取库名不准确的情况，请按以下步骤测试

1、请配置连接串中指定库名，例如： jdbc:clickhouse://host1:8123/mam （这里指定库为mam）
2、双击左侧Table页面任意表，右侧显示错误，Code: 81. DB::Exception: Database mammam doesn't exist. (UNKNOWN_DATABASE) (version 22.9.1.1) 。Database里重复出现了两遍mam这个数据库名字

**Comment by 1194570458** [comment]
> > 3.0.8 已修复#663
> 
> 3.0.8中仍存在获取库名不准确的情况，请按以下步骤测试
> 
> 1、请配置连接串中指定库名，例如： jdbc:clickhouse://host1:8123/mam （这里指定库为mam） 2、左侧 左侧Table页面任意表，右侧显示错误，代码：81。 DB::Exception：数据库妈妈不存在。(UNKNOWN_DATABASE) (version 22.9.1.1) 。数据库里重复出现了两遍mam这个数据库名称

好的，这个问题漏了，下个版本修复下
