### ISSUE TITLE
Bug: 导出insert sql功能，普通用户正常，管理用户下载是空文件，

### ISSUE THREAD

**Issue by meyerlee** [chat2db/Chat2DB#654]
### Chat2DB Version

3.0.4

### Describe the bug

导出insert sql功能，普通用户正常，管理用户下载是**空文件**，

![1698370461315](https://github.com/chat2db/Chat2DB/assets/8414971/c6830021-a442-4b49-8d9f-b858c1b8a0e3)

**Comment by SwallowGG** [comment]
升级到3.0.7试一下

**Comment by meyerlee** [comment]
升级到3.0.8 普通用户也不行了

**Comment by QingXiao111** [comment]
已修复
