### ISSUE TITLE
建议: 对于表及修改表字段增加复制功能

### ISSUE THREAD

**Issue by by123456by** [chat2db/Chat2DB#657]
参考navcat的表及表字段编辑的功能，对表和字段可以直接复制
![image](https://github.com/chat2db/Chat2DB/assets/15666692/161e125d-cc5d-47c9-8225-bf6b077cddf1)
![image](https://github.com/chat2db/Chat2DB/assets/15666692/560e46a8-272a-4f94-8dab-0f2536f9b406)

**Comment by shanhexi** [comment]
3.0.10已经支持
