### ISSUE TITLE
Bug: 返回源表不存在的字段

### ISSUE THREAD

**Issue by ruthxhz** [chat2db/Chat2DB#66]
### Chat2DB Version

当前版本:v0.0.0 build 20230610114555

### Describe the bug

--- BEGIN ---
找出所有作业中,分组id为1,2,3的所有作业,统计每个人的在线作业数量
--- 自然语言转换 ---
SELECT worker_list, COUNT(*) AS online_job_count
FROM Job_Info
WHERE group_id IN (1, 2, 3) AND status = 'online'
GROUP BY worker_list

Unknown column 'worker_list' in 'field list'

返回源表不存在的字段

**Comment by chenxian01** [comment]
Yes, it's true. AI cannot guarantee 100% accuracy.

**Comment by ruthxhz** [comment]
我收到你的来信了.
