### ISSUE TITLE
建议: 选中行可以加一个复制为insert、update语句的功能

### ISSUE THREAD

**Issue by xiaojun207** [chat2db/Chat2DB#662]
建议: 选中行可以加一个复制为insert、update语句的功能

如Navicat中，
<img width="561" alt="image" src="https://github.com/chat2db/Chat2DB/assets/10277455/d26f4b9d-bb7f-4c54-84ca-65a2c8ab3ffc">

**Comment by shanhexi** [comment]
3.0.10已支持
