### ISSUE TITLE
建议: 期望能支持目录的方式访问

### ISSUE THREAD

**Issue by triumph** [chat2db/Chat2DB#676]
我们在做甲方的项目时，对方只给了一个域名，我们想嵌入这个查看线上数据库，希望能和项目结合
比如做到https://prod.test.com/chat2db/    这样带目录的访问形式。  谢谢

**Comment by shanhexi** [comment]
如果你想用来商业化，请查看https://github.com/chat2db/Chat2DB/blob/main/Chat2DB_LICENSE 避免不必要的法律纠纷
