### ISSUE TITLE
Bug: 配置了AI Key，在控制台上方输入指令回车后，提示CHAT2DB_SERVICE_ERROR

### ISSUE THREAD

**Issue by maxiaobaii** [chat2db/Chat2DB#681]
### Chat2DB Version

3.0.7

### Describe the bug

数据查询等均可用
但配置了AI Key，在控制台上方输入指令回车后，提示CHAT2DB_SERVICE_ERROR

![image](https://github.com/chat2db/Chat2DB/assets/61737472/dd38ed82-0cbf-40eb-9e06-f7adc73a464b)

错误信息如下：

![image](https://github.com/chat2db/Chat2DB/assets/61737472/d338666a-73d3-454f-b07f-382552e5b938)

**Comment by zhangtingshu** [comment]
我也遇到了同样的问题，mac客户端和docker版本都一样

**Comment by maxiaobaii** [comment]
> 我也遇到了同样的问题，mac客户端和docker版本都一样

我没用docker，直接把dmg文件安装完就用了 ，然后就这个报错

**Comment by shanhexi** [comment]
可以看下wiki 选的表的字段太多了
