### ISSUE TITLE
建议: sql输入框可以对手打的表名进行字段提示

### ISSUE THREAD

**Issue by hudishijie** [chat2db/Chat2DB#682]
目前纯手打的表名，在需要使用 表别名.字段名 时，是不会有字段提示的。
只有在输入表名时，在提示信息中下拉选择表名，回车之后自动补全的表，才会在使用 别名.字段 时，有字段提示信息。

这不合理，这说明目前sql输入框不能识别用户输入的对象信息，与navicat、plsql等的基础功能差的还很多。
测试使用的oracle11g数据库。

**Comment by SwallowGG** [comment]
3.0.11

**Comment by hudishijie** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/17746301/3ddfa590-f9a3-4415-a21c-242325b622c6)
![image](https://github.com/chat2db/Chat2DB/assets/17746301/6136b053-b9b7-47a1-afac-273f6c575b0b)
目前看，并没有解决。手工输入select * from data_hq.hq_code_dept t 后，可以看到查询结果的字段信息，但截图明显看到，t.后面跟的提示，并不是后面表的字段信息。
目前已经是3.0.12版本了

**Comment by hudishijie** [comment]
> 3.0.11
![image](https://github.com/chat2db/Chat2DB/assets/17746301/c922f310-403b-4a98-b637-14c6847f4b43)

已经更新至3.0.12版本了，问题并没有解决，别名提示的信息，明显还是在提示表名，而不是表的字段
