### ISSUE TITLE
Bug: 点击测试链接数据库的时候报下面这个错误

### ISSUE THREAD

**Issue by dan1212-copy** [chat2db/Chat2DB#69]
### Chat2DB Version

https://oss-chat2db.alibaba.com/release/1.0.11/Chat2DB%20Setup%201.0.11.exe

### Describe the bug

The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]: null

**Comment by chenxian01** [comment]
Fixed in the latest version.
