### ISSUE TITLE
Bug: MySQL 手动输入SQL 会无限加 ` 字符

### ISSUE THREAD

**Issue by WangJincheng4869** [chat2db/Chat2DB#691]
### Chat2DB Version

3.0.4

### Describe the bug

![图片](https://github.com/chat2db/Chat2DB/assets/41162158/88e2ad50-e35c-4de0-af14-6b6a4bf72915)

全选表名进行修改

![图片](https://github.com/chat2db/Chat2DB/assets/41162158/e55e79e7-4a19-449d-a5ca-110a19620950)

最终效果

![图片](https://github.com/chat2db/Chat2DB/assets/41162158/76a4ea52-ddcf-42ac-8e67-e87aae87b8ac)

**Comment by fanjinyu-fjy** [comment]
已修复，可以使用下最新的3.0.10版本体验
