### ISSUE TITLE
建议: 希望加入对Redis的支持

### ISSUE THREAD

**Issue by Galaxy9572** [chat2db/Chat2DB#694]
希望加入对Redis的支持

**Comment by DragonM87** [comment]
貌似现在已经支持了吧

**Comment by DragonM87** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/29292904/958f944a-544d-44cd-86dd-3137cd7c9bca)

**Comment by Z-hu** [comment]
安装完发现并没有redis

**Comment by fanjinyu-fjy** [comment]
这个月会支持的
