### ISSUE TITLE
Bug: macOS下切换浅色/深色模式有bug

### ISSUE THREAD

**Issue by Galaxy9572** [chat2db/Chat2DB#695]
### Chat2DB Version

3.0.8

### Describe the bug
系统：macOS Sonoma 14.0 M1 Max
不管在主题设置下设置成亮色还是暗色主题还是跟随系统，当Mac切换深色浅色模式时，chat2db的主题都会跟随系统变化

复现步骤：
1、在主题设置下设置成亮色/暗色主题
2、切换深色/浅色模式
结果：
主题设置的亮色/暗色主题无效
截图：
<img width="1996" alt="image" src="https://github.com/chat2db/Chat2DB/assets/20737136/a3b517d2-5a89-4156-8983-b2b6c36f6a80">
<img width="1995" alt="image" src="https://github.com/chat2db/Chat2DB/assets/20737136/9be273b1-92c3-471f-ac65-365b5b62103c">

**Comment by shanhexi** [comment]
无法复现哦，可以加群@管理提供更多信息
