### ISSUE TITLE
Bug: chatglm3 不支持！

### ISSUE THREAD

**Issue by coderwpf** [chat2db/Chat2DB#708]
### Chat2DB Version

3.0.8

### Describe the bug

[chatglm-6b](https://github.com/THUDM/ChatGLM3)  最新发布的版本，请支持。多谢！

**Comment by fanjinyu-fjy** [comment]
> ### Chat2DB Version
> 3.0.8
> 
> ### Describe the bug
> [chatglm-6b](https://github.com/THUDM/ChatGLM3) 最新发布的版本，请支持。多谢！

现如今，智谱提供的API没有和具体的LLM绑定。
这种开源的LLM模型，你可以自己部署了，用自定义配置接入进来
