### ISSUE TITLE
建议: 快速复制单行insert sql/update sql到内存中

### ISSUE THREAD

**Issue by yann-su** [chat2db/Chat2DB#709]
为什么提出这个新的特性改动
可以快速复制sql，从 a 环境到 b 环境，不需要进入下载，直接能对行进行 copy 到本地文件中编辑，可以单一行 sql

描述一下你推荐的解决方案
目前推荐使用 navicat 的操作逻辑，邮件可以 copy to sql或者复制成 update

描述一下你考虑过的其它替代解决方案
从易用性来说，这个是简化操作

**Comment by mr-mihu** [comment]
希望作者可以参考 heidsql也同样支持复制行，可以做参考
![image](https://github.com/chat2db/Chat2DB/assets/34831987/d73f511f-f969-4ce1-ac96-cac622e6f029)

**Comment by shanhexi** [comment]
3.0.10已支持
