### ISSUE TITLE
建议: 请问怎么查看表结构呢？

### ISSUE THREAD

**Issue by duanzhuofeng** [chat2db/Chat2DB#71]
请问怎么查看mysql表结构呢？

**Comment by zwdgit** [comment]
+1

**Comment by zwdgit** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/28926324/22fff682-c3c5-4986-b054-324729f97419)

**Comment by chenxian01** [comment]
Please refer the answer by @zwdgit
