### ISSUE TITLE
Bug: 无法打开“Chat2DB.app”，因为Apple无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by yanan-wyze** [chat2db/Chat2DB#715]
### Chat2DB Version

v3.0.8

### Describe the bug

mac intel 芯片 版本，打开软件提示【 无法打开“Chat2DB.app”，因为Apple无法检查其是否包含恶意软件。】

**Comment by shanhexi** [comment]
有时苹果的安全认证有问题，不影响使用，可百度搜索 “因为Apple无法检查其是否包含恶意软件” 解决。
