### ISSUE TITLE
Suggestion: The query result list supports row and column selection and provides right-click function.

### ISSUE THREAD

**Issue by hbh112233abc** [chat2db/Chat2DB#720]
Reference navicat query result list supports multi-line selection.
1. press ctrl+ mouse to select and select multiple lines.
2. Press shift+ mouse to select and select multiple rows.
3. Columns are sorted only by clicking the sorting icon, otherwise the corresponding column data is selected.

When selected, it supports the shortcut key ctrl+c to copy data and the right-click menu.
-Copy as
![image](https://github.com/chat2db/Chat2DB/assets/7788164/256c6d37-9c45-4d69-9f3b-6c6e21a377c9)

-Export as
![image](https://github.com/chat2db/Chat2DB/assets/7788164/b74ab921-1b3f-48e3-b29f-fcb494a55834)

-Delete the selected row.
-bulk modify a field.

**Comment by miahemu** [comment]
Changes have been made in the new version, and optimization will continue in the future.
