### ISSUE TITLE
Bug: postgres修改数据 当表字段中存在boolen字段时修改保存会报错

### ISSUE THREAD

**Issue by lanayahebefan** [chat2db/Chat2DB#722]
### Chat2DB Version

3.0.8

### Describe the bug

postgres 查出数据 当表字段中存在boolean类型时修改会报错
<img width="1743" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39938163/6cd6b261-fc78-4293-b22b-3f34e26bbe6d">

**Comment by SwallowGG** [comment]
预计周末修复
