### ISSUE TITLE
建议: 希望SQL提示能够支持视图和视图字段的提示

### ISSUE THREAD

**Issue by git-cleverly** [chat2db/Chat2DB#723]
<img width="1131" alt="image" src="https://github.com/chat2db/Chat2DB/assets/25656361/07e84bde-574a-499d-ae32-9169cf44a1fb">

**Comment by fanjinyu-fjy** [comment]
很好的建议，我们会尽快修复

**Comment by fanjinyu-fjy** [comment]
新版本3.0.10已修复
