### ISSUE TITLE
Bug: 3.0.8没有windows安装包

### ISSUE THREAD

**Issue by jqk** [chat2db/Chat2DB#727]
### Chat2DB Version

3.0.8

### Describe the bug

3.0.7 release中还有windows版安装包，3.0.8中消失了，以后不在github上提供了吗？

谢谢

**Comment by shanhexi** [comment]
可以前往官网下载哦

**Comment by shanhexi** [comment]
[Chat2DB-Setup-3.0.9.exe](https://github.com/chat2db/Chat2DB/releases/download/v3.0.9/Chat2DB-Setup-3.0.9.exe) 这个就是window的，建议去[官网](https://sqlgpt.cn/)下载更方便，更多问题可以加群@群主@管理
