### ISSUE TITLE
Bug: Github 安装包Chat2DB-3.0.9-arm64-mac.zip安装，没有Redis和Mongodb

### ISSUE THREAD

**Issue by ppm10103** [chat2db/Chat2DB#728]
### Chat2DB Version

3.0.9-arm64

### Describe the bug

![no-redis-mongodb](https://github.com/chat2db/Chat2DB/assets/4432983/facb83f8-456a-4216-a49c-975031d1254f)

**Comment by fanjinyu-fjy** [comment]
11月份会重新上
