### ISSUE TITLE
Bug: console界面 右上角手动选择表，当表过多时，只能选择左下角当前分页中的表，

### ISSUE THREAD

**Issue by CodingPeppa** [chat2db/Chat2DB#731]
### Chat2DB Version

3.0.0

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/45756817/bd224249-9e99-47bd-a29d-2e94c20d8c51)
此处只能搜索到分页中查到的表
![image](https://github.com/chat2db/Chat2DB/assets/45756817/48fa8d0e-4569-4a98-97b9-ffc16a093cfb)
导致多个表无法一起加入上下文

**Comment by mr-mihu** [comment]
中文输入时，按键会自动关闭这个组件窗口，应该保留窗口不能判断失去焦点就关闭整个组件

**Comment by fanjinyu-fjy** [comment]
> 中文输入时，按键会自动关闭这个组件窗口，应该保留窗口不能判断失去焦点就关闭整个组件

这个问题没有复现。麻烦再确认下

**Comment by fanjinyu-fjy** [comment]
> ### Chat2DB Version
> 3.0.0
> 
> ### Describe the bug
> ![image](https://user-images.githubusercontent.com/45756817/279847218-bd224249-9e99-47bd-a29d-2e94c20d8c51.png) 此处只能搜索到分页中查到的表 ![image](https://user-images.githubusercontent.com/45756817/279847258-48fa8d0e-4569-4a98-97b9-ffc16a093cfb.png) 导致多个表无法一起加入上下文

最新版本已经修复
