### ISSUE TITLE
Bug: 没有redis连接支持？？？看着官网下载的3.0.8，更新了3.0.9依旧没有redis连接？

### ISSUE THREAD

**Issue by Z-hu** [chat2db/Chat2DB#738]
### Chat2DB Version

3.0.9

### Describe the bug

<img width="2402" alt="截屏2023-11-03 11 38 21" src="https://github.com/chat2db/Chat2DB/assets/35365645/d2dc7fc5-fb8b-4351-9291-9fd5895febff">

**Comment by songshengping** [comment]
是的,没有Redis支持.

**Comment by fanjinyu-fjy** [comment]
会在11月份重新上线
