### ISSUE TITLE
Bug:redis连接测试成功，但无法打开 

### ISSUE THREAD

**Issue by angel1magic** [chat2db/Chat2DB#74]
### Chat2DB Version

V1.0.10

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/20294059/ae31ebaa-6517-4c1e-baef-5cc0ca5a7730)

![dc75c8696ae2cd1e23c7f16c177eb85](https://github.com/chat2db/Chat2DB/assets/20294059/6d7888b4-a38f-4175-8aa6-7b551ac5dc5a)

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.
