### ISSUE TITLE
Bug: 启动软件就报错。NoClassDefFoundError: Could not initialize class ai.chat2db.server.domain.core.cache.MemoryCacheManage\

### ISSUE THREAD

**Issue by zoupengfeiagent** [chat2db/Chat2DB#741]
### Chat2DB Version

v3.0.9

### Describe the bug

启动软件就报错。
<img width="634" alt="image" src="https://github.com/chat2db/Chat2DB/assets/149367880/f83d7587-b1bb-4504-81d7-0c7043d55e74">

{"getApplicationMessage":{"env":"desktop","versions":"3.0.9","buildTime":1698844934257,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) chat2db/3.0.9 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"},"requestUrl":"http://127.0.0.1:10824/api/connection/datasource/list","requestParams":"{\"pageNo\":1,\"pageSize\":999}","errorCode":"common.systemError","errorMessage":"An exception occurs, you can view the exception details in the log in the help menu.","errorDetail":"jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class ai.chat2db.server.domain.core.cache.MemoryCacheManage\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat ai.chat2db.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:37)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)\n\tat org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat ai.chat2db.server.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: java.lang.NoClassDefFoundError: Could not initialize class ai.chat2db.server.domain.core.cache.MemoryCacheManage\n\tat ai.chat2db.server.start.config.config.Chat2dbWebMvcConfigurer$1.preHandle(Chat2dbWebMvcConfigurer.java:89)\n\tat org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1076)\n\t... 50 more\nCaused by: java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: org.ehcache.core.spi.service.ServiceFactory: Error accessing configuration file [in thread \"http-nio-0.0.0.0-10824-exec-1\"]\n\tat java.base/java.util.ServiceLoader.fail(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)\n\tat java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)\n\tat java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)\n\tat java.base/java.util.Iterator.forEachRemaining(Unknown Source)\n\tat java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)\n\tat java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)\n\tat org.ehcache.core.spi.ServiceLocator$DependencySet.discoverServices(ServiceLocator.java:425)\n\tat org.ehcache.core.spi.ServiceLocator$DependencySet.lookupService(ServiceLocator.java:380)\n\tat org.ehcache.core.spi.ServiceLocator$DependencySet.build(ServiceLocator.java:329)\n\tat org.ehcache.core.EhcacheManager.resolveServices(EhcacheManager.java:154)\n\tat org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:125)\n\tat org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:115)\n\tat org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:111)\n\tat org.ehcache.config.builders.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:112)\n\tat org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:68)\n\tat ai.chat2db.server.domain.core.cache.MemoryCacheManage.<clinit>(MemoryCacheManage.java:32)\n\t... 53 more\n","solutionLink":"https://github.com/chat2db/Chat2DB/wiki/Chat2DB"}

**Comment by zoupengfeiagent** [comment]
后退了一个版本。3.0.8也是同样的错误。

**Comment by SwallowGG** [comment]
3.0.11
