### ISSUE TITLE
Bug: 我用了正确的open ai key但是提示AI无法正常访问

### ISSUE THREAD

**Issue by zhaolinlly** [chat2db/Chat2DB#75]
### Chat2DB Version

1.0.11

### Describe the bug

我链接的是PGSQL，我的VPN设置的是全局，我看日志也是显示sucess=true  控制台里面都是返回200，但是就是提示：AI无法正常访问，我不太确实是否是BUG

![1](https://github.com/chat2db/Chat2DB/assets/34708290/d157e5ff-2627-4c7f-a221-56339b17010b)
![2](https://github.com/chat2db/Chat2DB/assets/34708290/ea958363-a9d4-490e-bbe1-26a00d8ca6c4)
![3](https://github.com/chat2db/Chat2DB/assets/34708290/757ddeaa-020a-4a77-834c-15ec69e25636)

**Comment by chenxian01** [comment]
Please set the proxy host and proxy port correctly to make sure the client can connect to the openai api. By the way, the version 1.x will not be supported, please try the latest version.
