### ISSUE TITLE
Bug: cannot start chat2db

### ISSUE THREAD

**Issue by bebestmaple** [chat2db/Chat2DB#757]
### Chat2DB Version

3.0.9

### Describe the bug

chat2db Console:

Web server failed to start. Port 10824 was already in use.

BUT  :
NOT start chat2db :
```shell
> netstat -ano | findStr 10824
> (none)
```
Started chat2db
```shell
> netstat -ano | findStr 10824
 TCP    127.0.0.1:9027         127.0.0.1:10824        SYN_SENT        21560
 TCP    127.0.0.1:9028         127.0.0.1:10824        SYN_SENT        21560
> tasklist | findstr 21560
Chat2DB.exe                  21560 Console                    1     54,508 K
```
chat2db use the port 10824,and show Port 10824 was already in use?

AND

can we set which port to use?

**Comment by tmlx1990** [comment]
如果需要修改默认端口，需要下载源码，修改chat2db-client中的src\service\base.ts中的
![image](https://github.com/chat2db/Chat2DB/assets/5753992/cfdcd350-d104-434f-b4fc-9ae7176e43ba)

还需要修改chat2db-server中chat2db-server-start的src\main\resources\application-release.yml中
![image](https://github.com/chat2db/Chat2DB/assets/5753992/ab321bb2-821a-4e0d-b5d1-a384b889020b)
