### ISSUE TITLE
提问  请问公司程序员使用chat2DB 会有法律风险么？

### ISSUE THREAD

**Issue by qiuxun** [chat2db/Chat2DB#758]
公司程序员使用chat2DB 作为平常开发工具

**Comment by shanhexi** [comment]
开源社区版放心食用，如果你有更高的团队协作需求，可在官网- https://sqlgpt.cn/zh 联系我们

**Comment by bestv5** [comment]
> 开源社区版放心食用，如果你有更高的团队协作需求，可在官网- https://sqlgpt.cn/zh 联系我们

社区版和离线版、专业版有何区别？

**Comment by tmlx1990** [comment]
> > 开源社区版放心食用，如果你有更高的团队协作需求，可在官网- https://sqlgpt.cn/zh 联系我们
> 
> 社区版和离线版、专业版有何区别？

https://chat2db-ai.com/zh-CN/pricing 这里可以查看离线版和专业版的区别。社区版的功能会少一点，支持的数据库也会少些。

**Comment by bestv5** [comment]
> > > 开源社区版放心食用，如果你有更高的团队协作需求，可在官网- https://sqlgpt.cn/zh 联系我们
> > 
> > 
> > 社区版和离线版、专业版有何区别？
> 
> https://chat2db-ai.com/zh-CN/pricing 这里可以查看离线版和专业版的区别。社区版的功能会少一点，支持的数据库也会少些。

感觉你说了，又感觉你没说....  好还是自己研究吧
