### ISSUE TITLE
Bug: 导出查询结果，文件内容出错

### ISSUE THREAD

**Issue by 1535369984** [chat2db/Chat2DB#763]
### Chat2DB Version

3.0.10

### Describe the bug

这是查询语句结果：
![image](https://github.com/chat2db/Chat2DB/assets/33055279/d46f8e4a-70f8-403a-a40e-736859f6e03c)

这是导表结果：
![image](https://github.com/chat2db/Chat2DB/assets/33055279/7e87980e-7a2a-4bc9-bbe9-cda2b3a48c81)

错误的填充了时间数据！使用的功能是：export result set csv

**Comment by 1535369984** [comment]
才发现应该是csv格式文件的问题，会把"10/10"自动转为时间

**Comment by Dewchlu** [comment]
蹲一蹲 xlsx格式 yyds
