### ISSUE TITLE
Bug: When connecting to MS SQL Server, the result of the same script executed in Chat2DB 3.0.10 is inconsistent with that executed in Microsoft SQL Server Management Studio.

### ISSUE THREAD

**Issue by dev-Hanjing** [chat2db/Chat2DB#766]
### Chat2DB Version

Chat2DB v3.0.10

### Describe the bug

When connecting to MS SQL Server, the result of the same script executed in Chat2DB 3.0.10 is inconsistent with that executed in Microsoft SQL Server Management Studio.

-the database is MS SQL Server 2016.
-prepare the test table

CREATE TABLE tbl_test(
  stu_id int ,
  stu_name varchar(20)
)
GO 
-Insert test data
INSERT into tbl_test values(1,'aaaa');
INSERT into tbl_test values(2,'bbbb');
INSERT into tbl_test values(3,'cccc');
GO

-The following is the beginning of the simulated query processing logic-----------.

declare @id INT
set @id = 1

select * into #tbl_test FROM tbl_test

update #tbl_test set stu_name = 'dddd' where stu_id=@id 

select * from #tbl_test

-The following is the end of the simulated query processing logic-------

The result of execution in Char2DB only shows "number of affected rows: 3", and the contents of the temporary table @tbl_test are not displayed in table form, but the result of execution in Microsoft SQL Server Management Studio shows the contents of the temporary table #tbl_test in table form.
![3](https://github.com/chat2db/Chat2DB/assets/12488587/70c30338-c15e-4e52-aa82-c69d7e136631)

<img width="333" alt="2" src="https://github.com/chat2db/Chat2DB/assets/12488587/58caf8bb-bb99-4347-8a2b-60dc0eb402b1">

**Comment by miahemu** [comment]
在 SQL Server 中，不能直接在 UPDATE 语句中使用 SELECT 语句来更新临时表。如果你想要使用 SELECT 查询来更新临时表，你可以使用 UPDATE ... FROM ... 语法。`DECLARE @id INT;
SET @id = 1;

SELECT * INTO #tbl_test FROM tbl_test;

UPDATE t
SET stu_name = 'dddd'
FROM #tbl_test t
WHERE stu_id = @id;

SELECT * FROM #tbl_test;
`
