### ISSUE TITLE
Bug: 字段是BIGINT类型，但是显示的精度丢失了，使用的是MySQL

### ISSUE THREAD

**Issue by kingkun1234** [chat2db/Chat2DB#77]
### Chat2DB Version

v1.0.11

### Describe the bug

正常的数据是：1118748237849833472，但是查询展示的是：1118748237849833500
<img width="178" alt="image" src="https://github.com/chat2db/Chat2DB/assets/15060453/f9e88822-e7a7-4aab-8ac6-40088ace748d">

**Comment by shanhexi** [comment]
已修复
