### ISSUE TITLE
Bug: mysql数据库表字段point类型显示不对乱码

### ISSUE THREAD

**Issue by 994279206** [chat2db/Chat2DB#777]
### Chat2DB Version

v3.0.10

### Describe the bug

<img width="232" alt="image" src="https://github.com/chat2db/Chat2DB/assets/46415598/adafbdc5-efb8-4aaf-8f0c-317f71c1b78c">

**Comment by shanhexi** [comment]
以定位到问题，下个版本修复

**Comment by SwallowGG** [comment]
新版本已经修复
