### ISSUE TITLE
Bug: 连接PostgreSQL数据库问题

### ISSUE THREAD

**Issue by whorusq** [chat2db/Chat2DB#78]
### Chat2DB Version

1.0.11

### Describe the bug

- 数据连接不保存密码；
- 只能用postgres用户连接，用其它用户会被当成数据库名报错；
- 连接成功进去之后只能看到 postgres 一个数据库；
- 查看表结构、设计表、视图等常用功能找不到入口

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.
