### ISSUE TITLE
Bug: Chat2DB has a permission management vulnerability that allows ordinary users to read the ssh password and database password configured by the administrator.

### ISSUE THREAD

**Issue by wa1ki0g** [chat2db/Chat2DB#780]
### Chat2DB Version

all

### Describe the bug

越权漏洞
Permission management vulnerability

普通用户通过 /api/connection/datasource/list?pageNo=1&pageSize=999&refresh=true接口，可读取管理员配置好的ssh密码与数据库密码
Ordinary users can read the ssh password and database password configured by the administrator through the /api/connection/datasource/list?pageNo=1&pageSize=999&refresh=true interface.

![image](https://github.com/chat2db/Chat2DB/assets/70200814/bd986c82-58ce-4fbb-a9d7-7bec79b8e78e)
![image](https://github.com/chat2db/Chat2DB/assets/70200814/bb8b6fa3-f54e-4de6-a87e-5671b4b0e13b)

**Comment by shanhexi** [comment]
这个会在一个月左右的新权限版本中修复
