### ISSUE TITLE
Bug: PG 查看建表语句，生成的默认值有错误

### ISSUE THREAD

**Issue by e-mhui** [chat2db/Chat2DB#785]
### Chat2DB Version

v3.0.10

### Describe the bug

Bug: PG 查看建表语句，生成的默认值有错误，无法执行

<img width="531" alt="image" src="https://github.com/chat2db/Chat2DB/assets/111486498/9c12ab1c-2bc0-4a73-b994-16be4e7de065">

**Comment by e-mhui** [comment]
PRI 也是有错误
<img width="793" alt="image" src="https://github.com/chat2db/Chat2DB/assets/111486498/bafbf631-7f57-4ca2-9894-452cf7d70a87">

**Comment by e-mhui** [comment]
<img width="856" alt="image" src="https://github.com/chat2db/Chat2DB/assets/111486498/df158128-76d3-4c85-9dfc-db465138e490">

**Comment by e-mhui** [comment]
<img width="591" alt="image" src="https://github.com/chat2db/Chat2DB/assets/111486498/27cc8a42-c46b-436c-b09d-4feef48ed1fc">

**Comment by shanhexi** [comment]
感谢你的参与，可以加群更多的参与贡献，我们将会有礼品送出
