### ISSUE TITLE
Bug: 行复制错乱

### ISSUE THREAD

**Issue by swtseaman** [chat2db/Chat2DB#809]
### Chat2DB Version

3.0.11

### Describe the bug

行复制的时候，丢字段、字段值错乱

**Comment by swtseaman** [comment]
复制行为 -> insert 语句

**Comment by tmlx1990** [comment]
> 复制行为 -> insert 语句

您好，能提供一下相关的操作截图吗？还有数据类型。刚没有复现出来。

**Comment by shanhexi** [comment]
3.0.12已经修复
