### ISSUE TITLE
Bug: list cannot select field sort.

### ISSUE THREAD

**Issue by Wpeng-Stronger** [chat2db/Chat2DB#812]
### Chat2DB Version

3.0.11

### Describe the bug

In the query list, I want to reverse the order through the time field, but I don't actually reverse the order according to the time field.
![image](https://github.com/chat2db/Chat2DB/assets/73539392/60135511-d4df-47d8-9339-ddfc7d1087c2)
![image](https://github.com/chat2db/Chat2DB/assets/73539392/09b70254-5656-49cd-8409-fa4ebe18c8af)

**Comment by Wpeng-Stronger** [comment]
或者说这个排序是根据当前页进行排序，不是对所有数据进行排序的？

**Comment by tmlx1990** [comment]
这个排序应该只是会排序当前查出来的数据的。

**Comment by zhangzimuzjq** [comment]
这里的排序是前端排序了吧
