### ISSUE TITLE
Bug: 双击Redis的键，右侧生成的是select语句无法使用

### ISSUE THREAD

**Issue by CV-Devlau** [chat2db/Chat2DB#82]
### Chat2DB Version

1.0.11

### Describe the bug

双击Redis的键，右侧生成的是select语句无法使用

![image](https://github.com/chat2db/Chat2DB/assets/63354237/ffe8ed62-e03e-4206-a0b2-1033403109e2)

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.
