### ISSUE TITLE
建议:创建数据表的问题 

### ISSUE THREAD

**Issue by zhipeng0703** [chat2db/Chat2DB#820]
在chat2db中，连接MySQL成功，已经选择了数据库，随后创建数据表的时候，创表语句的数据库默认不是当前选择的数据库，而是数据表的名字，这样的话使用这个工具还得自己重新改创表命令，变得繁琐了

**Comment by shanhexi** [comment]
这个是个bug已经修掉了，可以热更新3.0.13
