### ISSUE TITLE
Bug: 插入多条数据，返回结果是 影响1条 

### ISSUE THREAD

**Issue by shanze680** [chat2db/Chat2DB#824]
### Chat2DB Version

3.0.12

### Describe the bug

插入多条数据，返回结果是 影响1条

**Comment by tmlx1990** [comment]
您好，请问是什么数据库？

**Comment by shanze680** [comment]
mysql

**Comment by tmlx1990** [comment]
> mysql

我刚测试了下，他是把每个SQL影响的行数，分别统计的。每个的执行结果是分开看的。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/78777c58-6c21-4c48-a2a0-af18a274f6ab)
