### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by failgoddess** [chat2db/Chat2DB#83]
### Chat2DB Version

当前版本:v0.0.0 build 20230616055223

### Describe the bug

前端处理long类型的数据值丢失精度
数据库中的id
<img width="314" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39648053/0b313285-9de2-45df-8a52-acf867764d4a">
chat2db中的id 
<img width="366" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39648053/db17f367-10bd-4ae4-84b2-e0e686c5a2af">

**Comment by chenxian01** [comment]
Fixed in the latest version.
