### ISSUE TITLE
Bug: Unable to connect to the Internet. After uploading the driver, the drop-down box will not be displayed.

### ISSUE THREAD

**Issue by benzi007** [chat2db/Chat2DB#832]
### Chat2DB Version

v3.0.13

### Describe the bug

Unable to connect to the Internet. After uploading the driver, the drop-down box will not be displayed.
![image](https://github.com/chat2db/Chat2DB/assets/53590829/1a6176ff-f1a4-4029-9dda-161cf5d9e3e4)

**Comment by tmlx1990** [comment]
> 同样遇到过这个问题, 上传驱动后这里不显示驱动. 

能提供下具体jar包及上传时的界面吗？
