### ISSUE TITLE
Bug: 快速打开多个有概率出现鬼畜效果

### ISSUE THREAD

**Issue by WangJincheng4869** [chat2db/Chat2DB#837]
### Chat2DB Version

3.0.13

## 复现步骤
1. 连接好 MySQL 数据库
2. 通过左侧表菜单 `双击` 快速打开多个表会出现
3. 打开表尽量多几个，会出现多个标签同时查询的情况
4. 我打开了很多表，已经出现滚动条

![动画](https://github.com/chat2db/Chat2DB/assets/41162158/8b84fbad-0e99-43c8-bbde-acf5790b56ad)

PS：操作不顺滑，很卡顿，估计是架构的原因，这种架构的软件一般都卡的一批

**Comment by shanhexi** [comment]
fix
