### ISSUE TITLE
Bug: Mysql 5.X database cannot be connected

### ISSUE THREAD

**Issue by 1409130272** [chat2db/Chat2DB#843]
### Chat2DB Version

3.0.13

### Describe the bug

The MySQL version is 5.X. Clicking on "Upload Driver" fails to upload successfully. It's still only possible to select the 8.0 driver. I suggest adding a direct option for MySQL 5.X driver selection. When the customer's database is 5.X, selecting this driver should enable successful connection.

**Comment by tmlx1990** [comment]
可以提供下具体日志，及使用的具体jar包吗？

**Comment by Timmiy** [comment]
我遇到相同问题，无法上传5.1.49驱动
![image](https://github.com/chat2db/Chat2DB/assets/15071973/cf6a761e-0e35-4a02-b5bd-7fd91f1419c2)

**Comment by miahemu** [comment]
try new version
