### ISSUE TITLE
Bug: 如果查询时不指定库，则会随机选择库执行

### ISSUE THREAD

**Issue by demoManito** [chat2db/Chat2DB#845]
### Chat2DB Version

v2.0.12

### Describe the bug

查询时未指定库时，有时显示 No database selecte，有时会随机选择一个库：
<img width="1010" alt="image" src="https://github.com/chat2db/Chat2DB/assets/27986239/112ec22a-ac62-49ac-8f2b-89f91c83bb09">

指定表名后：
<img width="1303" alt="image" src="https://github.com/chat2db/Chat2DB/assets/27986239/4c50c165-6ec3-4168-a3fc-a183f95ea302">

**Comment by shanhexi** [comment]
什么数据库呢，还会随机选择库呢啊，
不过后续我们会换成navicat的操作 自己选择库
大概12月会上

**Comment by demoManito** [comment]
> 什么数据库呢，还会随机选择库呢啊， 不过后续我们会换成navicat的操作 自己选择库 大概12月会上

数据库：MySQL
版本：8.0.21
