### ISSUE TITLE
优化: 配置支持自定义

### ISSUE THREAD

**Issue by wangshengji** [chat2db/Chat2DB#85]
问题：使用的Oracle版本比较低，并且在内网。 在配置文件中的url驱动下载路径被解析完成之后并不匹配，判断本地是否存在。
源代码如下：
```java
for (String url : urls) {
            String outputPath = PATH + url.substring(url.lastIndexOf("/") + 1);
            File file = new File(outputPath);
            if (file.exists()) {
                System.out.println("File already exists: " + outputPath);
                continue;
            }
            asyncDownload(url);
        }
````
这边想要将可以适配的版本jar包重命名，然后客户端又报错：
Listener refused the connection with the following error: ORA-12505, TNS:listener does not currently know of SID given in connect descriptor : null

**Comment by chenxian01** [comment]
Upload driver manually was supported in the latest version.
