### ISSUE TITLE
Bug: Confusion between half-width symbols and full-width symbols is displayed after describing the problem

### ISSUE THREAD

**Issue by keker12138** [chat2db/Chat2DB#855]
### Chat2DB Version

3.0.13

### Describe the bug

Chat2db AI Error：<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by keker12138** [comment]
点击冒号会出现问题描述：The character U+ff1a "：" could be confused with the ASCII character U+003a ":", which is more common in source code. [Adjust settings]

**Comment by tmlx1990** [comment]
您好，请问这个是怎么操作的？能否截图下
