### ISSUE TITLE
Bug: 执行自然语言的查询需求报502网关错误

### ISSUE THREAD

**Issue by mouse325** [chat2db/Chat2DB#857]
### Chat2DB Version

3.0.13

### Describe the bug

1. 在chat2db中测试连接我的数据库成功。
2. 在控制台中用自然语言写一条查询需求。点击“执行”
3. 报502网关错误如下：
Chat2db AI Error：<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by shanhexi** [comment]
应该好了昂
