### ISSUE TITLE
优化: 我看redis的metadata里面用connection对象执行操作，应该用jedis这样的客户端来连接执行吧

### ISSUE THREAD

**Issue by hxhsome** [chat2db/Chat2DB#86]
public List<String> databases() {
        List<String> databases = new ArrayList<>();
        return SQLExecutor.getInstance().executeSql("config get databases", resultSet -> {
            try {
                if (resultSet.next()) {
                    Object count = resultSet.getObject(2);
                    if(StringUtils.isNotBlank(count.toString())) {
                        for (int i = 0; i < Integer.parseInt(count.toString()); i++) {
                            databases.add(String.valueOf(i));
                        }
                    }
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
            return databases;
        });
    }

**Comment by robinji0** [comment]
marked in #402
