### ISSUE TITLE
Bug: mysql 数据库新建一行新数据id自增不填写报错

### ISSUE THREAD

**Issue by liugongliushang** [chat2db/Chat2DB#865]
### Chat2DB Version

3.0.13

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/42638927/947869bd-bde0-4bed-b3ca-2e72c346eb57)

**Comment by tmlx1990** [comment]
您好，刚测试了没有复现，能提供下详细信息吗？
![image](https://github.com/chat2db/Chat2DB/assets/5753992/e6886662-b64c-41f3-b337-54db27a78ee1)
![image](https://github.com/chat2db/Chat2DB/assets/5753992/676c8191-ee39-4dc5-b559-37024edecab8)

**Comment by liugongliushang** [comment]
https://github.com/chat2db/Chat2DB/assets/42638927/1ce33cc0-7759-4563-a36d-ef6db8c422a2

复制行删掉id在保存出现的
