### ISSUE TITLE
Bug: MySQL database creation date field does not update field settings based on timestamp

### ISSUE THREAD

**Issue by liugongliushang** [chat2db/Chat2DB#866]
### Chat2DB Version

3.0.13

### Describe the bug

![93df8d6cc82cd5576766c98671e8fba](https://github.com/chat2db/Chat2DB/assets/42638927/343923a4-6ebd-44a1-9649-2d7cf45f7f1d)
There is no such setting in the picture

**Comment by tmlx1990** [comment]
现在用的是默认值设置，直接选这个就是插入数据时候的当前时间当默认值。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/588c863b-0940-497f-9c91-58fc72a676c4)

**Comment by liugongliushang** [comment]
当我更新数据的时候这个时间不会跟新啊

**Comment by tmlx1990** [comment]
> 当我更新数据的时候这个时间不会跟新啊

您好，目前还有没开发更新时的操作。后边会排期开发的。

**Comment by miahemu** [comment]
Hi, the new PRO version has solved this problem.
<img width="714" alt="image" src="https://github.com/user-attachments/assets/63010525-8f76-4af5-84cd-92719e4101fa">

**Comment by miahemu** [comment]
The community version will fix this bug soon
