### ISSUE TITLE
Bug: ai optimization sql keeps prompting

### ISSUE THREAD

**Issue by lanayahebefan** [chat2db/Chat2DB#879]
### Chat2DB Version

3.0.14

### Describe the bug

<img width="983" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39938163/e4f32c12-2cde-46fe-8f81-b9b44c974ee8">
Already paying attention. Have you used up the daily free times?

**Comment by lanayahebefan** [comment]
<img width="1175" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39938163/4cb35bec-7024-4b5e-9df8-480c10a5d1ae">
找到日志 提示 限制

**Comment by lanayahebefan** [comment]
<img width="1263" alt="image" src="https://github.com/chat2db/Chat2DB/assets/39938163/e4763c91-e20a-4337-810e-1f725de10716">
使用过一次ai功能之后后台会一直调用 然后就把次数耗尽了

**Comment by fanjinyu-fjy** [comment]
给一个最小化复现的路径呢？

**Comment by miahemu** [comment]
try new version
