### ISSUE TITLE
优化: 连接Oracle没有地方选择ServiceName方式登录，只有SID方式

### ISSUE THREAD

**Issue by xiaowanziwuha2** [chat2db/Chat2DB#880]
![image](https://github.com/chat2db/Chat2DB/assets/56863469/c1b94464-72de-481d-92c8-e5c5c51f872b)

**Comment by tmlx1990** [comment]
> ![image](https://user-images.githubusercontent.com/56863469/285097833-c1b94464-72de-481d-92c8-e5c5c51f872b.png)

您好，目前是可以选择的，您下载最新版试试。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/59995e89-df00-41c0-aa50-0899c734e0f3)
