### ISSUE TITLE
优化: chat2DB的能力还是很弱，已经很详细的描述了查询需求，生成的sql还是不对

### ISSUE THREAD

**Issue by PaulCoffee-zh** [chat2db/Chat2DB#883]

**Comment by StevenChina** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/10328189/d58c3664-debb-482a-840d-91b7aa3bb875)

**Comment by tmlx1990** [comment]
> ![image](https://user-images.githubusercontent.com/10328189/285135038-d58c3664-debb-482a-840d-91b7aa3bb875.png)

试试查询task_info表中cron_status字段为RUNNING的数据呢？

**Comment by StevenChina** [comment]
嗯， 可以的
