### ISSUE TITLE
Bug: 表数据不能复制

### ISSUE THREAD

**Issue by hantiancai** [chat2db/Chat2DB#888]
### Chat2DB Version

3.0.14

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/64368321/9ff4cf94-eb5a-4fc6-ac3a-0a2d1246a2e6)
点击复制之后没有响应

**Comment by tmlx1990** [comment]
> ### Chat2DB Version
> 3.0.14
> 
> ### Describe the bug
> ![image](https://user-images.githubusercontent.com/64368321/285383383-9ff4cf94-eb5a-4fc6-ac3a-0a2d1246a2e6.png) 点击复制之后没有响应

您好，刚测试了没有您这个问题。复制后按ctrl+v可以粘贴的

**Comment by DimonHo** [comment]
> > > ### Chat2DB 版本
> > > 3.0.14
> > > ### 描述错误
> > > ![图像](https://user-images.githubusercontent.com/64368321/285383383-9ff4cf94-eb5a-4fc6-ac3a-0a2d1246a2e6.png)点击复制之后没有响应
> > 
> > 
> > 您好，刚测试了没有您这个问题。复制后按ctrl+v可以粘贴的
> 
> ![image](https://private-user-images.githubusercontent.com/3371641/285766265-883ae03e-1e9f-4f75-8bd1-d2a264c25535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjAwODUsIm5iZiI6MTcwMjM1OTc4NSwicGF0aCI6Ii8zMzcxNjQxLzI4NTc2NjI2NS04ODNhZTAzZS0xZTlmLTRmNzUtOGJkMS1kMmEyNjRjMjU1MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDU0MzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY0ZWExNGZiM2ExMWMzOTMxMmM4YWY3MTI0NWJmYmRjMGQ3MDc1M2UxMGFhODM0YzljZjQ1NGM1OTM3ZjBkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m4lYvS-0xFk67w1x9_GgM2dqQ0KIHFgLpYjSquDdvII)我也遇到这个问题了，点复制后，控制台打印了这个异常

解决办法在这里：#935
