### ISSUE TITLE
建议: 

### ISSUE THREAD

**Issue by akhfasarrofi** [chat2db/Chat2DB#89]
is there any plan to make documentation in english?

**Comment by Huyang999** [comment]
修改连接信息的时候需要再次输入密码，不能记住密码

**Comment by CodingGorit** [comment]
When modifying the connection information, you need to enter the password again, and you cannot remember the password

> is there any plan to make documentation in english?

**Comment by chenxian01** [comment]
> is there any plan to make documentation in english?

The default README version is in english right now.

**Comment by chenxian01** [comment]
> 

Fixed in the latest version.
