### ISSUE TITLE
Bug: Packet for query is too large (4,739,923 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable.: null

### ISSUE THREAD

**Issue by ziliangzeng** [chat2db/Chat2DB#91]
### Chat2DB Version

v1.0.10

### Describe the bug

尝试登录mysql 输入线上测试数据库时候，显示
Packet for query is too large (4,739,923 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable.: null
使用navicate等都是可以正常登录的

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.

**Comment by 12345ZMTHL** [comment]
加一，目前也遇到，楼主怎么解决的呀？

> ### Chat2DB Version
> v1.0.10
> 
> ### Describe the bug
> 尝试登录mysql 输入线上测试数据库时候，显示 Packet for query is too large (4,739,923 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable.: null 使用navicate等都是可以正常登录的
