### ISSUE TITLE
建议: 增加复制连接的功能

### ISSUE THREAD

**Issue by DvShu** [chat2db/Chat2DB#912]
线上数据库有点多，又做了限制只能指定ip访问，这个时候只能通过 ssh 方式访问，但是大多数配置都是一样的，就只有密码不一样，每次配置一个有点繁琐。建议增加一个 Heidisql 的复制会话的功能。
![1701674130954](https://github.com/chat2db/Chat2DB/assets/10515836/157ef78b-3bf6-4ae6-9d8d-7ab6a30fc29a)

**Comment by shanhexi** [comment]
3.1.17 已支持
