### ISSUE TITLE
Bug: 多SQL并且由注释时候格式化有bug

### ISSUE THREAD

**Issue by yanceysong** [chat2db/Chat2DB#920]
### Chat2DB Version

3.0.14

### Describe the bug

多SQL并且有注释时候格式化有bug，以下的SQL脚本格式化不正确。
-- 20231204-1340
-- submitter_name='xxxx', component_name='xxxx', changeset_id='',file_name='xxxxx'
delete from data_connection_pair where data_name ='basic_material';

INSERT INTO data_connection_pair([data_name], [connection_name], [_d]) VALUES (N'basic_material', N'SECOND-DEV', 0);

delete关键会变成注释的一部分，并且insert没有另起一行

![1701830967998](https://github.com/chat2db/Chat2DB/assets/60731354/f7472a44-ff6f-40f4-b6f0-cccc738e538a)

**Comment by fanjinyu-fjy** [comment]
是MySQL吗？

**Comment by yanceysong** [comment]
> 是MySQL吗？


您好 是SqlServer

**Comment by yanceysong** [comment]
底层调用的hutool的SqlFormatter.format(sql);方法，似乎这个方法就不正确

**Comment by tmlx1990** [comment]
应该所有的都会有问题，底层用的hutool的

**Comment by yanceysong** [comment]
> 应该所有的都会有问题，底层用的hutool的

是的，这个会解决吗？

**Comment by tmlx1990** [comment]
> > 应该所有的都会有问题，底层用的hutool的
> 
> 是的，这个会解决吗？

我先看看有没有办法能解决。
