### ISSUE TITLE
Bug: PostgreSql无法正确识别库名

### ISSUE THREAD

**Issue by listenLearning** [chat2db/Chat2DB#93]
### Chat2DB Version

V1.0.11

### Describe the bug

当没有输入库名的时候，Chat2DB会默认将用户名当作库名处理
![微信图片_20230629102312](https://github.com/chat2db/Chat2DB/assets/25893114/9b310a8a-9058-4c57-96d9-347adccba146)

**Comment by chenxian01** [comment]
The version 1.x will not be supported, please try the latest version.
