### ISSUE TITLE
Bug: WEB 版本的数据库连接管理页面分页无法翻页、或者是页面改为50 无法进行滚动

### ISSUE THREAD

**Issue by maohaoming** [chat2db/Chat2DB#932]
### Chat2DB Version

Chat2DB3.0.10

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/30396726/13c37fdf-bdd5-4385-8580-479e38733159)

**Comment by tmlx1990** [comment]
您好，升级到3.0.14试试。目前3.0.14没有出现这个问题。
![image](https://github.com/chat2db/Chat2DB/assets/5753992/bfd781d1-2cb6-493b-b44f-0c26337289d5)

**Comment by DimonHo** [comment]
> ### Chat2DB Version
> Chat2DB3.0.10
> 
> ### Describe the bug
> ![image](https://private-user-images.githubusercontent.com/30396726/288661702-13c37fdf-bdd5-4385-8580-479e38733159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTM5NzgsIm5iZiI6MTcwMTk1MzY3OCwicGF0aCI6Ii8zMDM5NjcyNi8yODg2NjE3MDItMTNjMzdmZGYtYmRkNS00Mzg1LTg1ODAtNDc5ZTM4NzMzMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODAyZTkzYTk2OTE4NTZlZjAyODgwYjQ5NjU3NTliMGZkZTVhYjdiZDE2MTRiMjUxNjJlZTZhYjU4NDExNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V1sAW3gTYv4M87qIJXf2hPTin2Bp9lVGIRiuzBsHjh0)

可能是web版本前端编译有问题，我之前也出现过这个问题，拉的最新代码，后来重新编译打包后又好了。。。
