### ISSUE TITLE
Bug:通过ssh连接mysql，ssh测试连接成功，mysql连接失败 

### ISSUE THREAD

**Issue by xufeifan1992** [chat2db/Chat2DB#94]
### Chat2DB Version

当前版本:v0.0.0 build 20230616055221

### Describe the bug

Bug:通过ssh连接mysql，ssh测试连接成功，mysql连接失败

**Comment by VioletXQ** [comment]
+1 我这边同样碰到这个问题了。  Windows版本：1.0.11
COMMON_SYSTEM_ERROR:系统开小差啦，请尝试刷新页面或者联系管理员

![image](https://github.com/chat2db/Chat2DB/assets/38678550/9ededc83-ec22-454e-93bf-faaf2af2fd85)

**Comment by xufeifan1992** [comment]
> +1 我这边同样碰到这个问题了。Windows版本：1.0.11 COMMON_SYSTEM_ERROR：系统开小差啦，请尝试刷新页面或者联系管理员
> 
> ![image](https://user-images.githubusercontent.com/38678550/249663046-9ededc83-ec22-454e-93bf-faaf2af2fd85.png)

对 bug还是比较多

**Comment by GeziGuo** [comment]
同样遇到这个问题

**Comment by zhaoest** [comment]
ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的

**Comment by xufeifan1992** [comment]
> ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的

我试了本地端口，填多少啊，我ssh服务端的端口和22端口都不好使

**Comment by zhaoest** [comment]
> > ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的
> 
> 我试了本地端口，填多少啊，我ssh服务端的端口和22端口都不好使

我填了个那个配置里本地web服务的端口，不报错，但是超时。目前推测应该是连本地后端服务的端口

**Comment by xufeifan1992** [comment]
> > > ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的
> > 
> > 
> > 我试了本地端口，填多少啊，我ssh服务端的端口和22端口都不好使
> 
> 我填了个那个配置里本地web服务的端口，不报错，但是超时。目前推测应该是连本地后端服务的端口

我只是想连云端数据库啊，本地也没有服务啊，搞不清楚要写啥

**Comment by zhaoest** [comment]
> > > > ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的
> > > 
> > > 
> > > 我试了本地端口，填多少啊，我ssh服务端的端口和22端口都不好使
> > 
> > 
> > 我填了个那个配置里本地web服务的端口，不报错，但是超时。目前推测应该是连本地后端服务的端口
> 
> 我只是想连云端数据库啊，本地也没有服务啊，搞不清楚要写啥

你要不试试开个外网访问的端口，别用ssh了，哈哈哈

**Comment by xufeifan1992** [comment]
> > > > > ssh那个本地端口的问题，空的过不去，然后又不知道本地端口干嘛的
> > > > 
> > > > 
> > > > 我试了本地端口，填多少啊，我ssh服务端的端口和22端口都不好使
> > > 
> > > 
> > > 我填了个那个配置里本地web服务的端口，不报错，但是超时。目前推测应该是连本地后端服务的端口
> > 
> > 
> > 我只是想连云端数据库啊，本地也没有服务啊，搞不清楚要写啥
> 
> 你要不试试开个外网访问的端口，别用ssh了，哈哈哈

哈哈，那得公司掏钱，还是用navicat吧

**Comment by zengjianjay** [comment]
+1

**Comment by chat2db-yx** [comment]
2.0.1已经修复

**Comment by xufeifan1992** [comment]
> 2.0.1已经修复
这边测试，依旧报错，只是报错内容变化了
![image](https://github.com/chat2db/Chat2DB/assets/23428194/fc543811-7506-4a7b-b2fb-b229a1754353)

**Comment by zhaoest** [comment]
> > 2.0.1已经修复
> > 这边测试，依旧报错，只是报错内容变化了
> > ![image](https://user-images.githubusercontent.com/23428194/250702515-fc543811-7506-4a7b-b2fb-b229a1754353.png)

压根就没修复，这都连不上啊，都不用ssh吗？

**Comment by xufeifan1992** [comment]
> > > 2.0.1已经修复
> > > 这边测试，依旧报错，只是报错内容变化了
> > > ![image](https://user-images.githubusercontent.com/23428194/250702515-fc543811-7506-4a7b-b2fb-b229a1754353.png)
> 
> 压根就没修复，这都连不上啊，都不用ssh吗？

是 压根没修复，用ssh的少呗，我还以为阿里效率挺快呢，都回复我修复完成了
