### ISSUE TITLE
Bug: 通过ssh连接redis，redis不能输入空用户名，是必填值，否则返回报错

### ISSUE THREAD

**Issue by xufeifan1992** [chat2db/Chat2DB#95]
### Chat2DB Version

当前版本:v0.0.0 build 20230616055221

### Describe the bug

Bug: 通过ssh连接redis，redis不能输入空用户名，是必填值，否则返回报错
![image](https://github.com/chat2db/Chat2DB/assets/23428194/4cfbfa34-fbb2-4c77-be12-490f8b6e6f01)

**Comment by robinji0** [comment]
marked in #402
