### ISSUE TITLE
Bug: Connecting to the Mysql8.0.30 system library information_schema can only query the relevant tables, but you can use other tools to query it.

### ISSUE THREAD

**Issue by PastWillNotline** [chat2db/Chat2DB#963]
### Chat2DB Version

3.1.11

### Describe the bug

Connecting to the Mysql8.0.30 system library information_schema can only query the relevant tables, which can be queried using other tools.

**Comment by PastWillNotline** [comment]
![image](https://github.com/chat2db/Chat2DB/assets/18674238/566f2a14-7fc1-4498-9ac2-14cf88e6ad5a)
![image](https://github.com/chat2db/Chat2DB/assets/18674238/d2346e3d-b2f2-494f-aac8-44e565914e3b)

**Comment by miahemu** [comment]
try pro version
https://chat2db.ai/zh-CN/download
