### ISSUE TITLE
Bug: Mysql连接成功后，筛选数据库后，无法展开数据库详情

### ISSUE THREAD

**Issue by charwu** [chat2db/Chat2DB#967]
### Chat2DB Version

v3.1.11

### Describe the bug

未筛选前：
![image](https://github.com/chat2db/Chat2DB/assets/16216736/cfd6156c-fe63-4e38-a512-05cc069edfad)

筛选后:
![image](https://github.com/chat2db/Chat2DB/assets/16216736/c159b849-b5d1-485c-a499-6dc7735f733d)

**Comment by shanhexi** [comment]
已修复 更新新版本 3.1.14
