### ISSUE TITLE
Bug: sqlite

### ISSUE THREAD

**Issue by qycwudi** [chat2db/Chat2DB#968]
### Chat2DB Version

3.1.11

### Describe the bug

The table list on the left side of the sqlite database is empty, and the content can be found in the query statement.
![image](https://github.com/chat2db/Chat2DB/assets/49853496/77d06ac3-414e-43c5-9f48-972bbc628772)

**Comment by miahemu** [comment]
你好，这边复现了一遍没有问题。现在你那边依然还有这种问题吗？

**Comment by miahemu** [comment]
try new version
https://chat2db.ai/zh-CN/download
