### ISSUE TITLE
Bug: clickhouse cannot obtain the table of engine = Memory

### ISSUE THREAD

**Issue by PulLa1** [chat2db/Chat2DB#969]
### Chat2DB Version

3.1.11

### Describe the bug

Clickhouse data source, the left sidebar cannot query the table whose engine is memory.
```
create table order
(
    Order_Id      Nullable(String)
)
    engine = Memory;
```

**Comment by PulLa1** [comment]
我想修复这个bug 可以指派给我吗

**Comment by fanjinyu-fjy** [comment]
修复了,提pr即可
