### ISSUE TITLE
Bug: 双击表查看数据时报错无法查看数据

### ISSUE THREAD

**Issue by HighSpecific** [chat2db/Chat2DB#982]
### Chat2DB Version

3.1.13

### Describe the bug

{
  "getApplicationMessage": {
    "env": "desktop",
    "versions": "3.1.13",
    "buildTime": 1702654739906,
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) chat2db/3.0.14 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36"
  },
  "requestUrl": "http://127.0.0.1:10824/api/rdb/dml/execute_table",
  "requestParams": "{\"sql\":\"select * from `order`\",\"tableName\":\"order\",\"pageNo\":1,\"pageSize\":200,\"total\":0,\"hasNextPage\":true,\"dataSourceId\":2,\"databaseType\":\"MYSQL\",\"databaseName\":\"tn_management_system\",\"type\":\"MYSQL\"}",
  "errorCode": null,
  "errorMessage": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order' at line 1",
  "errorDetail": null,
  "solutionLink": null
}

**Comment by shanhexi** [comment]
新接口 execute_table，sql是后端拼的，需要给表名包一下`order`

**Comment by leven-space** [comment]
建议修改为 前端传入 table name时自动带入`table name`

![image](https://github.com/chat2db/Chat2DB/assets/31175045/d22ccfc8-e563-4623-919f-e76d77cad9ce)
