### ISSUE TITLE
Bug: 使用过滤功能过滤的结果无法展开，望解决一下

### ISSUE THREAD

**Issue by Yanch1994** [chat2db/Chat2DB#986]
### Chat2DB Version

v3.1.11

### Describe the bug

<img width="228" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/8c407a0e-bc7f-456b-8089-0674f2198f23">

**Comment by shanhexi** [comment]
3.1.14已修复

**Comment by Yanch1994** [comment]
抱歉 14版已修复，刚想过来自己关掉
