### ISSUE TITLE
Bug: 修改表结构 对字段进行拖动排序不生效

### ISSUE THREAD

**Issue by Yanch1994** [chat2db/Chat2DB#992]
### Chat2DB Version

v3.1.14

### Describe the bug

<img width="614" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/aecd3833-e798-4a63-aeff-2df1d8032608">
<img width="651" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/9dfc1806-dfcd-4dd2-9fed-45673a2e702c">
<img width="1609" alt="image" src="https://github.com/chat2db/Chat2DB/assets/28883972/9a5f6a36-5471-40e5-93c0-a22739e0333d">
生成的sql就不对

**Comment by tmlx1990** [comment]
> ### Chat2DB Version
> v3.1.14
> 
> ### Describe the bug
> <img alt="image" width="614" src="https://private-user-images.githubusercontent.com/28883972/291466033-aecd3833-e798-4a63-aeff-2df1d8032608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTY4NjMsIm5iZiI6MTcwMjk1NjU2MywicGF0aCI6Ii8yODg4Mzk3Mi8yOTE0NjYwMzMtYWVjZDM4MzMtZTc5OC00YTYzLWFlZmYtMmRmMWQ4MDMyNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZTFiOGJiYWJhMzRkYTE1ZGExOGQ2NTE1YjE3MGFhMzcyYjAwMGU3ZDJiMDU5Y2NiMTFkNTY5MzFlZDhhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poVmTgtYjNvgRMGOUqmhCUSfuYb4AkA5P5tqljgXUHs"> <img alt="image" width="651" src="https://private-user-images.githubusercontent.com/28883972/291466093-9dfc1806-dfcd-4dd2-9fed-45673a2e702c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTY4NjMsIm5iZiI6MTcwMjk1NjU2MywicGF0aCI6Ii8yODg4Mzk3Mi8yOTE0NjYwOTMtOWRmYzE4MDYtZGZjZC00ZGQyLTlmZWQtNDU2NzNhMmU3MDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YmNlY2ZjMTg5MWI2Yzc4ZTIxYWNhZjkzYWUxYzRlOTU1ZTVjZTFjYzRjM2I4OGU3OTk3ZjA1OWIxNWIwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UadlkSKuImtlEOqekTR9JJTfcIRgRzRx5c05Zf8B3sY"> <img alt="image" width="1609" src="https://private-user-images.githubusercontent.com/28883972/291466158-9a5f6a36-5471-40e5-93c0-a22739e0333d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTY4NjMsIm5iZiI6MTcwMjk1NjU2MywicGF0aCI6Ii8yODg4Mzk3Mi8yOTE0NjYxNTgtOWE1ZjZhMzYtNTQ3MS00MGU1LTkzYzAtYTIyNzM5ZTAzMzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjM3YTBmM2I0MTNhMjAzNGU1MTk2MDkzZTZjMDI2NGVmNjBlNWQ4ZGQ0NmE2Y2E2NWQ1ZWI0ZWVkZDM1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1ArMbKjlvdNGJXUNjgRVYUwhX0E8V6H0IWGn-pRg5A"> 生成的sql就不对

这个拖拽功能目前有问题。还在修复中。

**Comment by shanhexi** [comment]
3.1.17已修复
