### ISSUE TITLE
Bug: 表显示不全

### ISSUE THREAD

**Issue by jiangwenping** [chat2db/Chat2DB#994]
### Chat2DB Version

Chat2DB v3.1.14

### Describe the bug

单库表超过1000个时，只显示1000条以后的表

**Comment by shanhexi** [comment]
会持续懒加载呀

**Comment by jiangwenping** [comment]
加载的时候闪了一下，第二页表数据把第一页表数据覆盖了，右键查看所有表能看到是两页数据
