### ISSUE TITLE
Bug: ClickHouse database table does not display data

### ISSUE THREAD

**Issue by gm100861** [chat2db/Chat2DB#997]
### Chat2DB Version

3.1.14

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/3993839/8aa0d242-49eb-4de6-a1f6-7f256f8f74ba)
![image](https://github.com/chat2db/Chat2DB/assets/3993839/401556cb-bc90-47d0-a1e8-c612ecc0aba6)

**Comment by miahemu** [comment]
try new version
<img width="1247" alt="image" src="https://github.com/chat2db/Chat2DB/assets/157001655/3fde9ab2-9e94-4d87-b1eb-727f71b71e75">
